@startuml
!pragma layout smetana

!include <C4/C4_Container>
!include <tupadr3/font-awesome-5/user>
!include <tupadr3/font-awesome-5/mobile_alt>
!include <tupadr3/devicons2/android>
!include <tupadr3/devicons2/apple_original>

System_Boundary(kv, "Fachdienste der Krankenkasse") {
    Container(push, "Push-Gateway", "Zentrales Push Gateway")
    Container(epa, "ePA-Fachdienst", "Backend der ePA-Anwendung")  
    Container(erezept, "eRezept-Fachdienst", "Backend der ePA-Anwendung")
    Container(tim, "TI-Messenger-Fachdienst", "Backend der TI-Messenger Anwendung")
}
Rel(epa, push, "")
Rel(erezept, push, "")
Rel(tim, push, "")

System_Boundary(pp, "Anbieter von Smartphone Betriebssystemen") {
    System_Ext(fcm, "Push-Gateway", "Push Dienst von Google", $sprite=android)
    System_Ext(apn, "Push-Gateway", "Push Dienst von Apple", $sprite=apple_original)
} 
Rel(push, fcm, "")
Rel(push, apn, "")

AddBoundaryTag("Endanwender", $legendText="Endanwender")
Boundary(ug1, "Anwender mit einem Smartphone\n mit Android Betriebssystemen") {
    Container(s1, "ePA-App(FDV)", "", $sprite=mobile_alt)
    Container(s2, "ePA-App(FDV)", "", $sprite=mobile_alt)
    Person(u1, "Versicherter")
    Person(u2, "Versicherter")
    Rel_U(u1, s1, "")
    Rel_U(u2, s2, "")
}
Rel(fcm, s1, "")
Rel(fcm, s2, "")


Boundary(ug2, "Anwender mit einem Smartphone\n mit Apple Betriebssystemen") {
    Container(s3, "ePA-App(FDV)", "", $sprite=mobile_alt, $tags="Endanwender")
    Container(s4, "ePA-App(FDV)", "", $sprite=mobile_alt)
    Person(u3, "Versicherter")
    Person(u4, "Versicherter")
    Rel_U(u3, s3, "")
    Rel_U(u4, s4, "")
}
Rel(apn, s3, "")
Rel(apn, s4, "")

SHOW_LEGEND()
'Rel(personAlias, containerAlias, "Label", "Optional Technology", "Optional Description")
@enduml