@startuml
!pragma layout smetana

!include <C4/C4_Container>
!include <tupadr3/font-awesome-5/user>
!include <tupadr3/font-awesome-5/mobile_alt>
!include <tupadr3/devicons2/android>
!include <tupadr3/devicons2/apple_original>

AddContainerTag(er, #Green, $legendText="Bereitstellung durch die gematik")
Container_Ext(erezept, "eRezept-Fachdienst", "Backend der eRezept-Anwendung", $tags=er)

AddContainerTag(kk, $legendText="Bereitstellungen der Krankenkasse")
Container_Boundary(kv, "Fachdienste der Krankenkasse") {
    Container(push, "Push-Gateway", "Zentrales Push Gateway", $tags=kk)
    Container(epa, "ePA-Fachdienst", "Backend der ePA-Anwendung", $tags=kk)  
    Container(tim, "TI-Messenger-Fachdienst", "Backend der TI-Messenger Anwendung", $tags=kk)
}

Rel(epa, push, "")
Rel(erezept, push, "")
Rel(tim, push, "")

AddBoundaryTag(push, #LightGray, $legendText=Anbieter von Smartphone Betriebssystemen, $borderColor=#Black)
AddContainerTag(pd, #Gray, $legendText=Push-Dienste)
Container_Boundary(pp, "", $tags=push) {
    Container(fcm, "Push-Gateway", "Push Dienst von Google", $tags=pd, $sprite=android)
    Container(apn, "Push-Gateway", "Push Dienst von Apple", $tags=pd, $sprite=apple_original)
} 
Rel(push, fcm, "")
Rel(push, apn, "")

AddPersonTag(Endanwender, $legendText=Endanwender)
Boundary(ug1, "Anwender mit einem Smartphone\n mit Android Betriebssystemen") {
    Container(s1, "ePA-App(FDV)", "", $sprite=mobile_alt, $tags=kk)
    Container(s2, "ePA-App(FDV)", "", $sprite=mobile_alt, $tags=kk)
    Person(u1, "Versicherter", $tags=Endanwender)
    Person(u2, "Versicherter", $tags=Endanwender)
    Rel_U(u1, s1, "")
    Rel_U(u2, s2, "")
}
Rel(fcm, s1, "")
Rel(fcm, s2, "")


Boundary(ug2, "Anwender mit einem Smartphone\n mit Apple Betriebssystemen") {
    Container(s3, "ePA-App(FDV)", "", $sprite=mobile_alt, $tags=kk)
    Container(s4, "ePA-App(FDV)", "", $sprite=mobile_alt, $tags=kk)
    Person(u3, "Versicherter", $tags=Endanwender)
    Person(u4, "Versicherter", $tags=Endanwender)
    Rel_U(u3, s3, "")
    Rel_U(u4, s4, "")
}
Rel(apn, s3, "")
Rel(apn, s4, "")


SHOW_LEGEND()
@enduml