/' 
# UC - 10104
# Name: Einladung von Akteuren innerhalb einer Organisation
'/

@startuml
skinparam sequenceMessageAlign direction
skinparam minClassWidth 200
skinparam BoxPadding 1
skinparam sequenceReferenceHeaderBackgroundColor palegreen
skinparam sequenceReferenceBackgroundColor Beige
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20
}
autonumber

    actor U1 as "Akteur - A in\nder Rolle User"
    participant C1 as "TI-Messenger-\nClient A" #AliceBlue
    box <size:18>Messenger-Service</size> #WhiteSmoke
      participant MP as "Messenger-\nProxy"
      participant MH as "Matrix-Homeserver \n(inklusive Nutzerverzeichnis)"
    end box
    participant PG as "Push-\nGateway"
    participant C2 as "TI-Messenger-\nClient B"#TECHNOLOGY
    actor U2 as "Akteur - B in\nder Rolle User"
    
|||
note over U1, U2: \n<size:17>Die Akteure sind auf dem selben Messenger-Service angemeldet und im Besitz eines zugelassenen TI-Messenger-Clients.\n<size:17>Ein Chatraum wurde durch den Einladenen eingerichtet.</size>\n
|||

    opt#LightGrey #AliceBlue <size:16>Akteur suchen</size>
    |||
    U1->C1: Suche Akteur B
      activate C1
    C1->MP: POST /_matrix/client/\nuser_directory/search
      activate MP
    MP->MH: HTTP(S) Forward
      activate MH
    MH-->MH: Nutzerverzeichnis \ndurchsuchen
    MH-->MP: MXID
      deactivate MH
    MP-->C1: HTTP(S) Forward
      deactivate MP
    |||
    end
    
    |||
    U1->C1: Akteur B einladen
    C1->MP: POST /_matrix/client/v3/\nrooms/{roomId}/invite
      activate MP
    
    |||
      ref over MP, MP: <size:17><b>Berechtigungsprüfung</size>\n 
    |||
    
    alt#LightGrey #AliceBlue <size:16>Matrix-Domain nicht in der Föderation enthalten</size>
      |||
      MP-->C1: HTTP 401 \nUnauthorized
      C1-->U1: Einladung nicht \nerfolgreich
        |||

    
      else <size:16>Matrix-Domain in der Föderation enthalten</size>
    
      MP->MH: HTTP(S) Forward
        activate MH
      MH->MH: Invite verarbeiten
      MH-->MP: HTTP 200
      MP-->C1: HTTP(S) Forward
        deactivate MP
      |||
        opt#LightGrey #LightBlue <size:16>Push-Benachrichtigung</size>
          |||
          MH->PG: POST /_matrix/push/notify
            activate PG
          PG->C2: Notification
          activate C2
          PG-->MH: Status
            deactivate PG
        |||
        end
        |||
          
          C2->MP: Sync Request
            activate MP
          MP->MH: HTTP(S) Forward
          MH-->MP: Sync Response
          MP-->C2: HTTP(S) Forward

          C2->U2: Einladung anzeigen
          U2-->C2: Einladung bestätigen
          C2->MP: join
          MP-->MH: HTTP(S) Forward
          MH->MH: join verarbeiten
          MH-->MP: Room ID
            deactivate MH
          MP-->C2: HTTP(S) Forward
            deactivate MP
          C2-->U2: Nutzer ist dem \nRaum beigetreten
            deactivate C2

          C1->MP: Sync Request
            activate MP
          MP->MH: HTTP(S) Forward
            activate MH
          MH-->MP: Sync Response
          deactivate MH
          MP-->C1: HTTP(S) Forward
          deactivate MP
          C1-->U1: Akteur B ist dem Raum\nRaum beigetreten
          deactivate C1
        |||
        end
 |||
@enduml
