/'
# TI-Messenger 1.1
# TI-Messenger-Dienst
# UC - 10103
# Sequence Diagram
# Name: Authentisieren einer Organisation am TI-Messenger-Dienst
'/

@startuml "Authentisieren einer Organisation am TI-Messenger-Dienst"
skinparam sequenceMessageAlign direction
skinparam WrapWidth 300
skinparam minClassWidth 150
skinparam BoxPadding 1
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontName Impact
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20
ActorFontName Aapex
}

  actor oa as "Akteur in der Rolle\nOrg-Admin"
    box <size:19>Endgerät</size> #WhiteSmoke
    participant wb as "Frontend des \nRegistrierungs-Dienstes"
    participant au as "Authenticator"
    end box
  participant ko as "Konnektor"
  participant kt as "eHealth KT"
  participant rd as "Registrierungs-Dienst"
  participant ip as "zentraler \nIDP-Dienst"

|||
alt#LightGrey #AliceBlue <size:16>Organisation nicht am Registrierungs-Dienst authentisiert</size>
|||
      oa -> wb: Organisation verifizieren \n(Verfahren auswählen)
      alt#LightGrey #LightBlue <size:16>OpenID Connect</size>
          activate wb
        wb -> rd:POST I_Registration
        note right: <size:16>Schnittstelle wird nicht \n<size:16>durch die gematik spezifiziert</size>
          activate rd
        rd --> wb: Redirect to IDP Authorization Endpoint
          deactivate rd
        |||
        wb -> ip: GET /authorize
          activate au
          activate ip
        ip -> au: Authentication challenge
        au -> ko: ExternalAuthenticate
          activate ko
        ko -> kt: SICCT command
          activate kt
        kt --> ko
          deactivate kt
        ko --> au: Response \nExternalAuthenticate
        |||
          deactivate ko

      opt #MistyRose <size:15>Abbruch</size>
        au -> oa: SMC-B nicht freigeschaltet
        |||
      end
        |||
        au -->ip: Authentication response
          deactivate au
        ip --> wb: Authorization code
          deactivate ip
        |||
        wb -> rd: POST /register (Authorization code)
          activate rd
        rd -> ip: POST /tokenEndpoint\n{authorization code}
          activate ip
        ip --> rd: id_token
          deactivate ip
        |||
        rd -> rd: enthaltene \nProfessionOID auf \ngültige Organisation \nprüfen
        |||
      else <size:16>KIM - Verfahren</size>
        |||
        oa -> rd: KIM-Adresse in Eingabemaske eintragen (POST I_Registration)
        rd -> rd: Abfrage des LDAP-Directory\nEintrags zur KIM-Adresse
        |||
        rd -> rd: Speicherung der telematikId\nund der professionOID
        |||
        rd -> rd: ProfessionOID auf\ngültige Organisation\nprüfen
        |||
        rd -> oa: KIM Nachricht mit URL
        oa -> rd: URL in KIM-Nachricht öffnen
        |||
      end
      |||

    opt #MistyRose <size:15>Abbruch</size>
      rd -> wb: keine gültige ProfessionOID gefunden
      wb -> oa: Authentisierung fehlgeschlagen
      |||
    end

      |||
      rd-> rd: Organisation \nauthentifizieren
      |||
      rd -> rd : Prüfung auf existierenden Admin Account
      |||
        opt #MistyRose <size:15>Abbruch</size>
         rd -> oa: Organisation bereits authentifiziert und ein Admin-Account existiert bereits
         |||
        end
      |||
      rd --> wb: status
        deactivate rd
      wb --> oa: Verifizierung erfolgreich
      |||
      oa -> wb: Admin Account anlegen \n(Passwort + 2. Faktor)
      wb -> rd: POST I_Registration (Admin-Account Credentials + 2. Faktor)
      note right: <size:16>Schnittstelle wird nicht \n<size:16>durch die gematik spezifiziert</size>
        activate rd
      |||
      rd -> rd: Credentials-Policy prüfen
      |||
      rd -> rd: Org-Admin Account\nfür die Organisation \nanlegen
      rd --> wb: status
       deactivate rd
      wb --> oa: Account angelegt
       deactivate wb
      |||
end
|||
@enduml
