/' 
# TI-Messenger 1.1
# TI-Messenger-Dienst
# UC - 10057
# Sequence Diagram
# Name: Anmeldung eines Akteurs am Messenger-Service
'/

@startuml
skinparam sequenceMessageAlign direction
skinparam minClassWidth 200
skinparam BoxPadding 1
skinparam sequenceReferenceHeaderBackgroundColor palegreen
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontName Impact
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20
ActorFontName Aapex
}
    actor U as "Akteur in der Rolle\nUser / User-HBA"
    participant C as "TI-Messenger-Client"
    box <size:18>Messenger-Service</size> #WhiteSmoke
      participant MP as "Messenger Proxy"
      participant MH as "Matrix-Homeserver"
    end box
    box <size:18>VZD-FHIR-Directory</size> #WhiteSmoke
      participant Auth as "Auth-Service"
      participant FP as "FHIR-Proxy"
    end box

|||
  U->C: Eingabe Messenger-Service \n(Manuell oder \ndurch Auswahl)
    Activate C
  C->MP: GET /_matrix/client/login
    Activate MP
  MP->MP: TLS-Terminierung
  MP->MP: überprüfe User-Agent, \nClient-Secret

|||
alt#LightGrey #AliceBlue <size:16>TI-Messenger Client wird vom Anbieter nicht unterstützt (kein gültiges Client-Secret)</size>
|||  

  MP-->C: HTTP 401 Unauthroized
  C-->U: Anmeldung \nnicht erfolgreich
  
    |||  
    else <size:16>TI-Messenger Client wird vom Anbieter unterstützt  (gültiges Client-Secret)</size>
    |||

  MP->MH: HTTP Forward
   Activate MH

|||
note over U, MH: <size:17>Die Authentifizierungsverfahren werden für jeden \n<size:17>Messenger-Service durch die Organisation festgelegt</size>
|||

  MH-->MP: unterstützte \nAuthentifizierungs-\nverfahren
    Deactivate MH
  MP-->C: HTTP Forward
    Deactivate MP
  C-->U: Zeige \nAuthentifizierungsmaske
  U->U: Starte Authentifizierung
  U->C: Anmeldung
  C->MP: POST /_matrix/client/login
    Activate MP

    
    MP->MH: HTTP Forward
      Activate MH
    MH->MH: überprüfe Client-\nCredentials
    opt#LightGrey #MistyRose <size:16>Abbruch</size>
      MH-->MP:Fehlerhafte \nAnmeldedaten 
      MP-->C: HTTP Forward
      C-->U: Anmeldedaten \nsind nicht korrekt
    end
    
    note over MH, MH: <size:17>Die Überprüfung ist abhängig vom \n<size:17>gewählten Authentifizierungsverfahren</size>
    
    MH->MH: erstelle \nMatrix-ACCESS_TOKEN, \ndevice_id, \nMXID
    MH-->MP: Matrix-ACCESS_TOKEN, \ndevice_ID, MXID
      Deactivate MH
    MP-->C: HTTP Forward
      Deactivate MP
    C->C: Speichere \nMatrix-ACCESS_TOKEN
    
    |||
    C->MP: POST /_matrix/client\n/user/{userId}/\nopenid/request_token
      Activate MP
    MP->MH: HTTP Forward
      Activate MH
    MH->MH: Erstelle \nMatrix-OpenID-Token
    MH-->MP: Matrix-OpenID-Token
      Deactivate MH
    MP-->C: HTTP Forward
      Deactivate MP
    
    |||
    C->Auth: GET /tim-authenticate (Matrix-OpenID-Token)
      Activate Auth
    Auth->FP: GET /FederationList
      Activate FP
    FP-->Auth: Liste[]
      Deactivate FP
    Auth->Auth: Prüfung, ob \nmatrix_server_name \nin FöderationList \nenthalten ist

      |||
      alt#LightGrey #LightBlue <size:16>nicht valider Messenger-Service, da Matrix-Homeserver nicht in der Föderationsliste enthalten ist</size>
      |||  

        Auth-->C: HTTP 401 \nUnauthorized 
          Deactivate FP
        C->C: Abmelden Session \nMatrix-ACCESS_TOKEN \nlöschen
        C-->U: Anmeldung \nnicht erfolgreich
        
        |||
        else <size:16>valider Messenger-Service, da Matrix-Homeserver in der Föderationsliste enthalten ist</size>
          Auth-->C: HTTP 200
            Deactivate Auth
          C-->U: Anmeldung \nerfolgreich
            Deactivate C
          |||

      end  
      |||
end
|||

@enduml
