/' 
# TI-Messenger 1.1
# TI-Messenger-Dienst
# UC - 10059
# Sequence Diagram
# Name: Bereitstellung eines Messenger-Service für eine Organisation
'/

@startuml
skinparam sequenceMessageAlign direction
skinparam minClassWidth 200
skinparam BoxPadding 1
skinparam sequenceReferenceHeaderBackgroundColor palegreen
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontName Impact
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20
ActorFontName Aapex
}
    actor U as "Akteur in der Rolle\nOrg-Admin"
    box <size:18>Endgerät</size>\n #WhiteSmoke 
    participant C as "TI-Messenger-Client\n mit Org-Admin \nFunktionalität"
    participant A as "Authenticator \ndes IDP-Dienst"
    end box
    participant I as "IDP-Dienst" 
    box <size:18>VZD-FHIR-Directory</size> #WhiteSmoke
      participant FP as "FHIR-Proxy"
      participant Auth as "Auth-Service"
      participant VZD as "FHIR-Directory"
    end box

|||
note over U, I: <size:17>Die Organisation hat einen Messenger-Service bereitgestellt bekommen, \n<size:17>der Teil der Föderation ist</size>
|||

U->C: FHIR Ressourcen im \nVZD-FHIR-Directory \nhinzufügen (MXID)
  Activate C
C->C: Prüfung, ob gültiges \nowner-accesstoken \nvorliegt

|||
alt#LightGrey #AliceBlue <size:16>kein gültigess owner-accesstoken</size>
|||

  C->C: Erzeuge PKCE Code \nfür verifier und challenge
  |||
  C->Auth: GET /owner-authenticate
    Activate Auth
  Auth-->C: Redirct to IDP \nAuthorization Endpoint

  C->U: Liste verfügbarer IDP's
  U->C: ausgewählterr IDP
    
  C->I: GET /authorize
    Activate A
    Activate I
  I-->C: Authentication \nchallenge
  |||
  A->U: Aufforderung zur \nAuthentifizierung
  U->A: Eingabe tätigen
  |||
  A->A: Authentication
  A->I: Authentication \nchallenge response
    Deactivate A
  |||
  I-->C: Authorization Response with Authorization Code
    Deactivate I
      
  |||    
  C->Auth: GET /owner-authenticate with Authorization code
  Auth-->I: POST /tokenEndpoint\n(authorization code)
    Activate I
  I-->Auth: id_token
    Deactivate I
  Auth->Auth: prüfe id_token
  Auth->Auth: erzeuge \nowner-accesstoken
  Auth-->C: owner-accesstoken
  ||| 
    
    Deactivate Auth
end
      
|||

group <size:16>FHIR-Directory Eintrag erstellen</size>
  |||
  C->FP: GET /owner/TIHealthCareService?providedBy.id=telematikID \n(owner-accesstoken)
    Activate FP
  FP->FP: prüfe \nowner-accesstoken
  FP->VZD: HTTP Forward
    Activate VZD
  VZD->VZD: suche Eintrag
  VZD-->FP: result body json
    Deactivate VZD
  FP-->C: HTTP Forward
    Deactivate FP
  |||
  C->FP: PUT /owner/TIHealthCareService?telecom.value=MXID \n(owner-accesstoken)
  |||
    Activate FP
  FP->FP: prüfe \nowner-accesstoken
  FP->VZD: HTTP Forward
    Activate VZD
  VZD->VZD: Eintrag hinzufügen
  VZD-->FP: result body json
    Deactivate VZD
  FP-->C: HTTP Forward
    Deactivate FP
  C-->U: Status    
  |||
end
|||

  Deactivate C
@enduml
