/' 
# TI-Messenger 1.1
# TI-Messenger-Dienst
# UC - 10064
# Sequence Diagram
# Name: Föderationszugehörigkeit eines Messenger-Service prüfen
'/

@startuml
skinparam sequenceMessageAlign direction
skinparam minClassWidth 200
skinparam BoxPadding 1
skinparam sequenceReferenceHeaderBackgroundColor palegreen
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontName Impact
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20
ActorFontName Aapex
}
    box <size:18>Messenger-Service</size> #WhiteSmoke
    participant MP as "Messenger-Proxy"
    participant MH as "Matrix-Homeserver"
    end box
    participant RD as "Registrierungs-Dienst"
    box <size:18>VZD-FHIR-Directory</size> #WhiteSmoke
      participant FP as "FHIR-Proxy"
      participant AS as "OAuth-Service"
    end box

|||
note over MP, MH: \n<size:17>Überprüfe, ob eingehender Matrix-Event an den \n<size:17>Matrix-Homeserver weitergeleitet werden darf</size>\n
|||

    Activate MP
  MP->MP: prüfe ob Matrix-Domain \nim PASSporT \nin der Föderationsliste \nvorhanden ist

|||
opt#LightGrey #AliceBlue <size:16>Matrix-Domain ist nicht in der Föderationsliste enthalten</size>
|||  

  MP->RD: GET /FederationList
    Activate RD

    RD->AS: GET /token (client_id, client_secret) \n(OAuth Client credentials flow)
      Activate AS
    AS->AS: prüfe client_id und \nclient_secret
    AS-->RD: Status, admin-accesstoken (30 Minuten)
      Deactivate AS  

    |||
    RD->FP: GET /tim-provider-services/FederationList \n(admin-accesstoken)
      Activate FP
    FP->FP: prüfe \nadmin-accesstoken
    FP-->RD: Föderationsliste[]

      Deactivate FP
    RD-->MP: Föderationsliste[]
      Deactivate RD
    |||
    MP->MP: prüfe ob Matrix-Domain \nim PASSporT \nin der Föderationsliste \nvorhanden ist
    |||
end
|||

alt#LightGrey #AliceBlue <size:16>Matrix-Domain ist nicht in der Föderationsliste enthalten</size>
|||  

  note over MP, MH: <size:17>Abbruch, Verbindung wird abgelehnt</size>
  ||| 
  
  else <size:16>Matrix-Domain ist in der Föderationsliste enthalten</size>
    ||| 
    MP->MH: HTTP Forward
      Activate MH
    MH-->MP: Status
      Deactivate MH
      Deactivate MP
    ||| 

end
@enduml
