/' 
# TI-Messenger 1.1
# TI-Messenger-Dienst
# UC - 10103
# Sequence Diagram
# Name: Authentisieren einer Organisation am TI-Messenger-Dienst
'/

@startuml
skinparam sequenceMessageAlign direction
skinparam WrapWidth 300
skinparam minClassWidth 150
skinparam BoxPadding 1
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontName Impact
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20
ActorFontName Aapex
}

  actor oa as "Akteur in der Rolle\nOrg-Admin"
    box <size:19>Endgerät</size> #WhiteSmoke
    participant wb as "Frontend des \nRegistrierungs-Dienstes"
    participant au as "Authenticator"
    end box
  participant ko as "Konnektor"
  participant kt as "eHealth KT"
  participant rd as "Registrierungs-Dienst"
  participant ip as "zentraler \nIDP-Dienst"

  |||
  oa -> wb: Organisation verifizieren
    activate wb
  wb -> rd:POST /register 
    activate rd
  rd --> wb: Redirect to IDP Authorization Endpoint
    deactivate rd
  |||
  wb -> ip: GET /authorize
    activate au
    activate ip
  ip -> au: Authentication challenge
  au -> ko: SignDocument
    activate ko
  ko -> kt: SICCT command
    activate kt
  kt --> ko
    deactivate kt
  ko --> au: Response \nsignedDocument
    deactivate ko

opt #MistyRose <size:15>Abbruch</size>
  au -> oa: SMC-B nicht freigeschaltet 
end

  au -->ip: Authentication response
    deactivate au
  ip --> wb: Authorization code
    deactivate ip
  |||
  wb -> rd: POST /register (Authorization code)
    activate rd
  rd -> ip: POST /tokenEndpoint\n{authorization code}
    activate ip
  ip --> rd: Response\n{id_token, access_token}
    deactivate ip
  rd -> rd: Organisation \nauthentifizieren
  rd --> wb: status, id_token, access_token
    deactivate rd
  wb --> oa: Verifizierung erfolgreich
    deactivate wb
  |||  
@enduml
