/' 
# TI-Messenger 1.1
# TI-Messenger-Dienst
# UC - 10057
# Sequence Diagram
# Name: Anmeldung eines Akteurs am Messenger-Service
'/

@startuml
skinparam sequenceMessageAlign direction
skinparam minClassWidth 200
skinparam BoxPadding 1
skinparam sequenceReferenceHeaderBackgroundColor palegreen
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontName Impact
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20
ActorFontName Aapex
}
    actor U as "Akteur in der Rolle\nUser / User-HBA"
    participant C as "TI-Messenger-Client"
    box <size:18>Messenger-Service</size> #WhiteSmoke
      participant MP as "Messenger Proxy"
      participant MH as "Matrix-Homeserver"
    end box
    box <size:18>VZD-FHIR-Directory</size> #WhiteSmoke
      participant FP as "FHIR-Proxy"
      participant VZD as "FHIR-Directory"
    end box

  U->C: Eingabe Messenger-Service \n(Manuell oder \ndurch Auswahl)
    Activate C
  C->MP: POST /login
    Activate MP
  MP->MP: TLS-Terminierung
  MP->MH: HTTP Forward
   Activate MH

|||
note over U, MH: <size:17>Die Authentifizierungsverfahren werden für jeden \n<size:17>Messenger-Service durch die Organisation festgelegt</size>
|||

  MH-->MP: Authentifizierungsverfahren
    Deactivate MH
  MP-->C: HTTP Forward
    Deactivate MP
  C-->U: Zeige \nAuthentifizierungsmaske
  U->U: Starte Authentifizierung
  U->C: Anmeldung
  C->MP: POST /login
    Activate MP
  MP->MP: überprüfe User-Agent, \nClient-Secret

|||
alt#LightGrey #AliceBlue <size:16>TI-Messenger Client wird vom Anbieter nicht unterstützt</size>
|||  

  MP-->C: HTTP 401 Unauthroized
  C-->U: Anmeldung \nnicht erfolgreich
  
    else <size:16>TI-Messenger Client wird vom Anbieter unterstützt</size>
  
    MP->MH: HTTP Forward
      Activate MH
    MH->MH: überprüfe Zugangsdaten
    
    note over MH, MH: <size:17>Die Überprüfung ist abhängig vom \n<size:17>gewählten Authentifizierungsverfahren</size>
    
    MH->MH: erstelle \nMatrix-ACCESS_TOKEN, \ndevice_id, \nMXID
    MH-->MP: Matrix-ACCESS_TOKEN, \ndevice_ID, MXID
      Deactivate MH
    MP-->C: HTTP Forward
      Deactivate MP
    C->C: Speichere \nMatrix-ACCESS_TOKEN
    C->MP: Request \nMatrix-OpenID-Token
      Activate MP
    MP->MH: HTTP Forward
      Activate MH
    MH->MH: Erstelle \nMatrix-OpenID-Token
    MH-->MP: Matrix-OpenID-Token
      Deactivate MH
    MP-->C: HTTP Forward
      Deactivate MP
    
    C->FP: GET /tim-authenticate (Matrix-OpenID-Token)
      Activate FP
    FP->VZD: HTTP Forward
      Activate VZD
    VZD->VZD: Prüfung \nMatrix-OpenID-Token

      |||
      alt#LightGrey #LightBlue <size:16>nicht valider Messenger-Srvice</size>
      |||  

        VZD-->FP: HTTP 401 \nUnauthorized 
        FP-->C: HTTP Forward
          Deactivate FP
        C->C: Abmelden Session \nMatrix-ACCESS_TOKEN \nlöschen
        C-->U: Anmeldung \nnicht erfolgreich
        
        else <size:16>valider Messenger-Srvice</size>
          VZD-->FP: HTTP 200
            Activate FP
          FP-->C: HTTP Forward
            Deactivate FP
          C-->U: Anmeldung \nerfolgreich

      end  
end

@enduml
