/' 
# TI-Messenger 1.1
# TI-Messenger-Dienst
# UC - 10061
# Sequence Diagram
# Name: Einladung von Akteuren außerhalb einer Organisation
'/

@startuml
skinparam sequenceMessageAlign direction
skinparam minClassWidth 200
skinparam BoxPadding 15
skinparam sequenceReferenceHeaderBackgroundColor palegreen
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontName Impact
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20
ActorFontName Aapex
}
    actor U1 as "\nAkteur - A in der Rolle\nUser / User-HBA\n"
    participant C1 as "TI-Messenger-\nClient" #AliceBlue
    box <size:18>Messenger-Service A</size> #WhiteSmoke
      participant MP1 as "Messenger-\nProxy"
      participant MH1 as "Matrix-\nHomeserver"
    end box
    box <size:18>Messenger-Service B</size> #WhiteSmoke
    participant MP2 as "Messenger-\nProxy"
    participant MH2 as "Matrix-\nHomeserver"
    participant PG2 as "Push-\nGateway"
    end box
    participant C2 as "TI-Messenger-\nClient" #TECHNOLOGY
    actor U2 as "\nAkteur - B in der Rolle\nUser / User-HBA\n"
    
|||
note over U1, MH1: \n<size:17>Der Akteur A ist erfolgreich beim Messenger Service A angemeldet</size>\n   
note over U2, MP2: \n<size:17>Der Akteur B ist erfolgreich beim Messenger Service B angemeldet</size>\n    
|||
    
    alt#LightGrey #AliceBlue  <size:16>Suche über VZD-FHIR-Directory</size>
      |||
      ref over U1, MH1 : <size:16>Anhang B - Einträge im VZD-FHIR-Directory suchen</size>\n
      |||
    
      else <size:16>Direktaustausch (QR-Code Scan)</size>
         |||
         note over U1, U2: \n<size:16>Akteur A und Akteur B treffen sich in Person\n
         |||
         autonumber
         U1-[#0000FF]>C1: QR-Code teilen
          activate C1 #AliceBlue
         U2-[#red]>C2: QR-Code scannen
          activate C2 #TECHNOLOGY
         C2-[#red]>C1: GET /scan
         C1--[#0000FF]>C2: MXID (Akteur A)
         U2-[#red]>C2: QR-Code teilen
         U1-[#0000FF]>C1: QR-Code scannen
         C1-[#0000FF]>C2: GET /scan
         C2--[#red]>C1: MXID (Akteur B)
         autonumber stop
         |||
         
         opt#LightGrey #AliceBlue <size:16>Eintrag in Freigabeliste erzeugen</size>
         |||
           C2->MP2: POST /tim-contact-mgmt/createContactSetting (MXID, start, end, Matrix-OpenID-Token)
           activate MP2
           |||
           MP2->MH2: GET /openid/userinfo/\n?Matrix-OpenID-Token
           activate MH2
           MH2->MH2: prüfe \nMatrix-OpenID-Token
           MH2-->MP2: status
           deactivate MH2
           |||
           MP2->MP2: MXID von Akteur A \nin Freigabeliste \nfür Akteur B \naufnehmen
           |||
           MP2-->C2: status
           deactivate MP2
           deactivate C2
          |||
        end
        |||
    end
    
    |||
    C1->MP1: POST /_matrix/client/r0/\nrooms/{roomId}/invite 
      activate MP1
    
    |||
      ref over MP1, MP1: <size:17>**AF_10064** - \tFöderationszugehörigkeit eines \n<size:17>        \tMessenger-Service prüfen</size>\n 
      note right: <size:16>Stufe 1 - Prüfung gemäß </size>\n<size:16>Client-Server Kommunikation</size>
    |||
      break#LightGrey #MistyRose <size:16>Abbruch</size>
      |||
      MP1-->C1: HTTP 401 \nUnauthorized
      |||
      C1-->C1: Abmeldung der Session
      |||
      C1-->U1: Anmeldung nicht \nerfolgreich
      |||
      end
      |||

    MP1->MH1: HTTP(S) Forward
      activate MH1
    MH1->MH1: Invite verarbeiten
    MH1->MP1: POST /_matrix/federation/v1\n/invite/{roomId}/{eventId} 
      deactivate MH1
    |||
    ref over MP1, MP1: <size:17>**AF_10064** - \tFöderationszugehörigkeit eines \n<size:17>        \tMessenger-Service prüfen</size>\n 
    note left: <size:16>Stufe 1 - Prüfung gemäß </size>\n<size:16>Server-Server Kommunikation</size>
    |||
    MP1->MP2: HTTP(S) Forward
    note right: <size:16>Stufe 1 - Prüfung gemäß </size>\n<size:16>Server-Server Kommunikation</size>
    |||
      activate MP2
      ref over MP2, MP2: <size:17>**AF_10064** - \tFöderationszugehörigkeit eines \n<size:17>        \tMessenger-Service prüfen</size>\n 
    |||

      break#LightGrey #MistyRose <size:16>Abbruch</size>
      |||
      MP2-->MP1: HTTP 401 \nUnauthorized
      |||
      MP1-->C1: HTTP(S) forward
      |||
      C1-->C1: Abmeldung der Session
      |||
      C1-->U1: Anmeldung nicht \nerfolgreich
      |||
      end

    |||
      ref over MP2, MH2 : <size:16>Anhang B - Stufen der Berechtigungsprüfung</size>\n <size:16>Stufe 2 und 3</size>\n
    |||
    MP2->MH2: HTTP(S) Foward
      activate MH2
      MH2->MH2: Invite verarbeiten
      |||
      opt#LightGrey #AliceBlue <size:16>Pushbenachrichtigung</size>
      |||
        MH2->PG2: POST /_matrix/push/notify
          activate PG2
        PG2->C2: Notification
        PG2-->MH2: Status
          deactivate PG2
      |||
      end
      |||
        MH2->MP2: Invite Request
        MP2->C2: HTTP(S) Forward
          activate C2 #TECHNOLOGY
        C2->U2: Einladung anzeigen
        U2-->C2: Einladung bestätigen
        C2->MP2: commit
        MP2->MP2: TLS Terminierung
        MP2-->MH2: HTTP(S) Forward
        MH2-->MH2: Invite auslösen
        MH2-->MP2: Status
          deactivate MH2

        MP2-->C2: Status
        C2-->U2: Nutzer ist dem \nRaum beigetreten
          deactivate C2
        MP2-->MP1: Status 
          deactivate MP2
        MP1-->C1: Nutzer in den \nRaum hinzugefügt  
                  deactivate MP1
          deactivate C1
  |||
|||
@enduml
