/' 
# TI-Messenger 1.1
# TI-Messenger-Dienst
# UC - 10060
# Sequence Diagram
# Name: Bereitstellung eines Messenger-Service für eine Organisation
'/

@startuml
skinparam sequenceMessageAlign direction
skinparam WrapWidth 300
skinparam minClassWidth 150
skinparam BoxPadding 1
skinparam sequenceReferenceHeaderBackgroundColor palegreen
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontName Impact
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20
ActorFontName Aapex
}
    actor U as "Akteur in der Rolle\nOrg-Admin"
    box <size:18>Endgerät</size> #WhiteSmoke
      participant C as "Frontend des\nRegistrierungs-Dienstes"
    end box
    participant R as "Registrierungs-Dienst"
    box <size:18>VZD-FHIR-Directory</size> #WhiteSmoke
    participant Auth as "Auth-Service"
    participant FP as "FHIR-Proxy"
    participant VZD as "FHIR-Directory"
    end box

|||
ref over U, R: <size:17>**AF: 10103** - Authentisieren einer Organisation am TI-Messenger-Dienst</size>\n 
|||

loop <size:16>1..n</size>
  |||
  U->C: Messenger Service erstellen
  Activate C
  C->R: POST /create (id_token, \naccess_token, \nMatrix-Domain)
    Activate R
    
    |||
    group <size:16>Messaging-Service erstellen</size>
    |||
      R->R: Starte neuen Messenger-Service \nfür die Organisation (Matrix-Domain)
        create "Messenger-Service"
          R-->"Messenger-Service" : Messenger-Service erstellen 
        Activate "Messenger-Service"
      |||
      "Messenger-Service"->"Messenger-Service": Account \nerstellen
      "Messenger-Service"-->R: Status, Account Daten
      |||
        Deactivate "Messenger-Service"
    |||
    end
    
    |||
    
    group <size:16>FHIR-Directory Eintrag erstellen</size>
    |||
      R->Auth: GET /token (client_id, client_secret) \n(OAuth Client credentials flow)
        Activate Auth
      Auth->Auth: prüfe client_id und \nclient_secret
      Auth-->R: admin-access-token
        Deactivate Auth
      |||
      R->FP: FHIR Request \n(admin-access-token, Matrix-Domain)\nEndpoint (tim-domain)
        Activate FP
      FP->VZD: HTTP Forward
        Activate VZD
      VZD-->VZD: FHIR-Ressource \nerzeugen \n(TIOrganisation)
      VZD-->VZD: Föderationsliste\naktualisieren
      VZD-->FP: Status
        Deactivate VZD
      FP-->R: HTTP Forward
        Deactivate FP

    |||
    end

  |||
  R->C: Status, Account Daten
    Deactivate R
  C->U: Status, Account Daten
    Deactivate C
  |||
end
|||
@enduml
