/' 
# TI-Messenger 1.1
# TI-Messenger-Dienst
# UC - 10104
# Sequence Diagram
# Name: Einladung von Akteuren innerhalb eines Messenger-Service
'/

@startuml
skinparam sequenceMessageAlign direction
skinparam minClassWidth 200
skinparam BoxPadding 1
skinparam sequenceReferenceHeaderBackgroundColor palegreen
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontName Impact
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20
ActorFontName Aapex
}
    actor U1 as "Akteur - A in der Rolle\nUser / User-HBA"
    participant C1 as "TI-Messenger-\nClient A" #AliceBlue
    box <size:18>Messenger-Service</size> #WhiteSmoke
      participant MP as "Messenger-\nProxy"
      participant MH as "Matrix-Homeserver \n(inklusive Nutzerverzeichnis)"
      participant PG as "Push-Gateway"
    end box
    participant C2 as "TI-Messenger-\nClient B"#TECHNOLOGY
    actor U2 as "Akteur - B in der Rolle\nUser / User-HBA"
    
|||
note over U1, U2: \n<size:17>Die Akteure sind auf dem selben Messenger-Service angemeldet und im Besitz eines zugelassenen TI-Messenger-Clients.\n<size:17>Ein Chatraum wurde durch den Einladenen eingerichtet.</size>\n
|||

    opt#LightGrey <size:16>Akteur suchen</size>
    |||
    U1->C1: Suche Akteur B
      activate C1 #AliceBlue
    C1->MP: POST /_matrix/client/\nuser_directory/search
      activate MP
    MP->MP: TLS-Terminierung
    MP->MH: HTTP(S) Forward
      activate MH
    MH-->MH: Nutzerverzeichnis \ndurchsuchen
    MH-->MP: MXID
      deactivate MH
    MP-->C1: HTTP(S) Forward
    |||
    end
    
    |||
    U1->C1: Akteur B einladen
    C1->MP: POST /_matrix/client/r0/rooms/\n{roomId}/invite (roomId)
    MP->MP: Organisationszugehörigkeit \nprüfen
    |||
    
    alt#LightGrey #AliceBlue <size:16>kein gemeinsamer Messenger-Service</size>
      |||
      MP-->C1: Akteure nicht auf \ndem gleichen \nMatrix-Homeserver
      C1-->U1: Akteur B kann \nnicht eingeladen \nwerden
      |||
    
      else <size:16>gemeinsamer Messenger-Service</size>
    
      MP->MH: HTTP(S) Foward
        activate MH
      MH->MH: Invite verarbeiten
      |||
      group par 
        opt <size:16>Pushbenachrichtigung</size>
          |||
          MH->PG: POST /_matrix/push/notify
            activate PG
          PG->C2: Notification
          PG-->MH: Status
            deactivate PG
        |||
        end
        |||
        group /sync
          |||
          MH->MP: Invite Request
          MP->C2: HTTP(S) Forward
            activate C2 #TECHNOLOGY
          C2->U2: Einladung anzeigen
          U2-->C2: Einladung bestätigen
          C2->MP: commit
          |||
          MP->MP: TLS Terminierung
          MP-->MH: HTTP(S) Forward
          MH-->MH: Invite auslösen
          MH-->MP: Status
            deactivate MH
          MP-->C1: Status
          C1-->U1: Nutzer in den \nRaum hinzugefügt
            deactivate C1
          MP-->C2: Status
            deactivate MP
          C2-->U2: Nutzer ist dem \nRaum beigetreten
            deactivate C2

        |||
        end
      |||
      end
    |||
    end
|||
@enduml
