/' 
# TI-Messenger 1.1.1
# TI-Messenger-Dienst
# UC - 
# Sequence Diagram
# Name: Provider authentifizieren und Föderationsliste abrufen
'/

@startuml
skinparam sequenceMessageAlign direction
skinparam minClassWidth 200
skinparam BoxPadding 1
skinparam sequenceReferenceHeaderBackgroundColor palegreen
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontName Impact
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20
ActorFontName Aapex
}

participant RD as "Registrierungs-Dienst"
box <size:18>VZD-FHIR-Directory</size> #WhiteSmoke
  participant FP as "FHIR-Proxy"
  participant AS as "OAuth-Service"
end box

alt#LightGrey <size:16>kein gültiges provider-accesstoken vorhanden</size>
  activate RD
  alt#LightGrey <size:16>Benötigt IDP-TI-Provider-Accesstoken</size>
      RD -> AS: GET /token(client-ID, client_secret)\nfür Realm "ti-provider"\n{<10s := HealthState_VZD=gesund}
      activate AS
      AS -> AS: Credentials prüfen \n(client-ID, client_secret)
      AS -> AS: IDP-TI-Provider-Accesstoken\nerstellen
      note left: <size:16>Payload beinhaltet ClientID + TelematikID</size>
      AS --> RD: IDP-TI-Provider-Accesstoken
      deactivate AS
  end
  RD -> FP: GET /ti-provider-authenticate\n(IDP-TI-Provider-Accesstoken)\n{<10s := HealthState_VZD=gesund}
  activate FP
  FP -> FP: Token prüfen und ClientID auslesen\n(IDP-TI-Provider-Accesstoken)
  FP -> FP: provider-accesstoken erzeugen
  FP --> RD: provider-accesstoken
  deactivate FP
end

|||
RD->FP: GET /tim-provider-services/FederationList/federationList.jws\n(provider-accesstoken, FLVersion_RD)\n{<10s := HealthState_VZD=gesund}
  Activate FP
FP->FP: Token prüfen(provider-accesstoken)

break#LightGrey #LightPink <size:16>Abruf der Föderationsliste nicht möglich</size>
  FP-->RD: ResponseType=Bad Request ODER \nResponseType=Unauthorized ODER \nResponseType=Forbidden ODER \nResponseType=Not Found
end 

|||
FP->FP: Auf neuere Version der \nFöderationsliste prüfen\n(FLVersion_RD)
|||

alt#LightGrey <size:16>keine neuere Version der Föderationsliste vorhanden</size>
  FP-->RD: ResponseType=No Content
  RD->RD: Alter_Föderationsliste zurücksetzen(Alter_Föderationsliste=0s)
  |||
else <size:16>neuere Version der Föderationsliste vorhanden ODER FLVersion_RD=NULL</size>
  FP-->RD: Föderationsliste, x5c-Zertifikatsliste
      Deactivate FP
  RD->RD++: Föderationsliste aktualisieren(Föderationsliste)
  return Föderationsliste
  RD->RD: Alter_Föderationsliste zurücksetzen(Alter_Föderationsliste=0s)
  |||
end
|||
@enduml
