/' 
# TI-Messenger 1.1
# TI-Messenger-Dienst
# UC - 10064
# Sequence Diagram
# Name: Föderationszugehörigkeit eines Messenger-Service prüfen
'/

@startuml
skinparam sequenceMessageAlign direction
skinparam minClassWidth 200
skinparam BoxPadding 1
skinparam sequenceReferenceHeaderBackgroundColor palegreen
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontName Impact
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20
ActorFontName Aapex
}
    box <size:18>Messenger-Service\n #WhiteSmoke
    participant MP as "Messenger-Proxy"
    participant MH as "Matrix-Homeserver"
    end box
    participant RD as "Registrierungs-Dienst"
    box <size:18>VZD-FHIR-Directory</size> #WhiteSmoke
      participant FP as "FHIR-Proxy"
      participant AS as "OAuth-Service"
    end box

  |||
  MP->RD: GET /I_internVerification (Version) 
  note right: <size:16>Schnittstelle wird nicht \n<size:16>durch die gematik spezifiziert</size>
  |||
    Activate MP
    Activate RD


  alt#LightGrey #AliceBlue <size:16>kein gültiges provider-accesstoken</size>
    |||
    RD->AS: GET /authenticate (client_id, client_secret) \n(OAuth Client credentials flow)
      Activate AS
    AS->AS: prüfe client_id und \nclient_secret
    AS-->RD: status, provider-accesstoken 
      Deactivate AS  
    |||
  end

  |||
  RD->FP: GET /tim-provider-services/getFederationList \n(provider-accesstoken, Version)
    Activate FP
  FP->FP: prüfe \nprovider-accesstoken
  |||
  FP->FP: prüfe übergebene \nVersion

|||

  FP-->RD: status (aktuell oder nicht aktuell)
  |||
  
alt#LightGrey #AliceBlue <size:16>Version vom Registrierungs-Dienst ist aktuell</size>
    |||
    RD->RD: Prüfung der Version \nRegistrierungs-Dienst \nund Messenger-Proxy
      
      |||
      alt#LightGrey #LightBlue <size:16>Version vom Messenger-Proxy ist aktuell</size>
      ||| 
          RD-->MP: status
          |||
          
          else <size:16>Version ist nicht aktuell</size>
            RD-->MP: Föderationsliste[]
            |||
            MP->MP: Signatur der Föderationsliste prüfen
            |||
      end
    |||
    
    else <size:16>Version vom Registrierungs-Dienst ist nicht aktuell</size>
       FP-->RD: Föderationsliste[]
        Deactivate FP
      RD-->MP: Föderationsliste[]
        Deactivate RD
      |||
      MP->MP: Signatur der Föderationsliste prüfen
      'Needed for correct deactivation in case last message is message to itself
      MP-[hidden]->MP
        deactivate MP
    |||
end
@enduml
