@startuml ClassDiagram.CaseReference
skinparam monochrome true
class Encounter {
  {field} identifier (0.., MS)
  {field} status (1..1, MS)
  {field} statusHistory (0.., MS)
  {field} class (..1, MS)
  {field} classHistory (0.., MS)
  {field} serviceType (0.., MS)
  {field} priority (0.., MS)
  {field} subject (1..1, MS)
  {field} period (0.., MS)
  {field} length (0.., MS)
  {field} reasonCode (0.., MS)
  {field} diagnosis (0.., MS)
}
class Patient {
  {field} identifier (1.., MS)
  {field} name (1..1, MS)
  {field} gender (..1, MS)
  {field} birthDate (..1, MS)
  {field} address (0.., MS)
  {field} photo (1.., MS)
  {field} contact (0.., MS)
  {field} communication (0.., MS)
  {field} generalPractitioner (0.., MS)
}
class Condition {
  {field} identifier (0.., MS)
  {field} clinicalStatus (..1, MS)
  {field} verificationStatus (0..1, MS)
  {field} category (0.., MS)
  {field} severity (0..1, MS)
  {field} code (0..1, MS)
  {field} bodySite (0.., MS)
  {field} subject (1..1, MS)
  {field} encounter (0..1, MS)
  {field} recordedDate (0..1, MS)
  {field} stage (0.., MS)
  {field} evidence (0.., MS)
  {field} note (0.., MS)
}
class Procedure {
  {field} identifier (0.., MS)
  {field} status (1..1, MS)
  {field} statusReason (0..1, MS)
  {field} category (0..1, MS)
  {field} code (0..1, MS)
  {field} subject (1..1, MS)
  {field} encounter (0..1, MS)
  {field} reasonCode (0.., MS)
  {field} outcome (0..1, MS)
  {field} complication (0.., MS)
  {field} note (0.., MS)
}

Encounter o-- Patient: subject
Encounter o-- Condition: diagnosis.condition
Encounter o-- Procedure: diagnosis.condition
Condition o-- Patient: subject
Procedure o-- Patient: subject
@enduml
