ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images

image:meta/gematik_logo.svg[width=70%]

=== AF_10057 - Anmeldung eines Akteurs am Messenger-Service
Mit diesem Anwendungsfall meldet sich ein Akteur an einem in der TI-Föderation zuständigen *Messenger-Service* an und registriert seinen *TI-Messenger-Client* als Endgerät. Der Akteur muss die Matrix-Domain des gewünschten *Messenger-Service* direkt im *TI-Messenger-Client* eingeben können. Die Eingabe kann dabei automatisiert oder durch andere Hilfsmittel wie beispielweise durch ein QR-Code-Scan unterstützt werden. Die Authentifizierung erfolgt hierbei nach den Vorgaben der jeweiligen Organisation. Nach der erfolgreichen Anmeldung eines Akteurs am *Messenger-Service* können die von ihm angebotenen Dienste verwendet werden. 

.Anwendungsfallbeschreibung
[%collapsible%open]
====
[caption=]
Anmeldung eines Akteurs am Messenger-Service
[%header, cols="1,1"]
|===
| |Beschreibung
|*Akteur* |Leistungserbringer, Mitarbeiter einer Organisation im Gesundheitswesen in der "Rolle User / User-HBA"
|*Auslöser* |Ein Akteur möchte sich mit seinem TI-Messenger-Client bei einem Messenger-Service anmelden.
|*Komponenten* a|
              * TI-Messenger-Client,
              * Messenger-Proxy,
              * Messenger-Homeserver, 
              * FHIR-Proxy,
              * FHIR-Directory.
|*Vorbedingungen* a| 
                  * Der Akteur verfügt über einen vom Anbieter unterstützen TI-Messenger-Client.
                  * Der Akteur kennt die URL des Messenger-Services oder die URL ist bereits in seinem TI-Messenger-Client konfiguriert.
                  * Der Akteur kann sich durch ein beim Matrix-Homeserver unterstütztes Authentisierungsverfahren identifizieren. Wird durch die Organisation ein eigenes Authentifizierungsverfahren verwendet MUSS eine Anbindung an den Matrix-Homeserver erfolgt sein.
                  * Der verwendete Matrix-Homeserver ist in die Föderation integriert (valider Messenger-Service).
|*Eingangsdaten*|URL des Matrix-Homeservers
|*Ergebnis* | Es wurde ein TI-Messenger Account für einen Akteur in der Rolle "User / User-HBA" erzeugt.
|*Ausgangsdaten* |Matrix-ACCESS_TOKEN, MXID, device_id, Matrix-OpenID-Token, Status
|===
====
.Sequenzdiagramm
[%collapsible%open]
====
++++
<p align="center">
  <img width="80%" src=../../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10057_Seq.svg>
</p>
++++
====
