ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images

image:gematik_logo.svg[width=70%]

=== AF_10062 - Austausch von Events zwischen Akteuren außerhalb einer Organisation
In diesem Anwendungsfall können Akteure welche sich in einem gemeinsamen Raum befinden Nachrichten austauschen und andere durch die Matrix-Spezifikation festgelegte Aktionen ausführen. Dieser Anwendungsfall setzt ein erfolgreiches `Invite`-Event eines oder mehrerer beteiligter Akteure voraus. Die Prüfung auf Domainzugehörigkeit findet jedoch bei jedem `Event` der Server-Server Kommunikation statt. In diesem Anwendungsfall sind die beteiligten Akteure in einem gemeinsamen Chatraum und auf unterschiedlichen *Messenger-Services* verteilt.

.AF_10062 Anwendungsfallbeschreibung
[%collapsible%open]
====
[caption=]
Austausch von Events zwischen Akteuren außerhalb einer Organisation
[%header, cols="1,1"]
|===
| |Beschreibung
|*Akteur* |Leistungserbringer, Mitarbeiter einer Organisation im Gesundheitswesen in der Rolle "User / User-HBA"
|*Auslöser* |Alle Matrix-Events die zwischen Messenger-Services unterschiedlicher Organisationen ausgeführt werden.
|*Komponenten* a|
              * TI-Messenger-Client A + B,
              * Messenger-Proxy A + B,
              * Messenger-Homeserver A + B, 
              * Push-Gateway B
|*Vorbedingungen* a| 
                  * Beide Akteure sind Teilnehmer eines gemeinsamen Raumes
                  * Die Messenger Proxies verfügen über eine aktuelle Föderationsliste
|*Eingangsdaten* | Matrix-Event
|*Ergebnis* a|Matrix-Event wurde erfolgreich verarbeitet 
|*Ausgangsdaten* data |Abhängig vom Matrix-Event, Status
|===
====
.Sequenzdiagramm
[%collapsible%open]
====
++++
<p align="center">
  <img width="100%" src=../../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10062_Seq.svg>
</p>
++++
====
