ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images

image:meta/gematik_logo.svg[width=70%]

===  A 8.2 - Aktualisierung der Föderationsliste
Die folgende Sequenz beschreibt, wie der *Messenger-Proxy* seine lokal vorgehaltene Föderationsliste aktualisiert. Für die Aktualisierung der Föderationsliste MUSS der *Messenger-Proxy* diese beim *Registrierungs-Dienst* seines *TI-Messenger-Fachdienstes* anfragen. Die Häufigkeit der Anfrage einer neuen Liste wird durch den Anbieter festgelegt, Ziel sollte eine möglichst aktuelle Föderationsliste sein. Hierbei übergibt der *Messenger-Proxy* die durch ihn gespeicherte Version der Föderationsliste im Aufruf an den *Registrierungs-Dienst*. Bei Übereinstimmung der Version wird für den *Messenger-Proxy* keine neue Föderationsliste durch den *Registrierungs-Dienst* bereitgestellt. Ist die Version größer als die vom *Messenger-Proxy* übergebene, dann wird durch den *Registrierungs-Dienst* eine aktualisierte Föderationsliste zur Verfügung gestellt. Bei jeder Anfrage eines *Messenger-Proxys* beim *Registrierungs-Dienst* nach einer aktuellen Föderationsliste muss der *Registrierungs-Dienst* die Aktualität der durch ihn ausgelieferten Liste sicherstellen, indem er die von ihm gespeicherte Version der Föderationsliste im Bedarfsfall mit einer aktuelleren Version, die vom *FHIR-Proxy* bezogen wurde, überschreibt. Ein Download der Föderationsliste ist nur notwendig, wenn eine neuere Version auf dem *FHIR-Proxy* existiert. Die Struktur der Föderationsliste ist in https://github.com/gematik/api-vzd/blob/develop/src/schema/FederationList.json[JSON-Schemadefinition] beschrieben. Nach dem Abruf der Föderationsliste vom *Registrierungs-Dienst*, durch den *Messenger-Proxy*, muss dieser die Signatur der Föderationsliste prüfen.

.Anwendungsfallbeschreibung
[%collapsible%open]
====
[caption=]
Aktualisierung der Föderationsliste
[%header, cols="1,2"]
|===
| |Beschreibung
|*Akteur* |System
|*Auslöser* a|
            * Scheduler
            * Schnittstellenaufruf
|*Komponenten* a|
              * Messenger-Proxy, 
              * Registrierungs-Dienst,
              * FHIR-Proxy,
              * Auth-Service 
|*Vorbedingungen* a| keine
|*Eingangsdaten* | Versionsnummer
|*Ergebnis* | Der Messenger-Proxy erhält die Information eine aktuelle Liste zu besitzen oder eine neue Föderationsliste, sofern eine aktuellere Version vorliegt.
|*Ausgangsdaten* |status, Föderationsliste, x5c-Zertifikatsliste
|===
====

.Sequenzdiagramm "Föderationsliste aktualisieren"
[%collapsible%open]
====
++++
<p align="center">
  <img width="100%" src=../../images/plantuml/TI-Messenger-Dienst/Ressourcen/UC_Update_Federationlist_Seq.svg>
</p>
++++
====

[caption=]
Variablen, die vom Registrierungsdienst unterstützt werden.
[%header, cols="1,1,2,1"]
|===
|Name|Type|Beschreibung|Wertebereich
|`HealthState_VZD`|state|Hält den Gesundheitsstatus von Komponenten des VZD-FHIR-Directory in Abhängigkeit vom erhaltenen Antwortverhalten|[gesund, ungesund]
|`HealthStateCheck_VZD`|Counter|Hält die Anzahlt der Versuche den Gesundheitsstatus des VZD-FHIR-Directory zu ermitteln|0\<= `HealthStateCheck_VZD`\<=3
|`Alter_Föderationsliste`|Time in s |Hält das aktuelle Alter der Föderationsliste in Sekunden seit der letzten erfolgreichen Aktualisierung.
|min: 0s
|`TTL_Föderationsliste`|Time in h|Beschreibt das maximal erlaubte Alter der Föderationsliste.|Fester Wert: 72h
|===

Das in der Abbildung "Laufzeitansicht - Aktualisierung der Föderationsliste" referenzierte
Sequenzdiagramm "Provider authentifizieren und Föderationsliste abrufen":

.Sequenzdiagramm "Provider authentifizieren und Föderationsliste abrufen"
[%collapsible%open]
====
++++
<p align="center">
  <img width="100%" src=../../images/plantuml/TI-Messenger-Dienst/Ressourcen/UC_Update_Federationlist_auth_retrieve.svg>
</p>
++++
====

Das in der Abbildung "Laufzeitansicht - Aktualisierung der Föderationsliste" referenzierte
Sequenzdiagramm "Signatur der Föderationsliste prüfen":

.Sequenzdiagramm "Signatur der Föderationsliste prüfen"
[%collapsible%open]
====
++++
<p align="center">
  <img width="60%" src=../../images/plantuml/TI-Messenger-Dienst/Ressourcen/UC_Update_Federationlist_SignCheck.svg>
</p>
++++
====
