ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images

image:meta/gematik_logo.svg[width=70%]

=== AF_10060 - Bereitstellung eines Messenger-Service für eine Organisation
Mit diesem Anwendungsfall wird einer zuvor am *Registrierungs-Dienst* authentifizierten Organisation ein *Messenger-Service* für diese Organisation durch einen Akteur in der Rolle "Org-Admin" bereitgestellt. Die Beantragung zur Bereitstellung eines *Messenger-Service* wird durch den Akteur in der Rolle "Org-Admin" am *Frontend des Registrierungs-Dienstes* vorgenommen. Dieser MUSS sich zuvor mit dem Admin-Account der Organisation am *Registrierungs-Dienst* anmelden. Für eine zeitnahe Adaption des *TI-Messenger-Dienstes* MUSS eine schnelle Bereitstellung von *Messenger-Services* gewährleistet sein. Anbieter eines *TI-Messenger-Fachdienstes* sind verpflichtet, Prozesse zu etablieren, damit *Messenger-Services* für Organisationen schnell und ggf. automatisiert bereitgestellt werden können. Nach erfolgreicher Bereitstellung eines *Messenger-Service* wird dieser in die Föderation des *TI-Messenger-Dienstes* aufgenommen. Werden mehrere *Messenger-Services* für eine Organisation benötigt kann dieser Anwendungsfall mehrfach ausgeführt werden.

.Anwendungsfallbeschreibung
[%collapsible%open]
====
[caption=]
Bereitstellung eines Messenger-Service für eine Organisation
[%header, cols="1,1"]
|===
| |Beschreibung
|*Akteur* |Beauftragter Mitarbeiter einer Organisation in der Rolle "Org-Admin"
|*Auslöser* |Eine Organisation des deutschen Gesundheitswesen möchte am TI-Messenger-Dienst teilnehmen und benötigt die Bereitstellung eines oder mehrerer Messenger-Services
|*Komponenten* a|
              * Frontend des Registrierungs-Dienstes, 
              * Registrierungs-Dienst, 
              * VZD-FHIR-Directory,
              * Messenger-Service 
|*Vorbedingungen* a| 
                  * Es besteht ein Vertragsverhältnis mit einem TI-Messenger-Anbieter.
                  * Der Akteur verfügt über ein Frontend des Registrierungs-Dienstes für die Kommunikation mit dem Registrierungs-Dienst.
                  * Das verwendete Frontend des Registrierungs-Dienstes ist beim zentralen IDP-Dienst registriert.
                  * Die Organisation ist erfolgreich beim Registrierungs-Dienst authentifiziert und ein Admin-Account ist vorhanden.
                  * Der Registrierungs-Dienst kann sich beim VZD-FHIR-Directory Server für Schreibzugriffe mit OAuth2 authentisieren.
|*Eingangsdaten* |Admin-Account, Identität der Organisation (SMC-B)
|*Ergebnis* a|
            * Der Messenger-Service für die Organisation wurde erstellt.
            * Die Matrix-Domain des neuen Messenger-Services wurde als Endpunkt im VZD-FHIR-Directory eingetragen und in die Föderation aufgenommen.
|*Ausgangsdaten* |Neuer Messenger-Service für die Organisation, Status
|===
====
.Sequenzdiagramm
[%collapsible%open]
====
image:generated/TI-Messenger-Dienst/Ressourcen/UC_10060_Seq.svg[width="100%"]
====
