ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images

image:meta/gematik_logo.svg[width=70%]

=== AF_10058 Akteur - (User-HBA) im Verzeichnisdienst hinzufügen
Mit diesem Anwendungsfall wird ein Akteur in der Rolle "User-HBA" für andere Akteure anderer *Messenger-Services* auffindbar und erreichbar. Dafür werden FHIR-Ressourcen mit ihrer jeweiligen `MXID` im Personenverzeichnis (`PractitionerRole`) des *VZD-FHIR-Directory* hinterlegt. Zusätzlich besteht die Möglichkeit die Sichtbarkeit für andere Akteure einzuschränken. Dieser Anwendungsfall kann direkt mit dem initialen Anmeldevorgang eines Akteurs am *Messenger-Service* (siehe Anwendungsfall: link:/docs/anwendungsfaelle/COM-AF10057-anmeldung-am-messenger-service.adoc[AF_10057 - Anmeldung eines Akteurs am Messenger-Service]) kombiniert werden. Hierfür wird der Akteur in der Rolle "User-HBA" während des Anmeldevorgangs durch den *TI-Messenger-Client* gefragt, ob dieser im Besitz eines HBAs ist.

.Anwendungsfallbeschreibung
[%collapsible%open]
====
[caption=]
Akteur (User-HBA) im Verzeichnisdienst hinzufügen
[%header, cols="1,1"]
|===
| |Beschreibung
|*Akteur* |Leistungserbringer, Mitarbeiter einer Organisation im Gesundheitswesen in der Rolle "User-HBA"
|*Auslöser* |Ein Akteur in der Rolle "User-HBA" möchte sich im Personenverzeichnis erreichbar machen, indem er seine MXID im seinen Practitioner-Datensatz im VZD-FHIR-Directory hinterlegt.
|*Komponenten* a|
              * TI-Messenger-Client,
              * Authenticator,
              * zentraler IDP-Dienst, 
              * FHIR-Proxy, 
              * Auth-service,
              * VZD-FHIR-Directory,
|*Vorbedingungen* a| 
                  * Der Akteur ist bei einem gültigen Messenger-Service angemeldet.
                  * Der Akteur verfügt über einen zugelassenen TI-Messenger-Client.
                  * Das VZD-FHIR-Directory ist beim zentralen IDP-Dienst registriert.
                  * Der Akteur kann sich am zentralen IDP-Dienst authentisieren.
|*Eingangsdaten* |HBA, FHIR-Practitioner-Ressourcen
|*Ergebnis* |FHIR-Practitioner-Ressourcen aktualisiert, Status
|*Ausgangsdaten* |aktualisierter Practitioner-Datensatz
|===
====
.Sequenzdiagramm
[%collapsible%open]
====
image:plantuml/TI-Messenger-Dienst/Ressourcen/UC_10058_Seq.svg[width="100%"]
====
