ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images

image:meta/gematik_logo.svg[width=70%]

=== AF_10059 - Organisationsressourcen im Verzeichnisdienst hinzufügen
Mit diesem Anwendungsfall macht ein Akteur in der Rolle "Org-Admin" Akteure seiner Organisation im *TI-Messenger-Dienst* für andere Akteure auffindbar und erreichbar. Dafür werden Endpoint-Ressourcen mit ihrer jeweiligen `MXID` im Organisationsverzeichnis (`HealthcareService`) des *VZD-FHIR-Directory* hinterlegt. Organisationen können mehrere FHIR-Ressourcen pro Organisation administrieren und somit eingehende Kommunikationsprozesse organisatorisch und thematisch strukturieren (siehe *[gemSpec_VZD_FHIR_Directory]*).

.Anwendungsfallbeschreibung
[%collapsible%open]
====
[caption=]
Organisationsressourcen im Verzeichnisdienst hinzufügen
[%header, cols="1,1"]
|===
| |Beschreibung
|*Akteur* |Beauftragter Mitarbeiter einer Organisation in der Rolle "Org-Admin"
|*Auslöser* |Der Administrator der Organisation (Org-Admin) möchte seine Organisation erreichbar machen indem die MXIDs der Akteure der Organisation im VZD-FHIR-Directory hinterlegt werden.
|*Komponenten* a|
              * TI-Messenger-Client (mit erweiterter Org-Admin Funktionalität),
              * TI-Messenger Registrierungs-Dienst
              * Auth-Service 
              * FHIR-Proxy
              * FHIR-Directory
|*Vorbedingungen* a| 
                  * Für die Organisation wurde ein Messenger-Service bereitgestellt und es existiert ein Eintrag der Organisation im FHIR-Directory.
                  * Der Administrator der Organisation verfügt über einen TI-Messenger-Client (mit erweiterter Org-Admin Funktionalität).
                  * Es existiert eine Vertrauensbeziehung zwischen dem TI-Messenger Registrierungs-Dienst und dem VZD-FHIR-Directory (Übergabe des Zertifikates)
                  * Der Administrator der Organisation wurde vom Registrierungs-Dienst authentifiziert.
|*Eingangsdaten* | Org-Admin-Credentials, zweiter Faktor, FHIR-Organisations-Ressourcen
|*Ergebnis* | FHIR-Organisations-Ressourcen aktualisiert, Status
|*Ausgangsdaten* | Aktualisierte VZD-FHIR-Directory-Datensätze 
|===
====

.Sequenzdiagramm
[%collapsible%open]
====
++++
<p align="center">
  <img width="100%" src=../../images/plantuml/TI-Messenger-Dienst/Ressourcen/UC_10059_Seq.svg>
</p>
++++
====
