ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images

image:meta/gematik_logo.svg[width=70%]

=== A 8.1 - Einträge im VZD-FHIR-Directory suchen
Die folgende Sequenz beschreibt, wie ein Akteur im *VZD-FHIR-Directory* nach `HealthcareService`- und `PractitionerRole`-Ressourcen sucht. Dies setzt eine erfolgreiche Anmeldung des Akteurs an einem *Messenger-Service* voraus. Der dargestellte Ablauf zeigt alle prinzipiell notwendigen Kommunikationsbeziehungen. Weitergehende Informationen zum Ablauf sind in der *[gemSpec_VZD_FHIR_Directory]* zu finden. Für die Prüfung des `Matrix-OpenID-Tokens` muss der Zugriff auf den Endpunkt `/_matrix/federation/v1/openid/userinfo` ermöglicht werden.

.Anwendungsfallbeschreibung
[%collapsible%open]
====
[caption=]
Einträge im VZD-FHIR-Directory suchen
[%header, cols="1,1"]
|===
| |Beschreibung
|*Akteur* |Anwender in der Rolle "User/User-HBA"
|*Auslöser* |Ein Akteur in der Rolle "User"/"User-HBA" setzt eine Suche ab.
|*Komponenten* a|
              * TI-Messenger-Client,
              * Messenger-Proxy,
              * Matrix-Homeserver
              * FHIR-Proxy, 
              * Auth-Service,
              * VZD-FHIR-Directory,
|*Vorbedingungen* a| 
                  * Der Akteuer ist bei seinem Homeserver eingeloggt. 
                  *	Dem Matrix Homeserver wird vom VZD-FHR-Directory vertraut.
                  * Der Aktuer darf sich mit seinem Matrix-OpenID-Token authentisieren.
                  * Der Messenger-Proxy erlaubt dem VZD-FHIR-Directory Zugriff auf /_matrix/federation/v1/openid/userinfo, um den Token prüfen zu lassen.
|*Eingangsdaten* |Search, Matrix OpenID Token
|*Ergebnis* | Die gesuchten FHIR-Resourcen.
|*Ausgangsdaten* | FHIR Datensätze
|===

====
.Sequenzdiagramm
[%collapsible%open]
====
image:generated/Other/UC_Directory_search_Seq.svg[width="100%"]
====
