ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: /images

image:gematik_logo.svg[width=35%]

= TI-Messenger - API - Dokumentation

== Allgemeines

== Systemüberblick

== Ordnerstruktur
Im Folgenden ist die Organisation der Ordnerstruktur dargestellt.

    TI-Messenger-API
    ├─ github
	   │   └──── workflows
    ├─ .vscode
	   ├─ Vorabveroeffentlichungen
	   │   └──── TIM_1.1
	   ├─ images
	   │   └──── diagrams
    ├─ src
    │   ├──── fhir
    │   ├──── openapi
    │   └──── plantuml
    ├── README.md
    └── ReleaseNotes.md

== Ausbaustufen

== Referenzierte Dokumente

== Weiterführende Seiten

== Lizenzbedingungen
Copyright (c) 2022 gematik GmbH

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. 
