:imagesdir: /images/
= TI-Messenger Dokumentation

image::gematik_logo.svg[gematik,width="70%"]

image:https://img.shields.io/badge/Release%20Notes-v0.1-red?style=plastic&logo=github&logoColor=red[link="ReleaseNotes.md"] +
image:https://img.shields.io/badge/ContactManagement-v1.0.0-blue?style=plastic&logo=github&logoColor=blue[link=/src/openapi/TiMessengerContactManagement.yaml"]
image:https://img.shields.io/badge/TestTreiber-v0.2.0-blue?style=plastic&logo=github&logoColor=blue[link="/src/openapi/TiMessengerTestTreiber.yaml"] +
image:https://img.shields.io/badge/TI&hyphen;Messenger&hyphen;Dienst-v1.1.0-green?style=plastic&logo=github&logoColor=green[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-Dienst_V1.1.0.pdf"]
image:https://img.shields.io/badge/TI&hyphen;Messenger&hyphen;FD-v1.1.0-green?style=plastic&logo=github&logoColor=green[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-FD_V1.1.0.pdf"]
image:https://img.shields.io/badge/TI&hyphen;Messenger&hyphen;Client-v1.1.0-green?style=plastic&logo=github&logoColor=green[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-Client_V1.1.0.pdf"]



== Allgemeines

Der TI-Messenger ermöglicht sicheres und interoperable Instant Messaging im Gesundheitswesen.
Im Gesundheitswesen spielt das Konzept der digitalen Ad-hoc-Kommunikation eine immer wichtigere Rolle. Allerdings stoßen die Nutzer derzeit auf verschiedene Hürden, darunter:

- fehlende Interoperabilität zwischen den Messenger-Anbietern,
- fehlende einheitliche Zertifizierung zur Gewährleistung der Sicherheit sowie
- fehlende einheitliche Vorgaben zur Authentisierung.

TI-Messenger hingegen werden auf Basis des Matrix-Protokolls, dem offenen Messenger-Standard der Matrix.org Foundation, neue Maßstäbe für die Kommunikation in Echtzeit setzen. Der neue Kommunikationsstandard der gematik gewährleistet:

- Interoperabilität - und somit den sektoren- und anbieterübergreifenden Austausch
- Integrität dank hohem Out-of-the-box-Sicherheitsniveau,
- Ende-zu-Ende-Verschlüsselung sowie
- Innovation durch fortlaufende Weiterentwicklung des Matrix-Protokolls.

Die folgende Dokumentation beschreibt die systemspezifische Lösung von TIM 1.1. An dieser Stelle werden insbesondere die Komponenten der Lösung sowie deren Schnittstellen dargestellt und erläutert. Der Funktionsumfang der TIM Version 1.1 beinhaltet wie folgt:

* die Kommunikation zwischen Leistungserbringern

* die Kommunikation zwischen Leistungserbringern und Leistungserbringerorganistionen

* 

++++
<p align="left">
  <img width="100%" src=/images/System_overview.png>
</p>
++++

== Folder structure

    TI-Messenger-API
    ├─ github
	   │   └──── workflows
    ├─ src
    │   ├──── fhir
    │   ├──── openapi
    │   └──── plantuml
    ├── README.md
    └── ReleaseNotes.md




== License
Copyright (c) 2022 gematik GmbH

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
