:imagesdir: /images/
= TI-Messenger Dokumentation

image::gematik_logo.svg[gematik,width="70%"]

image:https://img.shields.io/badge/Release%20Notes-v0.1-red?style=plastic&logo=github&logoColor=red[link="ReleaseNotes.md"] +
image:https://img.shields.io/badge/ContactManagement-v1.0.0-blue?style=plastic&logo=github&logoColor=blue[link=/src/openapi/TiMessengerContactManagement.yaml"]
image:https://img.shields.io/badge/TestTreiber-v0.2.0-blue?style=plastic&logo=github&logoColor=blue[link="/src/openapi/TiMessengerTestTreiber.yaml"] +
image:https://img.shields.io/badge/TI&hyphen;Messenger&hyphen;Dienst-v1.1.0-green?style=plastic&logo=github&logoColor=green[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-Dienst_V1.1.0.pdf"]
image:https://img.shields.io/badge/TI&hyphen;Messenger&hyphen;FD-v1.1.0-green?style=plastic&logo=github&logoColor=green[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-FD_V1.1.0.pdf"]
image:https://img.shields.io/badge/TI&hyphen;Messenger&hyphen;Client-v1.1.0-green?style=plastic&logo=github&logoColor=green[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-Client_V1.1.0.pdf"]



== Allgemeines
Die folgende Dokumentation baut auf die Spezifikation des TI-Messengers v1.1 gemäß *[gemSpec_TI-Messenger-Dienst]* auf. An dieser Stelle werden insbesondere die in der Spezifikation genannten Komponenten der Lösung sowie deren Schnittstellen weiter dargestellt und erläutert, um Herstellern und Anbietern bestmöglich zu unterstützen. Der Funktionsumfang des TI-Messengers in der Version 1.1 beinhaltet: +

* die Echtzeit-Kommunikation zwischen Leistungserbringern und Leistungserbringerinstitutionen und
* die Echtzeit-Kommunikation direkt zwischen Leistungserbringern.

_Hinweis: In der TI-Messenger Version v1.1 können keine Versicherten an dem TI-Messenger Dienst teilnehmen_

== Systemüberblick
Die folgende Abbildung gibt einen Überblick über die Systemarchitektur des TI-Messengers in der Version 1.1. Die ebenfalls für den Betreib des TI-Messenger Dienstes notwendigen IDP-Dienste werden an dieser Stelle nicht betrachtet.

++++
<p align="left">
  <img width="100%" src=/images/System_overview.png>
</p>
++++

link:docs/TI-Messenger-Fachdienst.adoc[*TI-Messenger-Fachdienst*]

* *Registrierungs-Dienst:* +
Der Registrierungs-Dienst ist eine Komponente, die vom Hersteller des TI-Messenger-Fachdienstes umgesetzt wird. Über ein Frontend des Registrierungsdientes ist es einem Akteur in der Rolle "Org-Admin" möglich einen Administrations-Account im Registrierungs-Dienst für seine Organisation anzulegen. Dieser ermöglicht es ihm einen oder mehrere Messenger-Services für seine Organisation zu registrieren. Die Eintragung der Matrix-Domain seiner Messenger-Services in die Ressource der Organisation im FHIR-VZD-Directory erfolgt ebenfalls durch den Registrierungsdienst. Der Registrierungs-Dienst muss eine Liste aller verifizierten Matrix-Domains des VZD-FHIR-Directory vorhalten und diese den Messenger-Proxies über eine interne Schnittstelle bereitstellen.

* *Messenger-Service:* +
Ein Messenger-Service besteht aus den Teilkomponenten Matrix-Homeserver und dem Messenger-Proxy. Die Teilkomponente Matrix-Homeserver basiert auf dem offenen Kommunikationsprotokoll Matrix. Der Messenger-Proxy muss für jeden Messenger-Service bereitgestellt werden. Alle Anfragen der TI-Messenger-Clients und anderer Messenger-Services an den Matrix-Homeserver werden über den Messenger-Proxy geleitet. Die TLS-Kommunikation zwischen den TI-Messenger-Clients und den Matrix-Homeservern werden am Messenger-Proxy terminiert. Für die Nutzung eines eigenen Authentifizierungs-Dienstes durch eine Organisation wird durch den Messenger-Proxy eine Schnittstelle für die Anbindung des Authentifizierungs-Dienstes der Organisation bereitgestellt. Der Messenger-Proxy ruft bei seinem zuständigen Registrierungs-Dienst die Föderationsliste über die interne Schnittstelle (I_internVerification) ab und  speichert diese lokal. Der Messenger-Proxy hält eine Freigabeliste vor, die zur Prüfung, ob einem eingehenden Invite-Event am Messenger-Proxy zugestimmt wird, genutzt wird.

* *Push-Gateway:* +
Der TI-Messenger-Fachdienst stellt ein Push-Gateway, gemäß [Matrix Specification#Push Gateway API], für den TI-Messenger-Client bereit. Das Push-Gateway ermöglicht es, Akteure über eingegangene Nachrichten zu informieren.

link:docs/TI-Messenger-Fachdienst.adoc[*TI-Messenger-Client*] +

* TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT

link:docs/TI-Messenger-Fachdienst.adoc[*VZD-FHIR-Directory*] +

* TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT

== Ordnerstruktur
Im Folgenden ist die Organisation der Ordnerstruktur dargestellt.

----
TI-Messenger Dokumentation
├─ github
│   └──── workflows
├─ docs
├─ images
├─ src
│   ├──── fhir
│   │    ├── fsh-generated
│   │    ├── input
│   │    ├── output
│   │    ├── temp
│   │    └── template
│   ├──── openapi
│   │    ├── TiMessengerContactManagement.yaml
│   │    └── TiMessengerTestTreiber.yaml 
│   ├──── plantuml
│   │    ├── TI-Messenger-Dienst
│   │    ├── architecture
│   │    └── includes 
│   └──── schema
│        └── Attachment_schema.json
├── README.adoc
└── ReleaseNotes.md
----

== Referenzierte Dokumente
Die nachfolgende Tabelle enthält die in der vorliegenden Online Dokumentation referenzierten Dokumente der gematik zur Telematikinfrastruktur. Deren zu diesem Dokument jeweils gültige Versionsnummer entnehmen Sie bitte der aktuellen, auf der Internetseite der gematik veröffentlichten, Dokumentenlandkarte, in der die vorliegende Version aufgeführt wird.

|===
|[Quelle] |Herausgeber: Titel

|*[gemSpec_TI-Messenger-Dienst]* |gematik: Spezifikation TI-Messenger-Dienst
|*[gemSpec_TI-Messenger-FD]* |gematik: Spezifikation TI-Messenger-Fachdienst
|*[gemSpec_TI-Messenger-Client]* |gematik: Spezifikation TI-Messenger-Client
|*[gemSpec_VZD_FHIR_Directory]* |gematik: Spezifikation Verzeichnisdienst FHIR-Directory
|===

== Weiterführende Seiten
*Anwendungsfälle* +
link:docs/Anwendungsfaelle.adoc[- Anwendungsfälle] 

*Produkttypen* +
link:docs/KIM_API.adoc[- TI-Messenger-Fachdienst] +
link:docs/Fachdienst.adoc[- TI-Messenger-Client] +
link:docs/Verzeichnisdienst.adoc[- VZD-FHIR-Directory]

*Leitfaden für Primärsystemhersteller* +
link:docs/Primaersystem.adoc[- Primärsystem] 

*Diverses* +
link:docs/Authentisierung.adoc[- Authentisierung] +
link:docs/faq.adoc[- Fragen und Antworten zur aktuellen Spezifikation &#91;FAQ&#93;]

*Referenz-Implementierungen* +
https://github.com/gematik/kim-attachment-service[-] +

== License
Copyright (c) 2022 gematik GmbH

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
