= api-ti-messenger
gematik, Systems Engineering
:source-highlighter: rouge
:title-page:
:imagesdir: /images/
ifdef::env-github[]
:toc: preamble
endif::[]
ifndef::env-github[]
:toc: left
endif::[]
:toclevels: 3
:toc-title: Inhaltsverzeichnis
// ifndef::env-github[]
//image::gematik_logo.svg[gematik,float="right"]
// endif::[]
// ifdef::env-github[]
// ++++
// <img align="right" role="right" src="images/gematik_logo.svg?raw=true"/>
// ++++
// endif::[]

image::gematik_logo.svg[width=70%]

image:https://img.shields.io/badge/gemSpec__TI--Messenger--Client-v1.1.0-blue[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-Client_V1.1.0.pdf"]
image:https://img.shields.io/badge/gemSpec__TI--Messenger--FD-v1.1.0-blue[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-FD_V1.1.0.pdf"]


Im Gesundheitswesen spielt das Konzept der digitalen Ad-hoc-Kommunikation eine immer wichtigere Rolle. Der sichere und interoperable Nachrichtenaustausch zwischen beteiligten Akteuren des deutschen Gesundheitswesens erfolgt über den TI-Messenger.

Dieser basiert auf dem Matrix-Protokoll, einem offenen Messenger-Standard der Matrix.org Foundation. Der neue Kommunikationsstandard der gematik gewährleistet:

- Interoperabilität - und somit den sektoren- und anbieterübergreifenden Austausch
- Integrität dank hohem Out-of-the-box-Sicherheitsniveau,
- Ende-zu-Ende-Verschlüsselung sowie
- Innovation durch fortlaufende Weiterentwicklung des Matrix-Protokolls.
