= api-ti-messenger
gematik, Systems Engineering
:source-highlighter: rouge
:title-page:
:imagesdir: /images/
ifdef::env-github[]
:toc: preamble
endif::[]
ifndef::env-github[]
:toc: left
endif::[]
:toclevels: 3
:toc-title: Inhaltsverzeichnis
//:sectnums:

image::gematik_logo.svg[gematik,float="right"]

Der TI-Messenger ermöglicht sicheres und interoperable Instant Messaging im Gesundheitswesen.
Im Gesundheitswesen spielt das Konzept der digitalen Ad-hoc-Kommunikation eine immer wichtigere Rolle. Allerdings stoßen die Nutzer derzeit auf verschiedene Hürden, darunter:

- fehlende Interoperabilität zwischen den Messenger-Anbietern,
- fehlende einheitliche Zertifizierung zur Gewährleistung der Sicherheit sowie
- fehlende einheitliche Vorgaben zur Authentisierung.

TI-Messenger hingegen werden auf Basis des Matrix-Protokolls, dem offenen Messenger-Standard der Matrix.org Foundation, neue Maßstäbe für die Kommunikation in Echtzeit setzen. Der neue Kommunikationsstandard der gematik gewährleistet:

- Interoperabilität - und somit den sektoren- und anbieterübergreifenden Austausch
- Integrität dank hohem Out-of-the-box-Sicherheitsniveau,
- Ende-zu-Ende-Verschlüsselung sowie
- Innovation durch fortlaufende Weiterentwicklung des Matrix-Protokolls.
