ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ./images/
= TI Messenger Documentation

image::gematik_logo.svg[gematik,width="70%"]

image:https://img.shields.io/badge/Release%20Notes-v1.1.1-red?style=plastic&logo=github&logoColor=red[link="ReleaseNotes.md"] +
image:https://img.shields.io/badge/ContactManagement-v1.0.1-blue?style=plastic&logo=github&logoColor=blue[link=/src/openapi/TiMessengerContactManagement.yaml"]
image:https://img.shields.io/badge/TestTreiber-v0.3.0-blue?style=plastic&logo=github&logoColor=blue[link="/src/openapi/TiMessengerTestTreiber.yaml"] +
image:https://img.shields.io/badge/TI&hyphen;Messenger&hyphen;Dienst-v1.1.1-green?style=plastic&logo=github&logoColor=green[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-Dienst_V1.1.1.pdf"]
image:https://img.shields.io/badge/TI&hyphen;Messenger&hyphen;FD-v1.1.1-green?style=plastic&logo=github&logoColor=green[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-FD_V1.1.1.pdf"]
image:https://img.shields.io/badge/TI&hyphen;Messenger&hyphen;Client-v1.1.1-green?style=plastic&logo=github&logoColor=green[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-Client_V1.1.1.pdf"]

== Überblick
Die folgende Dokumentation baut auf die Spezifikation TI-Messenger-Dienst v1.1.1 gemäß *[gemSpec_TI-Messenger-Dienst]* auf. An dieser Stelle werden insbesondere die in der Spezifikation genannten Komponenten der Lösung sowie deren Schnittstellen weiter dargestellt und erläutert, um Herstellern und Anbietern bestmöglich zu unterstützen. Der Funktionsumfang des TI Messenger-Dienst v1.1.1 beinhaltet: +

* die Echtzeit-Kommunikation zwischen Leistungserbringern und Leistungserbringerinstitutionen und
* die Echtzeit-Kommunikation direkt zwischen Leistungserbringern.

💡 _Hinweis: In der TI-Messenger-Dienst v1.1.1 können keine Versicherten an dem TI-Messenger Dienst teilnehmen_

== Branches
Für die Dokumentation des TI-Messenger-Dienstes werden die folgenden Branches verwendet:

- *main*: enthält die Dokumentation für die aktuell veröffentlichte Version gemäß *[gemSpec_TI-Messenger-Dienst]*
- *develop*: enthält die Dokumentation der in Entwicklung befindlichen Features 
- *feature/**: Dieser Branch wird zur Vorbereitung und Diskussion neuer Themen, die noch nicht in der Entwicklung sind, verwendet. Diese Dokumente können unvollständig sein und sich bis zur Fertigstellung noch ändern.

== Systemübersicht
Die folgende Abbildung gibt einen Überblick über die Systemarchitektur des TI-Messenger-Dienst v1.1.1. Die ebenfalls für den Betreib des TI-Messenger Dienstes notwendigen IDP-Dienste werden an dieser Stelle nicht betrachtet.

++++
<p align="left">
  <img width="100%" src=./images/System_overview.png>
</p>
++++

link:docs/Fachdienst/Fachdienst.adoc[*TI Messenger-Fachdienst*]

* link:docs/Fachdienst/Registrierungsdienst.adoc[*Registrierungs-Dienst*] +
Der Registrierungs-Dienst bietet zwei abstrakte Schnittstellen an. Die Schnittstelle `I_Registration` wird vom Frontend des Registrierungs-Dienstes aufgerufen, um eine Organisation beim Registrierungs-Dienst zu authentifizieren und Messenger-Services zu administrieren. Die Schnittstelle `I_internVerfification` wird von den Messenger-Proxies aufgerufen, um die Föderationsliste abzurufen und für die Prüfung auf existierende VZD-FHIR-Einträge der beteiligten Akteure einer beabsichtigten Kommunikation.

* link:docs/Fachdienst/MessengerService.adoc[*Messenger-Service*] +
Ein Messenger-Service besteht aus den Teilkomponenten Messenger-Proxy und einem Matrix-Homeserver. Die Teilkomponente Matrix-Homeserver basiert auf dem offenen Kommunikationsprotokoll Matrix und bietet die `Matrix-Client-Server API` sowie die `Matrix-Server-Server API` an. Die Kommunikation zu einem Matrix-Homeserver wird immer über den Messenger-Proxy geleitet, sofern die Berechtigungsprüfung erfolgreich war. Dieser stellt die Schnittstelle `I_TiMessengerContactManagement` bereit, um die Administration einer Freigabeliste eines Akteurs zu ermöglichen. 

* https://spec.matrix.org/v1.3/push-gateway-api/[*Push-Gateway*] +
Das Push-Gateway stellt die `Matrix-Push Gateway API` gemäß der Matrix Spezifikation bereit. Dieses ermöglicht die Weiterleitung von Benachrichtigungen an Akteure des TI-Messenger-Dienstes.

link:docs/Client/Client.adoc[*TI Messenger-Client*] +

* Der TI-Messenger-Client basiert auf der `Matrix-Client-Server API`. Er wird durch weitere Funktionsmerkmale erweitert und ruft die Schnittstellen am TI-Messenger-Fachdienst sowie am VZD-FHIR-Directory auf.

link:docs/FHIR-Directory/FHIR-Directory.adoc[*VZD-FHIR-Directory*] +

* Beim VZD-FHIR-Directory handelt es sich um einen zentralen Verzeichnisdient der TI, der die deutschlandweite Suche von Organisationen und Akteuren des TI-Messenger-Dienstes ermöglicht. Das VZD-FHIR-Directory basiert auf dem FHIR-Standard und bietet für den TI-Messenger-Dienst relevante Schnittstellen an. Die Schnittstelle `I_VZD_TiMessenger_services` wird vom Registrierungs-Dienst aufgerufen, um eine Föderationsliste herunterzuladen. Die Schnittstellen `tim-authenticate` und `owner-authenticate` werden von den TI-Messenger-Clients aufgerufen, um eine Suche bzw. einen Eintrag im VZD-FHIR-Directory zu ermöglichen.

link:docs/IDP/idp.adoc[*Zentraler IDP-Dienst*] +

* Der Zentralen IDP-Dienst der gematik übernimmt die Aufgabe der smartcard-basierten Authentisierung eines Akteures. Hierbei fast der IDP-Dienst aus der Smartcard notwendige Attribute (z. B. `TelematikID`, `ProfessionOID`) in signierten JSON Web Token (ID_TOKEN) zusammen, um Zugriff auf angebotene Daten zu erhalten. 

link:docs/IDP/authenticator.adoc[*gematik Authenticator*] +

* Der Authenticator der gematik erhält vom IDP-Dienst einen `AUTHORIZATION_CODE` zurück, welches durch Vorlage vom Registrierungs-Dienst oder vom Auth-Service des VZD-FHIR-Directory am IDP-Dienst durch ein ID_TOKEN ausgetauscht wird.


== Ordnerstruktur
Im Folgenden ist die Organisation der Ordnerstruktur dargestellt.

----
TI-Messenger Dokumentation
├─ github
│   └──── workflows
├─ docs
|   ├──── changes
|   └──── use-cases
├─ images
├─ src
│   ├──── fhir
│   │    ├── fsh-generated
│   │    ├── input
│   │    ├── output
│   │    ├── temp
│   │    └── template
│   ├──── openapi
│   │    ├── TiMessengerContactManagement.yaml
│   │    └── TiMessengerTestTreiber.yaml 
│   ├──── plantuml
│   │    ├── TI-Messenger-Dienst
│   │    ├── architecture
│   │    └── includes 
│   └──── schema
│        └── Attachment_schema.json
├── README.adoc
└── ReleaseNotes.md
----

== Refferenzierte Dokumente
Die nachfolgende Tabelle enthält die in der vorliegenden Online Dokumentation referenzierten Dokumente der gematik zur Telematikinfrastruktur. Deren zu diesem Dokument jeweils gültige Versionsnummer entnehmen Sie bitte der aktuellen, auf der Internetseite der gematik veröffentlichten, Dokumentenlandkarte, in der die vorliegende Version aufgeführt wird.

|===
|[Source] |Editor: Title

|*[gemSpec_TI-Messenger-Dienst]* |gematik: Spezifikation TI-Messenger-Dienst
|*[gemSpec_TI-Messenger-FD]* |gematik: Spezifikation TI-Messenger-Fachdienst
|*[gemSpec_TI-Messenger-Client]* |gematik: Spezifikation TI-Messenger-Client
|*[gemSpec_VZD_FHIR_Directory]* |gematik: Spezifikation Verzeichnisdienst FHIR-Directory
|*[gemSpec_IDP_Dienst]* |gematik: Spezifikation Identity Provider-Dienst
|===

== 💡 Onboarding
Hersteller und Anbieter eines TI-Messenger-Dienstes können das von der gematik bereitgestellte https://gematikde.sharepoint.com/:w:/s/PTNeo/EczX7AFGfBdNrCYghzGsHz4BbSoYhV63QMmDCdz7x9zLpg?e=7wG3c[Welcome Package] zum Onboarding nutzen. Dieses Welcome Package ist als "Schritt-für-Schritt"-Anleitung gedacht, um Hersteller und Anbieter beim Onboarding des TI-Messenger-Dienstes zu unterstützen.

== Weiterführende Seiten
*Anwendungsfäll* +
link:docs/TI-Messenger-Anwendungsfaelle.adoc[- Anwendungsfälle] 

*Produkttypen* +
link:docs/Fachdienst/Fachdienst.adoc[- TI-Messenger-Fachdienst] +
link:docs/Client/Client.adoc[- TI-Messenger-Client] +
link:docs/FHIR-Directory/FHIR-Directory.adoc[- VZD-FHIR-Directory] +
link:docs/IDP/idp.adoc[- Zentraler IDP-Dienst] +

*Leitfaden für Primärsystemhersteller* +
link:docs/Primaersystem/Primaersystem.adoc[- Primärsystem] +

*Diverses* +
https://gematikde.sharepoint.com/:w:/s/PTNeo/EczX7AFGfBdNrCYghzGsHz4BbSoYhV63QMmDCdz7x9zLpg?e=7wG3c[- Welcome Package &#91;DE&#93;] +
https://gematikde.sharepoint.com/:w:/s/PTNeo/ETwc10F5Ha1KmlM8NEsetl8BtEumSDgu56AK-PNiZ0-e1Q?e=ySZROI[- Welcome Package &#91;EN&#93;] +
https://gematikde.sharepoint.com/sites/EXTAuthenticator/Freigegebene%20Dokumente/Forms/AllItems.aspx?id=%2Fsites%2FEXTAuthenticator%2FFreigegebene%20Dokumente%2FVer%C3%B6ffentlichte%20Version%20%2D%20gematik%20Authenticator&p=true&ga=1[- gematik Authenticator] +
https://github.com/gematik/TI-Messenger-Testsuite[- TI-Messenger-Testsuite] +
link:docs/Q&A.adoc[- Fragen und Antworten zur aktuellen Spezifikation &#91;FAQ&#93;]

*Referenz-Implementierungen* +
- [comming soon]

== License
Copyright (c) 2023 gematik GmbH

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
