= api-ti-messenger
gematik, Systems Engineering
:source-highlighter: rouge
:title-page:
:imagesdir: /images/
ifdef::env-github[]
:toc: preamble
endif::[]
ifndef::env-github[]
:toc: left
endif::[]
:toclevels: 3
:toc-title: Inhaltsverzeichnis
// ifndef::env-github[]
//image::gematik_logo.svg[gematik,float="right"]
// endif::[]
// ifdef::env-github[]
// ++++
// <img align="right" role="right" src="images/gematik_logo.svg?raw=true"/>
// ++++
// endif::[]

image::gematik_logo.svg[gematik,float="right"]

image:https://img.shields.io/badge/gemSpec__TI--Messenger--Client-v1.1.0-blue[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-Client_V1.1.0.pdf"]
image:https://img.shields.io/badge/gemSpec__TI--Messenger--FD-v1.1.0-blue[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-FD_V1.1.0.pdf"]

== Introduction

The TI-Messenger is a secure and interoperable Instant Messaging for the german healthcare system.
Digital ad-hoc communication is becoming more and more important in the healthcare system.

However, users are currently encountering various hurdles, including:

- lack of interoperability between the messenger providers,
- lack of uniform certification to ensure safety and
- lack of uniform specifications for authentication.

TI messengers, on the other hand, will set new standards for real-time communication based on the Matrix protocol, the open messenger standard from the Matrix.org Foundation. The new communication standard from gematik guarantees:

- Interoperability - and thus cross-sector and cross-provider exchange
- integrity thanks to high level security out-of-the-box,
- End-to-end encryption and
- Innovation through continuous development of the Matrix protocol.

== System overview

== Folder structure

    TI-Messenger-API
    ├─ github
	   │   └──── workflows
    ├─ src
    │   ├──── fhir
    │   ├──── openapi
    │   └──── plantuml
    ├── README.md
    └── ReleaseNotes.md


== TI-Messenger-Client

=== Matrix Client-Server-API

https://spec.matrix.org/v1.4/client-server-api/[The matrix.org Client-Server-API]

=== FHIR-Directory Search-API

xref:docs/FHIR-Directory-search-api.adoc[FHIR-Directory Search-API]

=== FHIR-Dirctory Owner-API

=== ContactManagement-API

=== Org-Admin

=== TestDriver-API

== Messenger-Service

=== Matrix Client-Server-API

=== Matrix Server-Server-API

=== ContactManagement-API

== RegistrationService

=== ProviderServices-API

== Push-Gateway


== License
Copyright (c) 2022 gematik GmbH

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-test, bitte ablehnen
