= api-ti-messenger
gematik, Systems Engineering
:source-highlighter: rouge
:title-page:
:imagesdir: /images/
ifdef::env-github[]
:toc: preamble
endif::[]
ifndef::env-github[]
:toc: left
endif::[]
:toclevels: 3
:toc-title: Inhaltsverzeichnis
// ifndef::env-github[]
//image::gematik_logo.svg[gematik,float="right"]
// endif::[]
// ifdef::env-github[]
// ++++
// <img align="right" role="right" src="images/gematik_logo.svg?raw=true"/>
// ++++
// endif::[]

image::gematik_logo.svg[gematik,width="70%"]

image:https://img.shields.io/badge/gemSpec TI&hyphen;Messenger&hyphen;Client-v1.1.0-blue[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-Client_V1.1.0.pdf"]
image:https://img.shields.io/badge/gemSpec TI&hyphen;Messenger&hyphen;FD-v1.1.0-blue[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-FD_V1.1.0.pdf"]
image:https://img.shields.io/badge/gemSpec TI&hyphen;Messenger&hyphen;Dienst-v1.1.0-blue[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-Dienst_V1.1.0.pdf"]

== Introduction

Der TI-Messenger ermöglicht sicheres und interoperable Instant Messaging im Gesundheitswesen.
Im Gesundheitswesen spielt das Konzept der digitalen Ad-hoc-Kommunikation eine immer wichtigere Rolle. Allerdings stoßen die Nutzer derzeit auf verschiedene Hürden, darunter:

- fehlende Interoperabilität zwischen den Messenger-Anbietern,
- fehlende einheitliche Zertifizierung zur Gewährleistung der Sicherheit sowie
- fehlende einheitliche Vorgaben zur Authentisierung.

TI-Messenger hingegen werden auf Basis des Matrix-Protokolls, dem offenen Messenger-Standard der Matrix.org Foundation, neue Maßstäbe für die Kommunikation in Echtzeit setzen. Der neue Kommunikationsstandard der gematik gewährleistet:

- Interoperabilität - und somit den sektoren- und anbieterübergreifenden Austausch
- Integrität dank hohem Out-of-the-box-Sicherheitsniveau,
- Ende-zu-Ende-Verschlüsselung sowie
- Innovation durch fortlaufende Weiterentwicklung des Matrix-Protokolls.

== System overview

++++
<p align="left">
  <img width="100%" src=/images/Systemoverview.png>
</p>
++++

== Folder structure

    TI-Messenger-API
    ├─ github
	   │   └──── workflows
    ├─ src
    │   ├──── fhir
    │   ├──── openapi
    │   └──── plantuml
    ├── README.md
    └── ReleaseNotes.md


== TI-Messenger-Client

=== Matrix Client-Server-API

https://spec.matrix.org/v1.4/client-server-api/[The matrix.org Client-Server-API]

=== FHIR-Directory Search-API

xref:docs/FHIR-Directory-search-api.adoc[FHIR-Directory Search-API]

=== FHIR-Dirctory Owner-API

=== Org-Admin

=== TestDriver-API

https://github.com/gematik/api-ti-messenger/blob/develop/src/openapi/TiMessengerTestTreiber.yaml/[The gematik TestDriver-API]

== Messenger-Service

=== Matrix Client-Server-API

https://spec.matrix.org/v1.4/client-server-api/[The matrix.org Client-Server-API]

=== Matrix Server-Server-API

https://spec.matrix.org/v1.4/server-server-api/[The matrix.org Server-Server-API]

=== ContactManagement-API

https://github.com/gematik/api-ti-messenger/blob/develop/src/openapi/TiMessengerContactManagement.yaml/[The gematik ContactManagement-API]

== RegistrationService

=== ProviderServices-API

== Push-Gateway

=== Matrix Push-Gateway-API

https://spec.matrix.org/v1.4/push-gateway-api/[The matrix.org Push-Gateway-API]

== License
Copyright (c) 2022 gematik GmbH

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
