:imagesdir: /images/
= TI-Messenger Dokumentation

image::gematik_logo.svg[gematik,width="70%"]

image:https://img.shields.io/badge/Release%20Notes-v0.1-red?style=plastic&logo=github&logoColor=red[link="ReleaseNotes.md"] +
image:https://img.shields.io/badge/ContactManagement-v1.0.0-blue?style=plastic&logo=github&logoColor=blue[link=/src/openapi/TiMessengerContactManagement.yaml"]
image:https://img.shields.io/badge/TestTreiber-v0.2.0-blue?style=plastic&logo=github&logoColor=blue[link="/src/openapi/TiMessengerTestTreiber.yaml"] +
image:https://img.shields.io/badge/TI&hyphen;Messenger&hyphen;Dienst-v1.1.0-green?style=plastic&logo=github&logoColor=green[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-Dienst_V1.1.0.pdf"]
image:https://img.shields.io/badge/TI&hyphen;Messenger&hyphen;FD-v1.1.0-green?style=plastic&logo=github&logoColor=green[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-FD_V1.1.0.pdf"]
image:https://img.shields.io/badge/TI&hyphen;Messenger&hyphen;Client-v1.1.0-green?style=plastic&logo=github&logoColor=green[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-Client_V1.1.0.pdf"]



== General
The following documentation is based on the TI-Messenger v1.1 specification according to *[gemSpec_TI-Messenger-Dienst]. At this point, the components of the solution mentioned in the specification and their interfaces are presented and explained in order to provide manufacturers and providers with the best possible support. The range of functions of the TI Messenger in version 1.1 includes: +

* the real-time communication between practitioners and practitioner institutions and
* real-time communication directly between practitioners.

_Notice: With TI Messenger version v1.1 no insured persons can participate in the TI-Messenger service_

== System Overview
The following picture gives an overview of the system architecture of the TI-Messenger in version 1.1. The IDP services that are also necessary for the operation of the TI-Messenger service are not considered here.

++++
<p align="left">
  <img width="100%" src=/images/System_overview.png>
</p>
++++

link:docs/TI-Messenger-Fachdienst.adoc[*TI-Messenger-Fachdienst*]

* *Registrierungs-Dienst:* +
The Registration-Dienst offers two abstract interfaces. The `I_Registration` interface is called by the registration service frontend to authenticate an organization to the Registration-Dienst and to administrate Messenger-Services. The `I_internVerfification` interface is called by the Messenger-Proxies to retrieve the federation list and to check for existing VZD-FHIR entries of the actors involved in an intended communication.

* *Messenger-Service:* +
A Messenger-Service consists of the sub-components Messenger-Proxy and a Matrix Homeserver. The sub-component  Matrix-Homeserver is based on the open communication protocol Matrix and offers the `Matrix-Client-Server API` and the `Matrix-Server-Server API`. Communication with a Matrix home server is always routed via the Messenger-Proxy, provided the authorization check was successful. This provides the interface `I_TiMessengerContactManagement` to enable the administration of an actor's release list (Freigabeliste).

* *Push-Gateway:* +
The Push-Gateway provides the `Matrix-Push Gateway API` according to the Matrix specification. This enables notifications to be forwarded to actors in the TI Messenger Service.

link:docs/TI-Messenger-Fachdienst.adoc[*TI-Messenger-Client*] +

* The TI-Messenger-Client is based on the `Matrix-Client-Server API`. It is expanded by further functional features and calls up the interfaces on the TI-Messenger-Fachdienst and on the VZD FHIR directory.

link:docs/TI-Messenger-Fachdienst.adoc[*VZD-FHIR-Directory*] +

* The VZD-FHIR-Directory is a central TI directory service that enables organizations and actors in the TI-Messenger-Service to be searched throughout Germany. The VZD-FHIR-Directory is based on the FHIR standard and offers relevant interfaces for the TI Messenger service. The `I_VZD_TiMessenger_services` interface is called by the Registrierungs-Dienst to download a federation list. The interfaces `tim-authenticate` and `owner-authenticate` are called by the TI messenger clients to enable a search or to make an entry in the VZD-FHIR directory.

== Folder structure
The organization of the folder structure is shown below.

----
TI-Messenger Dokumentation
├─ github
│   └──── workflows
├─ docs
├─ images
├─ src
│   ├──── fhir
│   │    ├── fsh-generated
│   │    ├── input
│   │    ├── output
│   │    ├── temp
│   │    └── template
│   ├──── openapi
│   │    ├── TiMessengerContactManagement.yaml
│   │    └── TiMessengerTestTreiber.yaml 
│   ├──── plantuml
│   │    ├── TI-Messenger-Dienst
│   │    ├── architecture
│   │    └── includes 
│   └──── schema
│        └── Attachment_schema.json
├── README.adoc
└── ReleaseNotes.md
----

== Referenced documents
The table below contains the gematik documents on the telematics infrastructure referenced in this online documentation. The version number valid for this document can be found in the current document map published on the gematik website, in which the present version is listed.

|===
|[Source] |Editor: Title

|*[gemSpec_TI-Messenger-Dienst]* |gematik: Spezifikation TI-Messenger-Dienst
|*[gemSpec_TI-Messenger-FD]* |gematik: Spezifikation TI-Messenger-Fachdienst
|*[gemSpec_TI-Messenger-Client]* |gematik: Spezifikation TI-Messenger-Client
|*[gemSpec_VZD_FHIR_Directory]* |gematik: Spezifikation Verzeichnisdienst FHIR-Directory
|===

== Additional pages
*Use cases* +
link:docs/Anwendungsfaelle.adoc[- Anwendungsfälle] 

*Product types* +
link:docs/KIM_API.adoc[- TI-Messenger-Fachdienst] +
link:docs/Fachdienst.adoc[- TI-Messenger-Client] +
link:docs/Verzeichnisdienst.adoc[- VZD-FHIR-Directory]

*Primary system manufacturer Guideline* +
link:docs/Primaersystem.adoc[- Primärsystem] 

*Miscellaneous* +
link:docs/Authentisierung.adoc[- Authentisierung] +
link:docs/faq.adoc[- Questions and answers on the current specification &#91;FAQ&#93;]

*Reference implementations* +
https://github.com/gematik/kim-attachment-service[-] +

== License
Copyright (c) 2022 gematik GmbH

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
