= api-ti-messenger
gematik, Systems Engineering
:source-highlighter: rouge
:title-page:
:imagesdir: /images/
ifdef::env-github[]
:toc: preamble
endif::[]
ifndef::env-github[]
:toc: left
endif::[]
:toclevels: 3
:toc-title: Inhaltsverzeichnis
// ifndef::env-github[]
//image::gematik_logo.svg[gematik,float="right"]
// endif::[]
// ifdef::env-github[]
// ++++
// <img align="right" role="right" src="images/gematik_logo.svg?raw=true"/>
// ++++
// endif::[]

image::gematik_logo.svg[gematik,float="right"]

image:https://img.shields.io/badge/gemSpec__TI--Messenger--Client-v1.1.0-blue[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-Client_V1.1.0.pdf"]
image:https://img.shields.io/badge/gemSpec__TI--Messenger--FD-v1.1.0-blue[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_TI-Messenger-FD_V1.1.0.pdf"]

== Introduction

Der TI-Messenger ermöglicht sicheres und interoperable Instant Messaging im Gesundheitswesen.
Im Gesundheitswesen spielt das Konzept der digitalen Ad-hoc-Kommunikation eine immer wichtigere Rolle. Allerdings stoßen die Nutzer derzeit auf verschiedene Hürden, darunter:

- fehlende Interoperabilität zwischen den Messenger-Anbietern,
- fehlende einheitliche Zertifizierung zur Gewährleistung der Sicherheit sowie
- fehlende einheitliche Vorgaben zur Authentisierung.

TI-Messenger hingegen werden auf Basis des Matrix-Protokolls, dem offenen Messenger-Standard der Matrix.org Foundation, neue Maßstäbe für die Kommunikation in Echtzeit setzen. Der neue Kommunikationsstandard der gematik gewährleistet:

- Interoperabilität - und somit den sektoren- und anbieterübergreifenden Austausch
- Integrität dank hohem Out-of-the-box-Sicherheitsniveau,
- Ende-zu-Ende-Verschlüsselung sowie
- Innovation durch fortlaufende Weiterentwicklung des Matrix-Protokolls.

== TI-Messenger-Client

=== Matrix Client-Server-API

https://spec.matrix.org/v1.4/client-server-api/[The matrix.org Client-Server-API]

=== FHIR-Directory Search-API

=== FHIR-Dirctory Owner-API

=== ContactManagement-API

=== Org-Admin

=== TestDriver-API

== Messenger-Service

=== Matrix Client-Server-API

=== Matrix Server-Server-API

=== ContactManagement-API

== RegistrationService

=== ProviderServices-API

== Push-Gateway

