ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../images
:docsdir: ../docs
:toc: macro
:toclevels: 5
:toc-title: Table of Contents
:numbered:

image:gematik_logo.svg[width=70%]

toc::[]

= Zentrale IDP-Dienst
== Überblick
Der zentrale *IDP-Dienst* ermöglicht die sichere Identifikation der Akteure anhand der ihnen bereitgestellten Identifikationsmittel einer Smartcard (SMC-B / HBA). Hierfür fasst der *IDP-Dienst*, die im AUT-Zertifikat befindlichen Attribute in signierten JSON Web Token (`ID_TOKEN`) zusammen und stellt diese der anfragenden *Relying Party* aus.

Im Rahmen des *TI-Messenger-Dienstes* werden die folgenden Endpunkte am *zentralen IDP-Dienst* verwendet:

* Discovery-Endpunkt
* Authorization-Endpunkt
* Token-Endpunkt

== Discovery-Endpunkt
Der Discovery Endpunkt stellt ein Base64 codiertes Discovery Dokument bereit, welches unter folgenden URL der jeweiligen Umgebung aufrufbar: 

* RU: https://idp-ref.app.ti-dienste.de/.well-known/openid-configuration 
* PU: https://idp.app.ti-dienste.de/.well-known/openid-configuration 

Das Discovery Dokument ist ein gemäß OpenID-Connect Metadatendokument, das den Großteil der Informationen enthält, die für eine Anwendung zum Durchführen einer Anmeldung erforderlich sind. Hierzu gehören Informationen wie z. B. die zu verwendenden Schnittstellen und der Speicherort der öffentlichen Signaturschlüssel des *IDP-Dienstes*.

CAUTION: Das Discovery Document wird alle 24 Stunden oder nach durchgeführten Änderungen umgehend neu erstellt. Dieses ist mit dem `PrK_DISC_SIG` des *IDP-Dienstes* signiert.

=== Aufbau des Discovery Dokumentes
Die folgende Tabelle enthält die Attribute und deren Beschreibung des Discovery Dokumentes

[options="header"]
|==================================================================================================================================================================================================================================
| Wert                                    | Beschreibung                                                                                                                                                                           
| `issuer`                                | hier ist der IdP-Dienst erreichbar                                                                                                                                                     
| `jwks_uri`                              | für den Abruf von `PUK_IDP_ENC` sowie des öffentlichen Schlüssels und des Zertifikats von `PUK_IDP_SIG` identifiziert anhand der `kid`-Parameter (`puk_idp_enc` / `puk_idp_sig`)
| `uri_disc`                              | URI, unter welcher das Discovery Document bereitgestellt wird                                                                                                                          
| `authorization_endpoint`                | URI des Dienstes und des öffentlichen Verschlüsselungsschlüssels des Authorization-Endpunktes                                                                                          
| `sso_endpoint`                          | URI des Authorization-Endpunktes für Requests mit SSO-Token                                                                                                                            
| `auth_pair_endpoint`                    | URI des Authorization-Endpunktes für Requests mit Pairing-Daten                                                                                                                        
| `token_endpoint`                        | URI des Token-Endpunktes                                                                                                                                                               
| `uri_puk_idp_enc` `uri_puk_idp_sig` | URI der JWK Objekte für die zwei Schlüssel und des Zertifikates                                                                                                                        
|==================================================================================================================================================================================================================================

=== Schlüsselmaterial des IDP-Dienstes
Die folgende Tabelle enthält die Abkürzungen für die öffentliche Schlüssel des IDP-Dienstes und deren Verwendung.

[options="header"]
|========================================================================================================================================================================
| Schlüssel    | Beschreibung        

| `PuK_DISC_SIG` | Wird für die Signaturprüfung des Discovery Document benötigt.  

| `PuK_IDP_SIG`  | Wird für die Signaturprüfung des `CHALLENGE_TOKEN`, des `AUTHORIZATION_CODE` und des `ID_TOKEN` benötigt. 

| `PuK_IDP_ENC`  | Wird für die Verschlüsselung der signierten Challenge durch das Authenticator-Modul und für die Verschlüsselung des `KEY_VERIFIER` durch den Relying Party benötigt.
|========================================================================================================================================================================

== Authorization Endpunkt
Der Authorization-Endpunkt erzeugt eine Authentication Challenge (`CHALLENGE_TOKEN`) - die auf Clientseite signiert wird - anhand der in der Authorization Request URL des Authenticator mitgelieferten Daten (`code_challenge` und `scope`). Hierfür prüft der *IDP-Dienst* die bei der organisatorischen Registrierung der Anwendung hinterlegten `redirect_uri` der *Relying Party* mit der `redirect_uri` aus der Authorization Request URI. Stimmen diese nicht überein, werden keine Token ausgestellt und die weitere Verarbeitung mit einem Fehler Response abgebrochen. Darüberhinaus prüft der *IDP-Dienst* ob die in der Authorization Request URI enthaltene `client_id` und `scope` bekannt und in dieser Kombination zulässig sind. Bei erfolg wird das `CHALLENGE_TOKEN` an dem Authenticator zur Signierung übermittelt. 

Auf der Clientseite wird der vom *IDP-Dienst* ausgestellte `CHALLENGE_TOKEN` unter Verwendung des `C.HCI.AUT` oder `C.HP.AUT`-Zertifikates am Konnektor signiert. Anschließend wird der `CHALLENGE_TOKEN` unter Verwendung des öffentlichen Schlüssels `PuK_IDP_ENC` des *IDP-Dienstes* verschlüsselt. Nach der erfolgreicher Verschlüsselung wird das signierte `CHALLENGE_TOKEN` mit das mitgelieferte Zertifikat der Smartcard (`C.HCI.AUT` oder `C.HP.AUT`) an den Authorization-Endpunkt übermittelt. 

Der *IDP-Dienst* entschlüsselt unter Verwendung seines privaten `PuK_IDP_ENC`-Schlüssels das übertragene `CHALLENGE_TOKEN`. Anschließend 
prüft der *IDP-Dienst* die Signatur des `CHALLENGE_TOKEN` und das mitgelieferte Zertifikat der Smartcard mittels OCSP/TSL der PKI der Telematikinfrastruktur. Sind alle im Claim geforderten Attribute vorhanden und die Gültigkeit der Attribute geprüft, erstellt der Authorization-Endpunkt einen `AUTHORIZATION_CODE` signiert diesen mit dem Schlüssel `PuK_IDP_SIG` und erschlüsselt diesen mit eigenem Schlüsselmaterial und 
sendet diesen an den Authenticator des anfragenden Client.


== Token-Endpunk
Das Anwendungsfrontend reicht den AUTHORIZATION_CODE zusammen mit dem CODE_VERIFIER beim Token-Endpunkt ein.

Die Token werden am Token-Endpunkt zum Download bereitgestellt, wo das jeweilige Anwendungsfrontend diese gegen gleichzeitige Vorlage von AUTHORIZATION_CODE und des eigenen code_verifier, auf welchem der bereits vorliegende Hash-Wert beruht, erhält.

Der Token-Endpunkt des IDP-Dienstes nimmt die Anfrage des Anwendungsfrontends bzw. Fachdienstes entgegen und prüft neben deren Integrität, ob der eingereichte CODE_VERIFIER bei Nutzung des Hash-Verfahrens S256 (nach [RFC7636 # section-4.2]) zum bitgleichen Hash-Wert führt. Stimmt der Hash-Wert aus dem initialen Aufruf des Authenticator-Moduls - die CODE_CHALLENGE - mit dem gebildeten Hash-Wert überein, ist sichergestellt, dass Aufrufer und Initiator identisch sind. Der Token-Endpunkt gibt daraufhin das ID_TOKEN / ACCESS_TOKEN an das anfragende System heraus.

Am Token-Endpunkt nimmt der Authorization-Server den AUTHORIZATION_CODE, welchen er selbst am Authorization-Endpunkt ausgegeben hat, entgegen. Da beide vom Authorization-Server selbst erstellt wurden, ist deren Prüfung auf Integrität keine besondere Herausforderung. Allerdings muss der Token-Endpunkt beim Einreichen eines AUTHORIZATION_CODE das dabei mit übertragene CODE_VERIFIER verarbeiten, um mittels Vergleich der Hash-Werte die Übereinstimmung des den AUTHORIZATION_CODE einreichenden mit dem ursprünglich authentisierten Client sicherzustellen. Das verwendete Hash-Verfahren ist im Authorization Request anzugeben.

TIP: Der Token-Endpunkt DARF ID_TOKEN mit einer Gültigkeitsdauer von mehr als 86400 Sekunden (24 Stunden) NICHT ausstellen.

Der Token-Endpunkt MUSS den vom Anwendungsfrontend übertragenen AUTHORIZATION_CODE und den KEY_VERIFIER des Anwendungsfrontend annehmen. Der AUTHORIZATION_CODE ist dabei mittels eines durch den IDP-Dienst für Authorization-Endpunkt und Token-Endpunkt definierten Verfahren zu entschlüsseln. 

Der Token-Endpunkt MUSS die Signatur des AUTHORIZATION_CODE unter Verwendung des Schlüssels PuK_IDP_SIG prüfen.

Der Token-Endpunkt MUSS den CODE_VERIFIER aus dem mittels PuK_IDP_ENC verschlüsselten KEY_VERIFIER extrahieren und die Überprüfung gegen die CODE_CHALLENGE mit S256 (Algorithmus nach [RFC7636 # section-4.2]) durchführen.

Der Token-Endpunkt MUSS den "Token-Key" aus dem mittels PuK_IDP_ENC verschlüsselten KEY_VERIFIER extrahieren.

Der Token-Endpunkt MUSS benötigte Attribute in Claims für das auszustellende ACCESS_TOKEN und das ID_TOKEN ausschließlich aus dem ihm mit dem signierten CHALLENGE_TOKEN eingereichten Authentifizierungszertifikat der Smartcard (eGK, HBA oder SMC-B) beziehen. Der Claim amr MUSS entsprechend des ursprünglich zur Authentisierung verwendeten Authentisierungsmittels belegt werden.
Der Token-Endpunkt MUSS das Attribut given_name und family_name der juristischen und natürlichen Personen sowie die Attribute organizationName,professionOID und idNummer entsprechend dem Datenformat der Informationsquelle (Zertifikat) wie folgt befüllen:

Der Token-Endpunkt MUSS alle erstellten ID_TOKEN und ACCESS_TOKEN, um deren Integrität sicherzustellen und eine eineindeutige Erklärung über deren Herkunft abzugeben, mit seinem privaten Schlüssel PrK_IDP_SIG signieren. [RFC7523 # section-3  Spiegelpunkt 9] ist zu gewährleisten. Als Algorithmus ist dementsprechend "BP256R1" zu wählen.

== Anfrage des ID_TOKEN
Der Request wird hierbei vom Registrierungs-Dienst oder Auth-Service generiert. Die Adressierung des IDP-Dienstes ist als Parameter in einer Konfigurationsdatei oder direkt im Quellcode hinterlegt.

Die Anfrage wird dann über das Authenticator-Modul an den Authorization-Endpunkt des IDP-Dienstes geleitet.

Inhalt der Anfrage ist: [gemF_eRp_Fed]

    die redirect_uri sowie der Scope (Attributsumfang) der Anfrage,
    Die client_id als Identifikation des Anfragenden Systems
    die eigene Hersteller-ID, Programmkürzel und Versionsnummer,
    der über den eigenen CODE_VERIFIER [RFC7636 # section-4.1] gebildete Hash code_challenge [RFC7636 # section-4.2] mit Angabe des Algorithmus code_challenge_method [RFC7636 # section-4.3],
    der state-Parameter [RFC8252 # section-8.9] wird genutzt, um CSRF (Cross-Site-Request-Forgery) zu verhindern.
    der nonce-Parameter openid-connect-core#Authentication Request] kann zusätzlich genutzt werden um den Erhalt des korrekten ID_TOKEN zu verifizieren.

Das Anwendungsfrontend überträgt seinen Authorization Request inklusive der generierten Werte  CODE_CHALLENGE, State und Nonce gemäß [RFC8252 # Anhang B] an das Authenticator-Modul.

3. Das Authenticator-Modul überträgt den Authorization Request weiter an den Authorization-Endpunkt des IDP-Dienstes.







== Authorization Code Flow

=== AF_10103 - Authentisieren einer Organisation am TI-Messenger-Dienst
Registrierungs-Dienst 
++++
<p align="left">
  <img width="100%" src=../../images/diagrams/idp.svg>
</p>
++++

*Beschreibung:*
Für die Signatur der Challenge wird die Funktion "externalAuthenticate" des Konnektors verwendet,

=== AF_10058 - Akteur (User-HBA) im Verzeichnisdienst hinzufügen
Auth-Service


== Rollen

=== Relying Party 
Registrierungs-Dienst / Auth-Servie

Das Relying Party muss einen `CODE_VERIFIER` (Zufallswert) und hierüber einen Hash, die `CODE_CHALLENGE` mit dem Algorithmus S256 erzeugen.

== Registrierung
Vorbereitende Maßnahmen: Das Anwendungsfrontend und der Fachdienst haben sich im Zuge eines organisatorischen Prozesses beim IDP-Dienst registriert. Das Anwendungsfrontend und das Authenticator-Modul haben das Discovery Dokument eingelesen und kennen damit die Uniform Resource Identifier (URI) und die öffentlichen Schlüssel der vom IDP-Dienst angebotenen Endpunkte. Der Fachdienst hat bei der Registrierung am IDP-Dienst seinen öffentlichen Schlüssel hinterlegt.


Die Registrierung des Anwendungsfrontends ist im Dokument *[gemSpec_IDP_Frontend]* beschrieben. Anbieter von Fachdiensten müssen ebenfalls die Registrierung ihres Fachdienstes über einen organisatorischen Prozess beim IDP-Dienst durchführen.

Ergänzung: Diese Registrierung erfolgt einmalig für die Anwendung bzw. den Dienst und muss bei Updates nicht wiederholt werden. Die Registrierung des Fachdienstes beinhaltet dabei auch die Abstimmung der Claims und die Gültigkeitsdauer der erstellten Token (siehe [gemSpec_IDP_FD#Kapitel 4]), wobei der Fachdienst seinen Bedarf an den gewünschten Attributen erklärt. Anpassungen an den Claims bedürfen einer erneuten Abstimmung und Registrierung.

Der Anbieter des IDP-Dienstes MUSS bei der organisatorischen Registrierung des Anwendungsfrontends diesem eine eindeutige client_id zur Nutzung des IDP-Dienstes zuweisen.

* Endpunkte: +
RU: https://idp-ref.app.ti-dienste.de +
PU: https://idp.app.ti-dienste.de/


Fachdienstbetreiber müssen ihren Authorization-Server beim Federation Master registrieren. Die Registrierung erfolgt als organisatorischer Prozess, bevor ein Fachdienst an den vom föderierten Identitätsmanagement (IDM) angebotenen Authentifizierungsprozessen teilnehmen kann. Erst nach erfolgter Registrierung, bei der die Adresse des Fachdienstes bzw. seines Authorization-Servers, seine öffentlichen Schlüssel sowie der verwendete scope angegeben wurden, können sektorale Identity Provider ID_TOKEN für den Fachdienst ausstellen.


= gematik Authenticator
Das Authenticator-Modul liefert die Daten zur Authentifizierung des Nutzers an den IDP-Dienst.

Hinweis: Der genaue Aufbau des vom Authenticator-Modul übertragenen, signierten CHALLENGE_TOKEN findet sich in [gemSpec_IDP_Dienst#Kapitel 7.3 Authentication Request].

