ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../images
:docsdir: ../docs
:toc: macro
:toclevels: 5
:toc-title: Table of Contents
:numbered:

image:gematik_logo.svg[width=70%]

toc::[]

= Zentrale IDP-Dienst
== Überblick
Der zentrale *IDP-Dienst* ermöglicht die sichere Identifikation der Akteure anhand der ihnen bereitgestellten Identifikationsmittel einer Smartcard (SMC-B / HBA). Hierfür fasst der *IDP-Dienst*, die im AUT-Zertifikat befindlichen Attribute in signierten JSON Web Token (`ID_TOKEN`) zusammen und stellt diese der anfragenden *Relying Party* aus.

Im Rahmen des *TI-Messenger-Dienstes* werden die folgenden Endpunkte am *zentralen IDP-Dienst* verwendet:

* Discovery-Endpunkt
* Authorization-Endpunkt
* Token-Endpunkt

== Discovery-Endpunkt
Der Discovery Endpunkt stellt ein Base64 codiertes Discovery Dokument bereit, welches unter folgenden URL der jeweiligen Umgebung aufrufbar: 

* RU: https://idp-ref.app.ti-dienste.de/.well-known/openid-configuration 
* PU: https://idp.app.ti-dienste.de/.well-known/openid-configuration 

Das Discovery Dokument ist ein gemäß OpenID-Connect Metadatendokument, das den Großteil der Informationen enthält, die für eine Anwendung zum Durchführen einer Anmeldung erforderlich sind. Hierzu gehören Informationen wie z. B. die zu verwendenden Schnittstellen und der Speicherort der öffentlichen Signaturschlüssel des *IDP-Dienstes*.

CAUTION: Das Discovery Document wird alle 24 Stunden oder nach durchgeführten Änderungen umgehend neu erstellt. Dieses ist mit dem `PrK_DISC_SIG` des *IDP-Dienstes* signiert.

=== Aufbau des Discovery Dokumentes
Die folgende Tabelle enthält die Attribute und deren Beschreibung des Discovery Dokumentes

[options="header"]
|==================================================================================================================================================================================================================================
| Wert                                    | Beschreibung                                                                                                                                                                           
| `issuer`                                | hier ist der IdP-Dienst erreichbar                                                                                                                                                     
| `jwks_uri`                              | für den Abruf von `PUK_IDP_ENC` sowie des öffentlichen Schlüssels und des Zertifikats von `PUK_IDP_SIG` identifiziert anhand der `kid`-Parameter (`puk_idp_enc` / `puk_idp_sig`)
| `uri_disc`                              | URI, unter welcher das Discovery Document bereitgestellt wird                                                                                                                          
| `authorization_endpoint`                | URI des Dienstes und des öffentlichen Verschlüsselungsschlüssels des Authorization-Endpunktes                                                                                          
| `sso_endpoint`                          | URI des Authorization-Endpunktes für Requests mit SSO-Token                                                                                                                            
| `auth_pair_endpoint`                    | URI des Authorization-Endpunktes für Requests mit Pairing-Daten                                                                                                                        
| `token_endpoint`                        | URI des Token-Endpunktes                                                                                                                                                               
| `uri_puk_idp_enc` `uri_puk_idp_sig` | URI der JWK Objekte für die zwei Schlüssel und des Zertifikates                                                                                                                        
|==================================================================================================================================================================================================================================

=== Schlüsselmaterial des IDP-Dienstes
Die folgende Tabelle enthält die Abkürzungen für die öffentliche Schlüssel des IDP-Dienstes und deren Verwendung.

[options="header"]
|========================================================================================================================================================================
| Schlüssel    | Beschreibung        

| `PuK_DISC_SIG` | Wird für die Signaturprüfung des Discovery Document benötigt.  

| `PuK_IDP_SIG`  | Wird für die Signaturprüfung des `CHALLENGE_TOKEN`, des `AUTHORIZATION_CODE` und des `ID_TOKEN` benötigt. 

| `PuK_IDP_ENC`  | Wird für die Verschlüsselung der signierten Challenge durch das Authenticator-Modul und für die Verschlüsselung des `KEY_VERIFIER` durch den Relying Party benötigt.
|========================================================================================================================================================================

TIP: In der oben gezeigten Tabelle sind nur die vom Hersteller eines *TI-Messenger-Clients* / *TI-Messenger-Fachdienstes* zu verwendenen Schlüssel gelistet

== Authorization Endpunkt
Der Authorization-Endpunkt erzeugt eine Authentication Challenge (`CHALLENGE_TOKEN`) - die auf Clientseite signiert wird - anhand der in der Authorization Request URL des Authenticator mitgelieferten Daten (`code_challenge` und `scope`). Hierfür prüft der *IDP-Dienst* die bei der organisatorischen Registrierung der Anwendung hinterlegten `redirect_uri` der *Relying Party* mit der `redirect_uri` aus der Authorization Request URI. Stimmen diese nicht überein, werden keine Token ausgestellt und die weitere Verarbeitung mit einem Fehler Response abgebrochen. Darüberhinaus prüft der *IDP-Dienst* ob die in der Authorization Request URI enthaltene `client_id` und `scope` bekannt und in dieser Kombination zulässig sind. Bei erfolg wird das `CHALLENGE_TOKEN` an dem Authenticator zur Signierung übermittelt. 

Auf der Clientseite wird der vom *IDP-Dienst* ausgestellte `CHALLENGE_TOKEN` unter Verwendung des `C.HCI.AUT` oder `C.HP.AUT`-Zertifikates am Konnektor signiert. Anschließend wird der `CHALLENGE_TOKEN` unter Verwendung des öffentlichen Schlüssels `PuK_IDP_ENC` des *IDP-Dienstes* verschlüsselt. Nach der erfolgreicher Verschlüsselung wird das signierte `CHALLENGE_TOKEN` mit das mitgelieferte Zertifikat der Smartcard (`C.HCI.AUT` oder `C.HP.AUT`) an den Authorization-Endpunkt übermittelt. 

Der *IDP-Dienst* entschlüsselt unter Verwendung seines privaten `PuK_IDP_ENC`-Schlüssels das übertragene `CHALLENGE_TOKEN`. Anschließend 
prüft der *IDP-Dienst* die Signatur des `CHALLENGE_TOKEN` und das mitgelieferte Zertifikat der Smartcard mittels OCSP/TSL der PKI der Telematikinfrastruktur. Sind alle im Claim geforderten Attribute vorhanden und die Gültigkeit der Attribute geprüft, erstellt der Authorization-Endpunkt einen `AUTHORIZATION_CODE` signiert diesen mit dem Schlüssel `PuK_IDP_SIG` und verschlüsselt diesen mit eigenem Schlüsselmaterial. Anschließend wird der `AUTHORIZATION_CODE` und die vom Client aufzurufende `redirect_url` vom *Reyling Party* an den Authenticator des anfragenden Client übermittelt. 

== Token-Endpunkt
CAUTION: Im folgenden wird davon ausgegangen, dass der Client die `redirect_url` vom *Reyling Party* aufruft.

Die *Relying Party* erzeugt einen AES256 `Token-Key`, verknüpft diesen mit dem `CODE_VERFIER` zum `KEY_VERIFIER` und sendet diesen verschlüsselt unter Nutzung des öffentlichen Schlüssels `PUK_IDP_ENC`zusammen mit dem `AUTHORIZATION_CODE` zum Token-Endpunkt des *IDP-Dienstes*.

Am *IDP-Dienst* wird der `AUTHORIZATION_CODE` mit dem zuvor im Kapitel Authorization Endpunkt beschriebenen erzeugten eigenem Schlüsselmaterial entschlüsselt. Anschließend prüft der *IDP-Dienst* die Signatur des `AUTHORIZATION_CODE` unter Verwendung des Schlüssels `PuK_IDP_SIG`. Als nächstes extrahiert der *IDP-Dienst* den `CODE_VERIFIER` aus dem mittels `PuK_IDP_ENC` verschlüsselten `KEY_VERIFIER` und prüft diesen gegen die `CODE_CHALLENGE`. Das bedeutet, dass der eingereichte `CODE_VERIFIER` bei Nutzung des Hash-Verfahrens S256 zum bitgleichen Hash-Wert führt. Stimmt der Hash-Wert aus dem initialen Aufruf des Authenticator - die `CODE_CHALLENGE` - mit dem gebildeten Hash-Wert überein, ist sichergestellt, dass dieser und der initialer Aufruf von der *Relying Party* initiiert wurden. 

Daraufhin extrahiert der *IDP-Dienst* die aus dem eingereichten Authentifizierungszertifikat der Smartcard (AUT-Zertifikat) enthaltenen Attribute in ein JSON WEB TOKEN (`ID_TOKEN`). Um die Integrität des `ID_TOKENS` sicherzustellen und eine eineindeutige Erklärung über die Herkunft des Tokens abzugeben, wird dies mit dem privaten Schlüssel `PrK_IDP_SIG` signiert. Abschließend verschlüsselt der *IDP-Dienst* das `ID_TOKEN` mit den von der *Relying Party* übermittelten `Token_Key` und sendet dieses verschlüsselt an die *Relying Party* zurück. 

TIP: Der Token-Endpunkt DARF `ID_TOKEN` mit einer Gültigkeitsdauer von mehr als 86400 Sekunden (24 Stunden) NICHT ausstellen.

== Aufbau der Authorization Request URI
Die Authorization Request URI wird von der *Relying Party* generiert, um beim *IDP-Dienst* sich ein `ID_TOKEN` ausstellen zu lassen. 

*Beispiel eines Authorization Requests:*
[source,text]
----
https://idp-ref.app.ti-dienste.de/auth? 
client_id=GEMgematAut5zGBeGaqR&
response_type=code&
redirect_uri=https%3A%2F%2Fgstopdh4.top.local%3A8090%2Fcallback&
state=f1bQrZ4SEsiKCRV4VNqG&
code_challenge=JvcJb54WkEm38N3U1IYQsP2Lqvv4Nx23D2mU7QePWEw&
code_challenge_method=S256&
scope=openid ti-messenger&
nonce=MbwsuHIExDKyqKDKSsPp
----

[options="header"]
|=============================================================================================================================================================================================================================================================================================================
| Attribut              | Beschreibung                                                                                                                                                                                                                                                                        
| `client_id`             | Die `client_id` der *Relying Party*. Wird bei Registrierung beim IDP vergeben.                                                                                                                                                                                                                
| `response_type`         | Referenziert den erwarteten Response-Type des Flow
Muss immer 'code' lauten.
Damit wird angezeigt, dass es sich hierbei um einen Authorization Code Flow handelt.
Für eine nähere Erläuterung siehe OpenID-Spezifikation.                                                         
| `redirect_uri`          | Die URL wird vom *Relying Party* beim Registrierungsprozess im *IDP-Dienst* hinterlegt und leitet die Antwort des Servers an diese Adresse um.                                                                                                                                                           
| `state`                 | Der state der Session. Sollte dem zufällig generierten state-Wert aus der initialen Anfrage entsprechen.                                                                                                                                                                            
| `code_challenge`        | Der Hashwert des `Code-Verifiers` wird zum *IDP-Dienst* als `Code-Challenge` gesendet.                                                                                                                                                                                                           
| `code_challenge_method` | Der *Relying Party* generiert einen `Code-Verifier` und erzeugt darüber einen Hash im Verfahren SHA-256.                                                                                                                                         
| `scope`                 | Der `Scope` entspricht dem zwischen der *Relying Party* und dem *IDP-Dienst* festgelegten Wert.

Der Scope besteht grundsätzlich aus drei Paramete +

    `openid` +
    `ti-messenger`
| `nonce`                 | String zur Verhinderung von CSRF-Attacke
Dieser Wert ist optional. Wenn er mitgegeben wird muss der gleiche Wert im abschließend ausgegebenen `ID-Token` wieder auftauchen.                                                                                                         
|=============================================================================================================================================================================================================================================================================================================

Die Anfrage wird dann über das Authenticator-Modul an den Authorization-Endpunkt des IDP-Dienstes geleitet.

Das Anwendungsfrontend überträgt seinen Authorization Request inklusive der generierten Werte  CODE_CHALLENGE, State und Nonce gemäß [RFC8252 # Anhang B] an das Authenticator-Modul.

3. Das Authenticator-Modul überträgt den Authorization Request weiter an den Authorization-Endpunkt des IDP-Dienstes.







== Authorization Code Flow

=== AF_10103 - Authentisieren einer Organisation am TI-Messenger-Dienst
Registrierungs-Dienst 
++++
<p align="left">
  <img width="100%" src=../../images/diagrams/idp.svg>
</p>
++++

*Beschreibung:*
Für die Signatur der Challenge wird die Funktion "externalAuthenticate" des Konnektors verwendet,

=== AF_10058 - Akteur (User-HBA) im Verzeichnisdienst hinzufügen
Auth-Service


== Rollen

=== Relying Party 
Registrierungs-Dienst / Auth-Servie

Das Relying Party muss einen `CODE_VERIFIER` (Zufallswert) und hierüber einen Hash, die `CODE_CHALLENGE` mit dem Algorithmus S256 erzeugen.

== Registrierung
Vorbereitende Maßnahmen: Das Anwendungsfrontend und der Fachdienst haben sich im Zuge eines organisatorischen Prozesses beim IDP-Dienst registriert. Das Anwendungsfrontend und das Authenticator-Modul haben das Discovery Dokument eingelesen und kennen damit die Uniform Resource Identifier (URI) und die öffentlichen Schlüssel der vom IDP-Dienst angebotenen Endpunkte. Der Fachdienst hat bei der Registrierung am IDP-Dienst seinen öffentlichen Schlüssel hinterlegt.


Die Registrierung des Anwendungsfrontends ist im Dokument *[gemSpec_IDP_Frontend]* beschrieben. Anbieter von Fachdiensten müssen ebenfalls die Registrierung ihres Fachdienstes über einen organisatorischen Prozess beim IDP-Dienst durchführen.

Ergänzung: Diese Registrierung erfolgt einmalig für die Anwendung bzw. den Dienst und muss bei Updates nicht wiederholt werden. Die Registrierung des Fachdienstes beinhaltet dabei auch die Abstimmung der Claims und die Gültigkeitsdauer der erstellten Token (siehe [gemSpec_IDP_FD#Kapitel 4]), wobei der Fachdienst seinen Bedarf an den gewünschten Attributen erklärt. Anpassungen an den Claims bedürfen einer erneuten Abstimmung und Registrierung.

Der Anbieter des IDP-Dienstes MUSS bei der organisatorischen Registrierung des Anwendungsfrontends diesem eine eindeutige client_id zur Nutzung des IDP-Dienstes zuweisen.

* Endpunkte: +
RU: https://idp-ref.app.ti-dienste.de +
PU: https://idp.app.ti-dienste.de/


Fachdienstbetreiber müssen ihren Authorization-Server beim Federation Master registrieren. Die Registrierung erfolgt als organisatorischer Prozess, bevor ein Fachdienst an den vom föderierten Identitätsmanagement (IDM) angebotenen Authentifizierungsprozessen teilnehmen kann. Erst nach erfolgter Registrierung, bei der die Adresse des Fachdienstes bzw. seines Authorization-Servers, seine öffentlichen Schlüssel sowie der verwendete scope angegeben wurden, können sektorale Identity Provider ID_TOKEN für den Fachdienst ausstellen.


= gematik Authenticator
Das Authenticator-Modul liefert die Daten zur Authentifizierung des Nutzers an den IDP-Dienst.

Hinweis: Der genaue Aufbau des vom Authenticator-Modul übertragenen, signierten CHALLENGE_TOKEN findet sich in [gemSpec_IDP_Dienst#Kapitel 7.3 Authentication Request].

