ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images
:toc: macro
:toclevels: 5
:toc-title: Inhaltsverzeichnis
:numbered:

image:gematik_logo.svg[width=70%]

toc::[]
= TI-Messenger-Fachdienst
== Überblick
Die folgende Seite gibt Implementierungshinweise für die Entwicklung eines eigenen _TI-Messenger-Fachdienstes_.

TIP: Die Seite ergänzt die *[gemSpec_TI-Messenger-FD]* Spezifikation, die als Grundlage für das Verständnis vorrausgesetzt wird. 

Der _TI-Messenger-Fachdienst_ besteht aus unterschiedlichen Teilkomponenten und Schnittstellen. Die nachfolge Abbildung verdeutlicht den Zusammenhang zwischen den Komponenten und den Kommunikationsschnittstellen. 

++++
<p align="left">
  <img width="100%" src=../../images/I_Fachdienst.png>
</p>
++++

Der _TI-Messenger-Fachdienst_ besteht aus den folgenden Teilkomponenten :  

* link:Registrierungsdienst.adoc[Registrierungs-Dienst], 

* link:Messengerservice.adoc[Messenger-Service] 

NOTE: Die Teilkomponente _Push-Gateway_ ist nach der  Matrix Spezifikation https://spec.matrix.org/latest/push-gateway-api/[&#91;Push Gateway API&#93;] zu implementieren und wird deshalb in dieser Implementierungshilfe nicht detaillierter beschrieben.

== Vorraussetzungen 
=== TI-ITSM Portal
==== Zugang zum TI-ITSM Portal
Die gematik stellt ein TI-IT Service Management (TI-ITSM) Portal zur Verfügung. Über das TI-ITSM Portal ist es möglich, Service-Requests für Anbieter eines *TI-Messenger-Fachdienstes* zu stellen. Dies ist im Kontext des *TI-Mesenger-Dienstes* für die folgenden Punkte notwendig:

CAUTION: Voraussetzungen für die Nutzung des von der gematik bereitgestellten *Authenticators* sind: +
- für den Zugang zum PKI-Management-System (PMS), +
- Erstellung des Signaturzertifikates für den Anbeiter des *TI-Messenger-Fachdienstes*, +
- für die Beantragung der `TI-Provider-Credentials` für die Anbieterschnittstelle des VZD-FHIR-Directory und +
- die Registrierung des *Registrierungs-Dienstes* beim zentralen *IDP-Dienst* der gematik. 

Hierfür ist es erforderlich, dass sich ein Anbieter eines *TI-Messenger-Fachdienstes* beim TI-ITSM registriert. Weitere Information sind im https://gematikde.sharepoint.com/:w:/s/PTNeo/EczX7AFGfBdNrCYghzGsHz4BbSoYhV63QMmDCdz7x9zLpg?e=7wG3c[Welcome Package] Schritt 4 zu finden. 

Das TI-ITSM-Portal ist unter der folgenden Interseite erreichbar:
* https://www.ti-itsm.de

==== Zugang zum PKI-Management-System (PMS)
Um das Signaturzertifikat (welches für die Signatur des `RegService-OpenID-Token` benötigt wird) abrufen zu können, müssen vorher ein Benutzeraccount und Berechtigungen über weitere Service-Requests für die Organisation und den Benutzer (nur Root-User) im TI-ITSM beantragt werden. Weitere Informationen sind im link:https://gematikde.sharepoint.com/:w:/s/PTNeo/EczX7AFGfBdNrCYghzGsHz4BbSoYhV63QMmDCdz7x9zLpg?e=7wG3c[Welcome Package] Schritt 6 zu entnehmen. 

Zugang zum PMS
* RU/TU: https://www-testref.tms.ti-dienste.de
* PU: https://auth.ti-dienste.de/my.policy

==== Erstellung des Signaturzertifikates für den Anbeiter
Für die Signierung eines `RegService-OpenID-Token` durch den *Registrierungs-Dienst* eines *TI-Messnger-Fachdienstes* wird ein Signaturzertifikat der PKI der Telematikinfrastruktur benötigt. Das Zertifikat muss den Typ `C.FD.SIG` und die technische Rolle `oid_tim` haben. Die Beantragung des Signaturzertifikates erfolg über das TI-ITSM Portal und ist anschließend über das PMS abrufbar (siehe hierzu https://gematikde.sharepoint.com/:w:/s/PTNeo/EczX7AFGfBdNrCYghzGsHz4BbSoYhV63QMmDCdz7x9zLpg?e=7wG3c[Welcome Package] Schritt 6)


==== Beantragung der TI-Provider-Credentials am VZD-FHIR-Directory
Initial muss der Anbieter eines *TI-Messenger-Fachdienstes* `TI-Provider-Credentials` für den Zugriff auf die Schnittstelle `/tim-provider-services` des *FHIR-Proxy* beantragen. Die TIM-Provider-Services-Zugangsdaten erhält der Anbieter über eine weitere Serviceanfrage im gematik TI-ITSM-Portal. Hierbei muss das Signaturzertifikat bei der Beantragung mit übergeben werden. Dadurch wird sichergestellt, dass nur registrierte Anbieter eines *TI-Messenger-Fachdienstes* `RegService-OpenID-Token` an der `/owner-authenticate`-Schnittstelle des *Auth-Service* des *VZD-FHIR-Directory* gegen ein `owner-accesstoken` eintauschen können.

=== Bekanntmachung des Registrierungs-Dienstes am zentralen IDP-Dienst

Es besteht bereits eine abgeschlossene Scope-Registrierung am zentralen *IDP-Dienst* für den *TI-Messenger-Dienst*. Daher ist es nur erforderlich ber der gematik eine `client_id` für den *Registrierungs-Dienst* zu beantragen. Hierfür benötigt die gematik im Registrierungsformular die `redirect_uri` des *Registrierungs-Dienstes*, die zu der `client_id` registriert wird. Das Registrierungsformular kann unter idp-registrierung@gematik.de angefragt werden. Nach der Registrierung erhält der Anbieter die registrierte `client_id` sowie den Download-Endpunkt des Discovery Documentes des zentralen *IDP-Dienst*. Weitere Informationen sind im https://gematikde.sharepoint.com/:w:/s/PTNeo/EczX7AFGfBdNrCYghzGsHz4BbSoYhV63QMmDCdz7x9zLpg?e=7wG3c[Welcome Package] Schritt 5 zu finden. 


