@startuml
title FHIR Questionnaire Statusabfrage über Matrix

' Moderneres Design
skinparam Style strictuml
skinparam Shadowing true
skinparam RoundCorner 8
hide footbox
skinparam ArrowColor #3B82F6
skinparam ParticipantBackgroundColor #EAF2FF
skinparam ParticipantBorderColor #3B82F6
skinparam ParticipantFontColor #0F172A
skinparam LifeLineBackgroundColor #F8FAFC
skinparam LifeLineBorderColor #94A3B8
skinparam SequenceMessageAlign center

' Farben für B1/B2
' B1 (grün):  #86EFAC
' B2 (violett): #C4B5FD

autonumber
participant "Dr. Sabine Schröder (Client A)" as A
participant "Matrix-Raum" as HS
participant "Erika Mustermann (iPhone B1)" as B1 #86EFAC
participant "Erika Mustermann (iPad B2)" as B2 #C4B5FD
actor "Erika Mustermann" as EM
!$phaseCounter  = 1

== Phase $phaseCounter – Dr. Schröder möchte feststellen, ob Erika Mustermann einen TI-M Client nutzt, \n der ISiK-Formulate in einer bestimmten Version unterstützt und sendet eine Abfrage in den Raum. ==
A -> HS : m.room.encrypted ($1)
note over A, HS
{ "type": "de.gematik.msc4301.request.event_capability",
  "event_id": "$1",
  "content": {
    "de.gematik.msc4300.request.status": {
      "from_device": "RJYKSTBOIE",
      "lifetime": 90000, // 90s
    },
    "de.gematik.msc4301.request.event_capability": {
      "events": [
        {
          "type": "de.gematik.msc4302.fhir",
          "content": [{
            "key": "de\.gematik\.msc4302\.fhir\.structure_definition.url",
            "value": "https://gematik.de/fhir/isik/StructureDefinition/ISiKFormularDefinition"
          }, {
            "key": "de\.gematik\.msc4302\.fhir\.structure_definition.version",
            "value": "5.0.0"
          }]}]}}
}
end note
HS -> B1 : Event $1
HS -> B2 : Event $1

!$phaseCounter=$phaseCounter + 1
== Phase $phaseCounter a) – Der TI-M Client auf Frau Mustermanns iPhone unterstützt das angefragte FHIR-Profil nicht\n und sendet ein leeres events Array zurück. ==
' Antwort von B1 farbig (grün)
B1 -[#86EFAC]> HS : m.room.encrypted (ref $1)
note over B1, HS #86EFAC
{   "type": "de.gematik.msc4300.response.status",
    "content": {
      "m.response.status": {
        "from_device": "EIOBTSKYJR",
        "status": "success",
        "messages": [{
          "type": "info",
          "m.text": [{ "body": "Unknown structure definition
           https://gematik.de/fhir/isik/StructureDefinition/ISiKFormularDefinition" }]
        }]},
      "m.relates_to": {
        "event_id": "$1",
        "rel_type": "m.reference",
      },
      "de.gematik.msc4301.response.event_capability": {
        "events": []
      }}}
}
end note
HS -> A : Zustellung Status (B1)

== Phase $phaseCounter b) – Der TI-M Client auf Frau Mustermanns iPad unterstützt das angefragte FHIR-Profil\n und sendet es zur Bestätigung im events Array zurück.==
' Antwort von B2 farbig (violett)
B2 -[#C4B5FD]> HS : m.room.encrypted (ref $1)
note over B2, HS #C4B5FD
{ "type": "de.gematik.msc4300.response.status",
  "sender": "@I12345678:gematikerKK.de",
  "content": {
    "de.gematik.msc4300.response.status": {
      "from_device": "B2",
      "status": "success",
    },
    "m.relates_to": {
      "event_id": "$1",
      "rel_type": "m.reference",
    },
    "de.gematik.msc4301.event_capability": {
          "events": [
            {
              "type": "de.gematik.msc4302.fhir",
              "content": [{
                "key": "de\.gematik\.msc4302\.fhir\.structure_definition.url",
                "value": "https://gematik.de/fhir/isik/StructureDefinition/ISiKFormularDefinition"
              }, {
                "key": "de\.gematik\.msc4302\.fhir\.structure_definition.version",
                "value": "5.0.0"
              }]}]}}
}
end note
HS -> A : Zustellung Status (B2)

!$phaseCounter=$phaseCounter + 1
== Phase $phaseCounter – Dr. Schröder sendet das Formular, weil Client B2(das iPad) bestätigt hat die Version verarbeiten zu können.\n und fragt den Status ab. ==
A -> HS : m.room.encrypted ($2)
note over A, HS
{   "type": "de.gematik.msc4302.fhir",
    "content": {
     "de.gematik.msc4300.request.status": {
          "from_device": "RJYKSTBOIE",
          "lifetime": 90000, // 90s
        },
      "de.gematik.msc4302.fhir.structure_definition": {
        "url": "https://gematik.de/fhir/isik/StructureDefinition/ISiKFormularDefinition",
        "version": "5.0.0",
        "type": "Questionnaire",
        "fhir_version": "4.0.1",
      },
      "org.matrix.msc1767.file: {
        "url": "mxc://example.org/abcd1234",
        "mimetype": "application/fhir+json",
        // further properties as per MSC3551
    }}
}
end note
HS -> B1 : Event $2
HS -> B2 : Event $2

newpage

!$phaseCounter=$phaseCounter + 1
== Phase $phaseCounter a)– Der TI-M Client auf Frau Mustermanns iPhone unterstützt das übertragene FHIR-Profil nicht\n und sendet daher den Status error zurück.==
' Antwort von B1 farbig (grün)
B1 -[#86EFAC]> HS : m.room.encrypted (ref $2)
note over B1, HS #86EFAC
{
  {
    "type": "de.gematik.msc4300.response.status",
    "content": {
      "de.gematik.msc4300.response.status": {
        "from_device": "EIOBTSKYJR",
        "status": "error",
        "messages": [{
          "type": "info",
          "m.text": [{ "body": "Unknown structure definition
           https://gematik.de/fhir/isik/StructureDefinition/ISiKFormularDefinition" }]
        }]
      },
      "m.relates_to": {
        "event_id": "$2",
        "rel_type": "m.reference",
      }}}
}
end note
HS -> A : Zustellung Status (B1)

== Phase $phaseCounter b) – Der TI-M Client auf Frau Mustermanns iPad unterstützt das übertragene FHIR-Profil.\n Der Client validiert den Inhalt der Resource und sendet zur Bestätigung den Status success zurück.==
' Versand von B2 farbig (violett)
B2 -[#C4B5FD]> HS : m.room.encrypted (ref $2)
note over B2, HS #C4B5FD
 {  "type": "de.gematik.msc4300.response.status",
    "content": {
      "de.gematik.msc4300.response.status": {
        "from_device": "B2",
        "status": "success",
      },
      "m.relates_to": {
        "event_id": "$2",
        "rel_type": "m.reference",
      }}}
}
end note
HS -> A : Zustellung Status (B2)

!$phaseCounter=$phaseCounter + 1
== Phase $phaseCounter – Frau Mustermann öffnet den TI-M Client auf ihrem iPhone. ==
EM -> B1 : Öffnen des TI-M Clients auf dem iPhone
B1 -> EM : Sie haben ein neues Formular von Dr. Schröder erhalten. Bitte öffnen Sie dieses auf ihrem iPad.

!$phaseCounter=$phaseCounter + 1
== Phase $phaseCounter – Frau Mustermann öffnet den Raum im TI-M Client auf ihrem iPad \n und sendet das ausgefüllte Formular zurück. ==
EM -> B2 : Öffnen des TI-M Clients auf dem iPhone
B2 -> EM : Sie haben ein neues Formular von Dr. Schröder erhalten. Bitte füllen Sie dieses aus.
EM -> EM : Ausfüllen des Formulars auf dem iPad
EM -> B2 : Fertigstellen des Formulars im TI-M Client auf dem iPad

' Versand von B2 farbig (violett)
B2 -[#C4B5FD]> HS : m.room.encrypted
note over B2, HS #C4B5FD
{     "type": "de.gematik.msc4302.fhir",
      "content": {
        "de.gematik.msc4300.fhir.structure_definition": {
          "url": "https://gematik.de/fhir/isik/StructureDefinition/ISiKFormularDaten",
          "version": "5.0.0",
          "type": "QuestionnaireResponse",
          "fhir_version": "4.0.1",
        },
        "org.matrix.msc1767.file": {
          "url": "mxc://example.org/abcd1234",
          "mimetype": "application/fhir+json",
          // further properties as per MSC3551
      }}
     "m.relates_to": {
            "event_id": "$2",
            "rel_type": "m.reference",
          },
    "de.gematik.msc4300.request.status": {
      "from_device": "B2",
      "lifetime": 600_000, // 10min
    }}
}
end note
HS -> A : Event $3

!$phaseCounter=$phaseCounter + 1
== Phase $phaseCounter – Der TI-M Client auf Frau Mustermanns iPhone empfängt das Event.\nDa das Event vom selben Nutzer stammt, der im Client angemeldet ist, wird kein Verarbeitungsstatus zurück übermittelt. ==
HS -> B1 : Event $3

!$phaseCounter=$phaseCounter + 1
== Phase $phaseCounter – Der TI-M Client von Dr. Schröder empfängt das Event.\nDer Client extrahiert die enthaltene FHIR-Resource und übermittelt sie an Dr. Schröders PVS.\nAnschließend sendet der Client zur Bestätigung ein de.gematik.msc4300.response.status Event mit dem Status success zurück. ==
A -> HS : de.gematik.msc4300.response.status (ref $3)
note over A, HS
{ "type": "de.gematik.msc4300.response.status",
  "sender": "@dr.schroeder:praxis.de",
  "content": {
    "de.gematik.msc4300.response.status": {
      "from_device": "A",
      "status": "success",
    },
    "m.relates_to": {
      "event_id": "$3",
      "rel_type": "m.reference",
    }}
}
end note

!$phaseCounter=$phaseCounter + 1
== Phase $phaseCounter – Die TI-M Clients von Frau Mustermann empfangen das de.gematik.msc4300.response.status Event\n und zeigen eine Bestätigung über den erfolgreichen Versand des ausgefüllten Fragebogens an. ==
HS -> B1 : Zustellung Status (A)
HS -> B2 : Zustellung Status (A)
B1 -> EM : Ihr ausgefülltes Formular wurde erfolgreich an Dr. Schröder übermittelt.
B2 -> EM : Ihr ausgefülltes Formular wurde erfolgreich an Dr. Schröder übermittelt.

@enduml