/' 
# TI-Messenger 1.1
# TI-Messenger-Dienst
# UC - 10057
# Sequence Diagram
# Name: Anmeldung eines Akteurs am Messenger-Service
'/

@startuml
skinparam sequenceMessageAlign direction
skinparam minClassWidth 200
skinparam BoxPadding 1
skinparam sequenceReferenceHeaderBackgroundColor palegreen
scale max 2048 width
autonumber

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION



ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20
ActorFontName Aapex
}
    actor U as "Akteur in der\nRolle User"
    participant C as "TI-Messenger-Client"
    box <size:18>Messenger-Service</size> #WhiteSmoke
      participant MP as "Messenger Proxy"
      participant MH as "Matrix-Homeserver"
    end box

|||
  U->C: Eingabe Messenger-Service 
    Activate C
  C->MP: GET /_matrix/client/login
    Activate MP 
  MP->MH: HTTP(S) Forward
   Activate MH

|||
note over U, MH: <size:17>Die Authentifizierungsverfahren werden für jeden \n<size:17>Messenger-Service durch die Organisation festgelegt</size>
|||

  MH-->MP: unterstützte \nAuthentifizierungs-\nverfahren
    Deactivate MH
  MP-->C: HTTP(S) Forward
    Deactivate MP
  C-->U: Zeige \nAuthentifizierungsmaske
  |||
  U->U: Starte Authentifizierung
  U->C: Anmeldung
  C->MP: POST /_matrix/client/login
    Activate MP

    
    MP->MH: HTTP(S) Forward
      Activate MH
    MH->MH: prüfe \nClient-Credentials
    |||
    opt#LightGrey #MistyRose <size:16>Abbruch</size>
      MH-->MP:Fehlerhafte \nAnmeldedaten 
      MP-->C: HTTP(S) Forward
      C-->U: Anmeldedaten \nsind nicht korrekt
      |||
    end
    |||
    
    note over MH, MH: <size:17>Die Überprüfung ist abhängig vom \n<size:17>gewählten Authentifizierungsverfahren</size>
    
    |||
    MH->MH: erstelle \nMatrix-ACCESS_TOKEN, \nMatrix-REFRESH_TOKEN
    MH-->MP: :Matrix-ACCESS_TOKEN, \n:Matrix-REFRESH_TOKEN
      Deactivate MH
    MP-->C: HTTP(S) Forward
      Deactivate MP
    |||
    C->C: Speichere \nMatrix-ACCESS_TOKEN, \nMatrix-REFRESH_TOKEN

    C-->U: Anmeldung \nerfolgreich
        Deactivate C
    |||
@enduml
