@startuml
/' 
# UC - 10063
# Name: Austausch von Events zwischen Akteuren innerhalb einer Organisation
'/

skinparam sequenceMessageAlign direction
skinparam minClassWidth 200
skinparam BoxPadding 1
skinparam sequenceReferenceHeaderBackgroundColor palegreen
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20
}
    actor U1 as "Akteur A in der\nRolle User"
    participant C1 as "TI-Messenger-\nClient A" #AliceBlue
    box <size:18>Messenger-Service</size> #WhiteSmoke
      participant MP as "Messenger-\nProxy"
      participant MH as "Matrix-Homeserver \n(inklusive Nutzerverzeichnis)"
    end box
    participant PG as "Push-\nGateway"
    participant C2 as "TI-Messenger-\nClient B" #TECHNOLOGY
    actor U2 as "Akteur B in der\nRolle User"

autonumber

|||
note over U1, U2: \n<size:17>Die Akteure sind auf dem selben Messenger-Service angemeldet und im Besitz eines zugelassenen TI-Messenger-Clients.</size>\n<size:17>Ebenfalls sind beide Akteure einem gemeinsamen Raum beigetreten.</size>\n
|||
    U1->C1: Akteur A löst \nMatrix-Event aus
      activate C1 #AliceBlue
    C1->MP: Matrix-Request
      activate MP

    MP->MH: HTTP(S) Forward
      activate MH
    MH->MH: Event verarbeiten

    MH-->MP: Matrix-Request Status
    MP-->C1: HTTP(S) Forward
      deactivate MP
    C1-->U1: Status
      deactivate C1

    
    |||
    opt#LightGrey #AliceBlue <size:16>Push-Benachrichtigung</size>
    |||
    MH->PG: POST /_matrix/push/notify
      activate PG
    PG->C2: Notification
    PG-->MH: Status
      deactivate PG
      deactivate MH
    |||
    end
    
    |||
    C2->MP: GET /_matrix/client/v3/sync
      activate MP
      activate C2 #TECHNOLOGY
    MP->MH: HTTP(S) Forward
      activate MH
    MH-->MP: Status
      deactivate MH
    MP-->C2: HTTP(S) Forward    
      deactivate MP
    C2->C2: Event\nverarbeiten
    |||
    C2-->U2: Status
      deactivate C2
|||
@enduml