/' 
# TI-Messenger 1.1.1
# TI-Messenger-Dienst
# UC - 
# Sequence Diagram
# Name: Signatur der Föderationsliste prüfen
'/

@startuml
skinparam sequenceMessageAlign direction
skinparam minClassWidth 200
skinparam BoxPadding 1
skinparam sequenceReferenceHeaderBackgroundColor palegreen
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

}

autonumber

box <size:18>Messenger-Service\n #WhiteSmoke
participant MP as "Messenger-Proxy"
end box
participant OCSP as "Public OCSP-Responder"

activate MP
MP->MP++: Signatur der Föderationsliste prüfen\n(Föderationsliste, x5c-Zertifikatsliste[1])
return Signaturprüfergebnis
|||
loop#LightGrey <size:16>für jeden Eintrag von x5c-Zertifikatsliste</size>
  MP->OCSP: Public-OCSP-Zertifikatsprüf-Request stellen(x5c-Zertifikat)
  MP<--OCSP: OCSP-Response
end
alt#LightGrey <size:16>Signaturprüfergebnis=gültig UND jeder OCSP-Response.CertificateStatusValue=good</size>
  MP->MP: Föderationsliste aktualisieren(Föderationsliste)
end
deactivate MP
|||

@enduml
