ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images
:docsdir: ../docs
:toc: macro
:toclevels: 6
:toc-title: Table of Contents
:numbered:
:sectnumlevels: 6

image:gematik_logo.svg[width=70%]

toc::[]

= Tiefenintegration Primärsysteme
Der folgende Leitfaden beschreibt, wie das Primärsystem die Funktionalitäten vom TI-Messenger umsetzt.

CAUTION: Im Rahmen der Gespräche mit den Herstellern hat sich herausgestellt, dass sehr unterschiedliche Vorstellungen zum Zulassungsobjekt (Tiefenintegration eines Clients in Primärsysteme) existieren. Für die aktuell veröffentlichte Version des *TI-Messenger-Dienstes* v1.1.1 kann nur ein *TI-Messenger-Client* gemäß des Produkttypsteckbriefes zugelassen werden. Der gematik ist bewusst, dass der Wunsch einer Tiefenintegration von Clients in Primärsysteme aus Sicht der Industrie vorhanden ist. Die gematik arbeitet diesbezüglich an einer Lösung. 
