ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images

:toc: macro
:toclevels: 3
:toc-title: Table of Contents
:numbered:

image:gematik_logo.svg[width=70%]

toc::[]

== *HOWTO: Authenticate as an organization to the VZD-FHIR-Directory*

Only the owner of an SMC-B is able to change the organization entry in the VZD-FHIR-Directory. The card and an the entry are connected by the telematik-ID. So it would be necessary to use the SMC-B card to authenticate oneself as an organization in the german healthcare system every time access to the organization ressourcec in the VZD-FHIR-Directory is needed. Besides the card itself a card terminal and a connector need to be also in place. 

The more user friendly approach...

====
. register the Registrierung-Dienst with the VZD-FHIR-Directory
. store the telematik-ID used while ordering the TI-Messenger service
. create an RegService-OpenID-Token for the Org-Admin
. exchange the RegService-OpenID-Token for an owneraccess-Token
====

=== Register the Registrierung-Dienst with the VZD-FHIR-Directory
. First of all a certificate is needed that can be obtained by creating a service request in the gematik TI-ITSM portal. The certificate must must have the type C.FD.SIG and the technical role "oid_tim" Please contact your Transisiton Manager for further details. 
. The certificate then needs to be provided while creating another service request in the gematik TI-ITSM portal for the TIM-Provider-Services credentials. Please contact your Transisiton Manager for further details. While creating the service request you will be asked for the certificate. This ensures that only registered TI-Messenger service providers are able to create exchange Token with the VZD-FHIR-Directory.

=== Store the Telematik-ID used while ordering the TI-Messenger service
The Telematik-ID is needed as part of the RegService-OpenID-Token that is descriped in the next paragraph. The VZD-FHIR-Directory needs that information to identify for which FHIR-Ressources an owneraccess-Token will be provided.

=== Create an RegService-OpenID-Token for the Org-Admin
The RegService-OpenID-Token is a JWT and has to be filled with the following content: 
[source,json]
----
HEADER
{
  "alg": "RS256",
  "typ": "JWT"
  "x5c": [
     "<X.509 Sig-Cert, base64-encoded DER>",
     "<X.509 CA-Cert, base64-encoded DER>"
 ]
}
PAYLOAD
{
  "sub": "1234567890",
  "iss": "<url des Registrierungs-Dienst-Endpunkts, über den das Token ausgestellt wurde>",
  "aud": "https://vzd-fhir-directory.vzd.ti-dienste.de/owner-authenticate",
  "professionOID": "<professionOID der Organisation>",
  "idNummer": "<telematikID der Organisation>",
  "iat": "1516239022", 
  "exp": "1516239022"
}
----
For the signature of the token the C.FD.SIG certificates private key has to be used and the certificate must be included in the JWT HEADER.  

=== Exchange the RegService-OpenID-Token for an owneraccess-Token
The RegService-OpenID-Token can be exchanged for an owneraccess-Token by authenticating oneself with the token against the /owner-authenticate endpoint of the VZD-FHIR-Directory. For further details, please check: https://github.com/gematik/api-vzd/blob/feature/ILF-FHIR_VZD/docs/gemILF_FHIR_VZD.adoc#211-authentication[VZD-FHIR-DIRECTORY-ENDPOINTS] TODO: Replace with final Link after Release


