ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images
:toc: macro
:toclevels: 6
:toc-title: Inhaltsverzeichnis
:numbered:
:sectnumlevels: 6

image:gematik_logo.svg[width=70%]

toc::[]

= TI-Messenger-Client
== Überblick
Im Kontext des TI-Messenger-Dienstes wird zwischen den folgenden Ausprägungen des *TI-Messenger-Clients* unterschieden:

* *TI-Messenger-Clients für Akteure* und 
* *TI-Messenger-Clients mit Administrationfunktionen*. 

Beide Arten von Clients basieren auf dem offenen Kommunikationsprotokoll Matrix und werden auf dem Endgerät eines Akteurs verwendet. In der folgenden Dokumentation werden die zwei Ausprägungen der Clients beschrieben. 

== TI-Messenger-Client für Akteure
Der *TI-Messenger-Client* für Akteure unterstützt die meisten aller, durch die Matrix-Spezifikation festgelegten Funktionalitäten eines Matrix-Messengers und weitere durch die gematik definierten Vorgaben. Die Funktionalität des *TI-Messenger-Clients* für Akteure kann in drei abstrakte Module unterteilt werden. In der folgenden Abbildung wird dies verdeutlicht.

++++
<p align="left">
  <img width="80%" src=../../images/I_Client.png>
</p>
++++

=== Abstrakte Module 
==== TI-Messenger Modul
Über das _TI-Messenger Modul_ werden alle Funktionalitäten, die zur Ad-Hoc Kommunikation benötigt werden sowie der Administration der Freigabeliste eines Akteurs, durchgeführt. Hierfür werden am *Messenger-Proxy* zwei APIs vom  _TI-Messenger Modul_ des *TI-Messenger-Clients* angesprochen. Der *TI-Messenger-Client* kommuniziert mit dem *Messenger-Proxy* eines *Messenger-Services* über die [Matrix - Client-Server API], um `Matrix-Events` an den zuständigen *Matrix-Homeserver* auszutauschen. Fü die Administration der Freigabeliste kommuniziert das _TI-Messenger Modul_ mit der Schnittstelle `I_Ti_MessengerContactManagement` des *Messenger-Proxy*.

NOTE: Der Aufruf der vom *Matrix-Homeserver* angebotenen Schnittstellen der [Matrix - Client-Server API] erfolgt immer über den *Messenger-Proxy*. 

In den folgenden Kapiteln werden die vom _TI-Messenger Modul_ zu verwendenen Schnittstellen sowie die vom *TI-Messenger-Client* bereitzustellenden Funktionen beschrieben. 

===== Matrix - Client-Server API
Der *Matrix-Homeserver* muss die REST-Schnittstellen gemäß der Matrix https://spec.matrix.org/v1.3/client-server-api/[[Client-Server API]] für den *TI-Messenger-Client* zur Verfügung stellen. Diese müssen füe die *TI-Messenger-Clients* aus dem Internet angeboten werden. Für die Verarbeitung der `Matrix-Events` muss der *TI-Messenger-Client* die in der [Matrix-Client-Server API] clientspezifischen verhaltensweisen implementieren. Diese sind in der APi mit dem Keyword _behaviour_ gekennzeichnet. Im folgenden ist ein Beispiel für das https://spec.matrix.org/v1.3/client-server-api/#client-behaviour-21[Client Verhalten für den Direktnachrichtenaustausch] dargestellt. 

Für ein Überblick und für testzwecke der REST-Schnittstellen der [Matrix-Client-Server API] kann der von der Matrix Foundation bereitgestellte https://matrix.org/docs/api/#overview[[API Playground]] verwendet werden. 

CAUTION: Der Playground bildet immer die aktuellste Version der Matrix-Spezifikation ab und stimmt somit ggf. nicht mit der aktuell von der gematik geforderten Version der Matrix-API überein. 

Im Rahmen der Verwendung des Matrix-Protokolls im deutschen Gesundheitswesen ist es notwendig dies um weitere Vorgaben zu erweitern. Hierzu trifft die gematik die folgenden weiteren Festlegungen zum Umgang mit dem Matrix-Protokoll.

====== CreateRoom 
Beim Anlegen eines Raumes über den `/_matrix/client/v3/createRoom` Endpunkt (siehe: link:https://spec.matrix.org/v1.3/client-server-api/#post_matrixclientv3createroom[createRoom]) über die [Client-Server-API] ist darauf zu achten, dass im `invite`-Feld maximal eine Matrix-ID (`MXID`) eines einzuladenden Akteurs angegeben werden darf. Die Vorgabe muss eingehalten werden, damit diese bei der link:../../docs/anwendungsfaelle/MS-stufen-berechtigungspruefung.adoc#stufe-1-pr%C3%BCfung-der-ti-f%C3%B6derationszugeh%C3%B6rigkeit[Proxy Berechtigungsprüfung] validiert werden kann.

====== Custom Room Types 
Das Matrix-Protokoll erlaubt während der Erstellung eines Chatraumes einen eigene Raumtyp (_Custom Room Type_) für diesen mit Hilfe einer Typinitialisierung im `/_matrix/client/v3/createRoom`-Endpunkt zu definieren, um spezielle Raumeigenschaften (_Room State Events_) für diesen _Custom Room Type_ zu verwenden. Die gematik definiert für föderierte und fallbezogene Kommunikation die folgenden Raumtypen. 

- `de.gematik.tim.roomtype.default.v1`
- `de.gematik.tim.room.casereference.v1`

Es ist vorgesehen den Raumtyp `de.gematik.tim.roomtype.default.v1` für alle föderierten Kommunikation beim Anlegen entsprechend zu setzen. 
Der Raumtyp `de.gematik.tim.room.casereference.v1` ist für die spätere Verwendung im Context von Fallbezogenen Kommunikationen vorgesehen.

TIP: Weitere Informationen mit den Umgang der Raumtypen können in *[gemSpec_Ti-Messenger-Client#5.4.17]* und *[gemSpec_Ti-Messenger-Client#5.4.16]* nachgelesen werden.  

NOTE: In der veröffentlichten und zulassungsrelevanten Spezifikationsversion v1.1.1 wird die produktive Verwendung der _Custom Room Types_ aktuell nicht gefordert, da die notwendigen Vorbedingungen für den produktiven Einsatz seitens des Matrix-Protokolls noch nicht vollständig erfüllt sind.

====== Custom State Events
Das Matrix-Protokoll erlaubt die Eigenschaften eines Chatraumes mit _State Events_ zu erweitern bzw. zu ändern. Typische _State Events_, die ein _Room State_ definieren und die durch das Matrix-Protokoll definiert sind, sind zum Beispiel `m.room.name` oder `m.room.topic`. Das Matrix-Protokoll erlaubt auch benutzerdefinierte State Events (_Custom State Events_) zu verwenden. In der vorliegenden Dokumentation werden bereits erste _Custom Room Types_ sowie _Custom State Events_ mit von der gematik definierten _Event Type_s und _Event Content_ definiert. 

- `de.gematik.tim.room.name` +
- `de.gematik.tim.room.topic` +
- `de.gematik.tim.room.default.v1` +
- `de.gematik.tim.room.casereference.v1`

Für die Fallbezogene Kommunikation sind die beiden _Custom State Events_ `de.gematik.tim.room.name` und `de.gematik.tim.room.topic` vorgesehen, um eine verschlüsselte Abbildung der beiden Standardfelder `m.room.name` und `m.room.topic` zu relasieren, da im Fallbezogenen Kontext ein hoher Datenschutzbedarf besteht. Im Kontext der fallbezogenen Kommunikation ist es notwendig zusätzliche patientbezogene Informationen bereitzustellen. Hierfür ist das _Custom State Event_ `de.gematik.tim.room.casereference.v1` vorgesehen, um in diesem den folgenden link:https://simplifier.net/tim[FHIR-Datensatz] zu hinterlegen.  

Das _Custom State Event_ `de.gematik.tim.room.default.v1` ist vorgesehen, um verschlüsselte Information im Kontext von intersektoraler Kommunikation zu ermöglichen. In diesem Fall sind die Informationen zu "Name" und "Topic" des Raumes ebenfalls über die Events `de.gematik.tim.room.topic` und `de.gematik.tim.room.name` abzubilden. 

TIP: Weitere Informationen zu den _Custom State Events_ können in *[gemSpec_Ti-Messenger-Client]#5.4.17* und *[gemSpec_Ti-Messenger-Client#5.4.16]* nachgelesen werden. 

NOTE: In der veröffentlichten und zulassungsrelevanten Spezifikationsversion v1.1.1 wird die produktive Verwendung der _Custom State Events_ aktuell nicht gefordert, da die notwendigen Vorbedingungen für den produktiven Einsatz seitens des Matrix-Protokolls noch nicht vollständig erfüllt sind.

===== I_Ti_MessengerContactManagement
Über die vom *Messenger-Proxy* bereitgestellte Schnittstelle `I_Ti_MessengerContactManagement` wird die für einen Akteur im Proxy vorgehaltene Freigabeliste administriert. Die Freigabeliste wird in link:docs/anwendungsfaelle/COM-AF10061-einladung-ausserhalb.adoc[AF10061 - Einladung von Akteuren außerhalb einer Organisation] benötigt, wenn zwei Akteure ihre Kontaktdaten mittels QR-Scan austauschen möchten. Weitere Informationen zu der Schittstelle sind link:../../docs/Fachdienst/MessengerService.adoc#i_timessengercontactmanagement[hier] zu finden.

==== VZD-FHIR-Directory Modul
Über das _VZD-FHIR-Dirctory Modul_ wird die Suche und die Pflege von Einträgen im *FHIR-Directory* ermöglicht. Hier werden die folgenden Schnittstellen der Teilkomponenten *Auth Services* und *FHIR-Proxy* des *VZD-FHIR-Directory* vom _VZD-FHIR-Dirctory Modul_ des *TI-Messenger-Clients* angesprochen:

* *Auth-Service* +
- `/tim-authenticate` +
- `/owner-authenticate` +
* *FHIR-Proxy* +
- `/search` +
- `/owner`

Für den Aufruf der beiden Schnittstellen `/search` und `/owner` am *FHIR-Proxy* für die Suche und Pflege von Einträgen werden ACCESS_TOKEN benötigt, um die Berechtigung für den Zugriff nachzuweisen. Daher muss der *TI-Messenger-Client* zuvor am *Auth Service* des *VZD-FHIR-Directory* die notwendigen Token anfragen. Im folgenden werden die Aufrufe der Schnittstellen beschrieben. 

===== Auth-Service
Der *Auth-Service* des *VZD-FHIR-Directory* bietet die zwei Endpunkte an, die die beiden ACCESS_TOKEN  `search-accesstoken` und `owner-accesstoken` ausstellen. Die zwei Endpunkte werden in den folgenden Kapiteln weiter beschrieben.

====== /tim-authenticate
Für den Zugriff auf die Suche von FHIR-Ressourcen (`/search`-Endpukt) authentisiert sich der *TI-Messenger-Client* gegenüber dem *VZD-FHIR-Directory* mit einem 3rd Party `Matrix-OpenID Token`, den er von seinem *Matrix-Homeserver* anfordern kann. (siehe link:https://spec.matrix.org/v1.3/client-server-api/#post_matrixclientv3useruseridopenidrequest_token[Matrix OpenID Token]). Dieses 3rd Party Token benötigt der *TI-Messenger-Client*, um es beim `/tim-authenticate`-Endpunkt des *VZD-FHIR-Directory* gegen ein `search-accesstoken` einzutauschen. Bei Aufruf des Endpunktes `/tim-authenticate` ist es erforderlich dass 3rd Party Token `Matrix-OpenID-Token` im Header und die URL des *Matrix-Homeservers* im Parameter `MXID` zu übergeben. Der Aufruf des `/tim-authenticate`-Endpunktes ist (siehe link:https://github.com/gematik/api-vzd/blob/feature/gemILF_VZD_FHIR_Directory/docs/FHIR_VZD_HOWTO_Authenticate.adoc#21-authenticate-for-the-search-endpoint[hier]) beschrieben. 

====== /owner-authenticate
Für die Pflege von FHIR-Ressourcen (`/owner`) authentisiert sich der *TI-Messenger-Client* gegenüber dem *VZD-FHIR-Directory* unter Verwendung einer Smartcard (HBA), um ein `owner-accesstoken` vom *Auth-Service* zu erhalten. Für die Authentisierung mittels Smartcard ist der von der gematik bereitgestellte *zentrale IDP-Dienst* zu verwenden (Siehe bitte Kapitel Auth-Modul). Details sind dem Anwendungsfall link:docs/anwendungsfaelle/VZD-AF10058-practitioner-hinzufuegen.adoc[AF10058 - Akteur (User-HBA) im Verzeichnisdienst hinzufügen] zu entnehmen. Nach erfolgreicher Authensierung erhält der *TI-Messenger-Client* vom *Auth-Service* ein `owner-accesstoken`. Der Aufruf des `/owner-authenticate`-Endpunktes ist (siehe link:https://github.com/gematik/api-vzd/blob/feature/gemILF_VZD_FHIR_Directory/docs/FHIR_VZD_HOWTO_Authenticate.adoc#24-authenticate-for-the-owner-endpoint-as-an-user[hier]) beschrieben. 

TIP: Für die Interaktion mit den Smartcards und dem *zentralen IDP-Dienst* der gematik kann der link:https://fachportal.gematik.de/hersteller-anbieter/komponenten-dienste/authenticator[gematik authenticator] genutzt werden. 

Der durchzuführende Authorization Code Flow ist hier link:[TODO] beschrieben.

===== FHIR Proxy
Der *FHIR-Proxy* bietet zwei Schnittstellen zur Suche und Pflege von FHIR-Ressourcen an, die nur unter Verwendung eines gültigen ACCESS_TOKEN aufgerufen werden können. Die zwei Endpunkte werden in den folgenden Kapiteln weiter beschrieben.

====== /search
Der *FHIR-Proxy* bietet über die Schnittstelle `FHIRDirectorySearchAPI` den Endpunkt `/search` an, um FHIR-Ressourcen zu suchen. Um den Endpunkt `/search` aufrufen zu können, wird ein `search-accesstoken` im Authorization Header benötigt. Eine beispielhafte Verwendung der Schnittstelle für die Suche von FHIR-Ressourcen ist in der link:https://github.com/gematik/api-vzd/blob/feature/gemILF_VZD_FHIR_Directory/docs/FHIR_VZD_HOWTO_Search.adoc[search API examples] beschrieben.

====== /owner
Der *FHIR-Proxy* bietet über die Schnittstelle `FHIRDirectoryOwnerAPI` den Endpunkt `/owner` an, um FHIR-Ressourcen zu suchen und eigene Einträge zu pflegen. Um den Endpunkt `/owner` aufrufen zu können, wird ein `owner-accesstoken` im Authorization Header benötigt. Eine beispielhafte Verwendung der Schnittstelle zur Pflege der FHIR-Ressourcen ist in der link:https://github.com/gematik/api-vzd/blob/feature/gemILF_VZD_FHIR_Directory/docs/FHIR_VZD_HOWTO_Owner.adoc[owner API examples] beschrieben. 

==== Auth Modul
Über das _Auth Modul_ wird die Kommunikation mit Smartcards (HBA) releasiert, um diese zur Authentisierung am  `/owner-authenticate`-Endpunkt zu ermöglichen. Dies wird als Grundlage für den Anwendungsfall link:docs/anwendungsfaelle/VZD-AF10058-practitioner-hinzufuegen.adoc[AF_10058 Akteur(User-HBA) im Verzeichnisdienst hinzufügen] benötigt. Im Folgenden wird der Prozess kurz skizziert, nachdem beim Aufruf der `/owner-authenticate`-Endpunktes der Redirect zum `Authorization Endpoint` des IDP-Dienstes zurückgegeben wurde. 

===== Authorization Endpoint zentraler IDP-Dienst
Hierfür ruft das _Auth Modul_ des *TI-Messenger-Clients* den `{Authorization Endpoint}` am *zentralen IDP-Dienst* auf, um das Challenge-Response-Verfahren durchzuführen und den `AuthorizationCode` sowie den Redirect zum Endpunkt `/signin-gematik-idp-dienst` zu erhalten. 

===== Signin-gematik-idp-dienst
An dem Endpunkt `/signin-gematik-idp-dienst` übergibt der *TI-Messenger-Client* den `AuthorizationCode` um sich ein `owner-accesstoken` ausstellen zu lassen. Der `AuthorizationCode` wird vom *Auth-Service* an den *zentralen-IDP-Dienst* weitergeleitet, um das für die passende Smartcard gehörende `ID_TOKEN` zu erhalten. Die darin enthaltenen `TelematikID` und `ProfessionOID` werden im Rahmen der Ausstllung des `owner-accesstoken` verwendet. 

=== Bereitstellung weiterer Funktionalitäten
==== Sichbarkeit 
*TI-Messenger-Clients* müssen über eine Funktion verfügen die die Sichtbarkeit eines Akteurs für den *TI-Messenger-Dienst* im Personenverzeichnis über den `/owner`-Endpunkt des *VZD-FHIR-Directory* ein bzw. ausschalten kann. Wenn ein Akteur den Status seines Endpunktes von `active` nach `off` link:https://github.com/gematik/api-vzd/blob/feature/gemILF_VZD_FHIR_Directory/docs/FHIR_VZD_HOWTO_Owner.adoc#232-update-endpoint-put[ändert], muss der TI-Messenger-Client prüfen, ob diese `MXID` auch im Organisationsverzeichnis eingetragen ist. Wird die `MXID` ebenfalls im Organisationsverzeichnis gefunden und ist der hinterlegte status in diesem Verzeichnis active, dann ist im TI-Messenger-Client dem Akteur ein entsprechender Hinweis anzuzeigen, dass eine Inkonsistenz in der hinterlegten Sichtbarkeit vorliegt. 

IMPORTANT: Aus dem Hinweis muss hervorgehen, dass ein Kontaktieren des Administrators seiner Organisation notwendig ist, um die gewünschte Sichtbarkeit ebenfalls im Organisationsverzeichnis zu hinterlegen. 

==== Kontaktdatenaustausch mit 2D-Barcode
Der *TI-Messenger-Client* muss eine Funktion bereitstellen, um Kontaktdaten mittels 2D-Barcodes austauschen zu können. 

Hierbei muss der 2D-Code in eine QR-Code-Darstellung gemäß [ISO/IEC 18004:2006] kodiert werden. Im folgenden wird das zu verwendene vCard-Object dargestellt:
[source, text]
----
BEGIN:VCARD
  VERSION:4.0 
  N:<Nachname>;<Vorname>;<zusätzliche Vornamen>;<Titel>;<Namenszusätze> 
  FN:<Vorname><Nachname> 
  IMPP:matrix://<MXID> 
END:VCARD
----
Der Aufbau der Matrix-URI muss gemäß link:https://spec.matrix.org/v1.3/appendices/#uris[Matrix-Appendices#uris] gebildet werden.

TIP: Bei dem gezeigten vCard-Object handelt es sich um die geforderte Mindestbefüllung, die Verwendung weiterer Felder ist zulässig.

Der *TI-Messenger-Client* muss den eingescannten 2D-Code gemäß [ISO/IEC 18004:2006] decodieren und mindestens den vollständigen Namen sowie die `MXID` aus den Parameter `N` und `IMPP` dem Akteur anzeigen, damit dieser die Aufnahme in die Freigabeliste bestätigen oder ablehnen kann. siehe link:docs/anwendungsfaelle/COM-AF10061-einladung-ausserhalb.adoc[Einladung von Akteuren außerhalb der Organisation]

==== Editierbarkeit von Displaynamen
TODO

== TI-Messenger-Client mit Administrationsfunktionen 
=== Überblick
Der *TI-Messenger-Client* mit Administrationsfunktionen ist ein Client für Akteure in der Rolle Org-Admin einer Organisation. Dieser wird im TI-Messenger-Kontext auch als *Org-Admin-Client* bezeichnet. Der Org-Admin-Client dient zur komfortablen Verwaltung der Messenger-Services bei einem TI-Messenger-Fachdienst. Die im folgenden Beschriebenen Funktionalitäten für einen Org-Admin Client können separat oder in einen *TI-Messenger-Client* integriert sein.

=== Org-Admin Funktionalität
Mit dem *Org-Admin-Client* haben Administratoren einer Organisation die Möglichkeit Benutzer und Geräte auf dem jeweiligen Messenger-Service zu verwalten. Darüber hinaus besteht die Möglichkeit, über den *Org-Admin-Client* Sessions von angemeldeten Geräten auf dem Messenger-Service zu verifizieren oder zu invalidieren. Das bedeutet zum Beispiel, dass ein Akteur in der Rolle "Org-Admin" einen *TI-Messenger-Client* eines Akteurs bei Bedarf abmelden kann.

==== Auth owner-authenticate
Für den Zugriff auf die `/owner` Schnittstelle wird ein `owner-accesstoken` benötigt, dass vom `/owner-authenticate`` Endpunkt des *VZD-FHIR-Directory ausgestellt wird. Zur Authentisierung am Endpunkt fragt der *Org-Admin-Client* beim zuständigen *Registrierungs-Dienst* einen `RegService-OpenID-Token` an, welcher am `/owner-authenticate` Endpunkt gegen ein owner-accesstoken ausgetauscht wird. Ein Beispiel ist link:https://github.com/gematik/api-vzd/blob/feature/gemILF_VZD_FHIR_Directory/docs/FHIR_VZD_HOWTO_Authenticate.adoc#231-authenticate-with-an-regservice-openid-token[hier] zu finden.

==== Organisationsressourcen im VZD-FHIR-Directory bearbeiten
Mit dem Org-Admin-Client besteht die Möglichkeit, im Namen der Organisation FHIR-Ressourcen zur Verfügung zu stellen oder zu bearbeiten.
Funktionsaccounts

= Referenzierte Dokumente
Die nachfolgende Tabelle enthält die in der vorliegenden Online Dokumentation referenzierten Dokumente der gematik. Deren zu diesem Dokument jeweils gültige Versionsnummer entnehmen Sie bitte der aktuellen, auf der Internetseite der gematik veröffentlichten, Dokumentenlandkarte, in der die vorliegende Version aufgeführt wird.





|===
|[Quelle] |Herausgeber: Titel

|*[Client-Server API]* | https://spec.matrix.org/latest/client-server-api/
|*[API Playground]* | https://matrix.org/docs/api/#overview
|===
