ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images
:toc: macro
:toclevels: 5
:toc-title: Inhaltsverzeichnis
:numbered:
:sectnumlevels: 5

image:gematik_logo.svg[width=70%]

toc::[]

= TI-Messenger-Client
== Überblick
Der TI-Messenger-Client basiert auf dem offenen Kommunikationsprotokoll Matrix und wird auf dem Endgerät eines Akteurs verwendet. Die Funktionalität des TI-Messenger-Clients kann in drei abstrakte Module unterteilt werden. In der folgenden Abbildung wird dies verdeutlicht. 

++++
<p align="left">
  <img width="80%" src=../../images/I_Client.png>
</p>
++++

== Abstrakte Module 
=== TI-Messenger Modul
Über dieses abstrakte Modul wird die Ad-Hoc Kommunikation durchgeführt. Der *TI-Messenger-Client* kommuniziert mit dem *Messenger-Proxy* eines *Messenger-Services* über die Matrix - Client-Server Schnittstelle, um Events auszutauschen. Ebenfalls bietet der *Messenger-Proxy* für die Administration der Freigabeliste die Schnittstelle I_Ti_MessengerContactManagement bereit. 

NOTE: Der Aufruf der vom *Matrix-Homeserver* angebotenen Schnittstellen erfolgt immer über den *Messenger-Proxy*. 

In den folgenden Kapiteln werden die Schnittstellen und deren bereitzustellenden Funktionen beschrieben. 

==== Matrix - Client-Server API
Der *Matrix-Homeserver* muss die REST-Schnittstellen gemäß der Matrix https://spec.matrix.org/v1.3/client-server-api/[[Client-Server API]] für den *TI-Messenger-Client* anbieten. Der TI-Messenger-Client muss die in der Matrix-Client-Server API clientspezifischen verhaltensweisen implementieren (Beispiel: https://spec.matrix.org/v1.3/client-server-api/#client-behaviour-21[Client Verhalten für den Direktnachrichtenaustausch]). 

Für ein Überblick und für testzwecke der REST-Schnittstellen der Matrix-Client-Server API kann der von der Matrix Foundation bereitgestellte https://matrix.org/docs/api/#overview[[API Playground]] verwendet werden. 

CAUTION: Der Playground bildet immer die aktuellste Version der Spezifikation ab und stimmt somit ggf. nicht mit der aktuell von der gematik geforderten Version der Matrix-API überein. 

Im Rahmen der Verwendung des Matrix-Protokoll im deutschen Gesundheitswesen ist es notwendig dies um weitere Vorgaben zu erweitern. Hierzu trifft die gematik die folgenden weiteren Festlegungen.

===== CreateRoom 
Beim Anlegen eines Raumes (link:https://spec.matrix.org/v1.3/client-server-api/#post_matrixclientv3createroom[createRoom]) über die Client-Server-API ist darauf zu achten, dass im `invite` Feld maximal eine Matrix-ID (`MXID`) einer einzuladenden Person angegeben werden darf. Die Vorgabe muss eingehalten werden, damit diese bei der link:../../docs/anwendungsfaelle/MS-stufen-berechtigungspruefung.adoc#stufe-1-pr%C3%BCfung-der-ti-f%C3%B6derationszugeh%C3%B6rigkeit[Proxy Berechtigungsprüfung] validiert werden kann.

===== Custom Room Types 
Das Matrix-Protokoll erlaubt während der Erstellung eines Chatraumes einen eigene Raumtyp (_Custom Room Type_) für diesen mit Hilfe einer Typinitialisierung im `/createRoom`-Endpunkt zu definieren, um spezielle Raumeigenschaften (_Room State Events_) für diesen _Custom Room Type_ zu verwenden. Die gematik definiert für föderierte und fallbezogene Kommunikation die folgenden Raumtypen. 

- `de.gematik.tim.roomtype.default.v1`
- `de.gematik.tim.room.casereference.v1`

Es ist vorgesehen den Raumtyp `de.gematik.tim.roomtype.default.v1` für alle föderierten Kommunikation beim Anlegen entsprechend zu setzen. 
Der Raumtyp `de.gematik.tim.room.casereference.v1` ist für die spätere Verwendung im Context von Fallbezogenen Kommunikationen vorgesehen.

TIP: Weitere Informationen mit den Umgang der Raumtypen finden sich in *[gemSpec_Ti-Messenger-Client]#5.4.17* und *[gemSpec_Ti-Messenger-Client#5.4.16]*  

NOTE: In der veröffentlichten und zulassungsrelevanten Spezifikationsversion v1.1.1 wird die produktive Verwendung der _Custom Room Types_ aktuell nicht gefordert, da die notwendigen Vorbedingungen für den produktiven Einsatz seitens des Matrix-Protokolls noch nicht vollständig erfüllt sind.

===== Custom State Events
Das Matrix-Protokoll erlaubt die Eigenschaften eines Chatraumes mit _State Events_ zu erweitern bzw. zu ändern. Typische _State Events_, die ein _Room State_ definieren und die durch das Matrix-Protokoll definiert sind, sind zum Beispiel `m.room.name` oder `m.room.topic`. Das Matrix-Protokoll erlaubt auch benutzerdefinierte State Events (_Custom State Events_) zu verwenden. In der vorliegenden Dokumentation werden bereits erste _Custom Room Types_ sowie _Custom State Events_ mit von der gematik definierten _Event Type_s und _Event Content_ definiert. 

- `de.gematik.tim.room.name` +
- `de.gematik.tim.room.topic` +
- `de.gematik.tim.room.default.v1` +
- `de.gematik.tim.room.casereference.v1`

Für die Fallbezogene Kommunikation sind die beiden _Custom State Events_ `de.gematik.tim.room.name` und `de.gematik.tim.room.topic` vorgesehen, um eine verschlüsselte Abbildung der beiden Standardfelder `m.room.name` und `m.room.topic` zu relasieren, da im Fallbezogenen Kontext ein hoher Datenschutzbedarf besteht. Im Kontext der fallbezogenen Kommunikation ist es notwendig zusätzliche patientbezogene Informationen bereitzustellen. Hierfür ist das _Custom State Event_ `de.gematik.tim.room.casereference.v1` vorgesehen, um in diesem den folgenden link:https://simplifier.net/tim[FHIR-Datensatz] zu hinterlegen.  

Das _Custom State Event_ `de.gematik.tim.room.default.v1` ist vorgesehen, um verschlüsselte Information im Kontext von intersektoraler Kommunikation zu ermöglichen. In diesem Fall sind die Informationen zu "Name" und "Topic" des Raumes ebenfalls über die Events `de.gematik.tim.room.topic` und `de.gematik.tim.room.name` abzubilden. 

TIP: Weitere Informationen zu den _Custom State Events_ finden sich in *[gemSpec_Ti-Messenger-Client]#5.4.17* und *[gemSpec_Ti-Messenger-Client#5.4.16]*  

NOTE: In der vorliegenden zulassungsreleventane Spezifikationsversion v1.1.1 wird die produktive Verwendung der _Custom State Events_ aktuell nicht gefordert, da die notwendigen Vorbedingungen für den produktiven Einsatz seitens des Matrix-Protokolls noch nicht vollständig erfüllt sind.

==== I_Ti_MessengerContactManagement
Über die vom *Messenger-Proxy* bereitgestellte Schnittstelle `I_Ti_MessengerContactManagement` wird die für einen Nutzer erzeugte Freigabeliste administriert. Die Freigabeliste wird in link:docs/anwendungsfaelle/COM-AF10061-einladung-ausserhalb.adoc[AF10061 - Einladung von Akteuren außerhalb einer Organisation] benötigt, wenn zwei Akteure ihre Kontaktdaten mittels QR-Scan austauschen. Weitere Informationen zu der Schittstelle sind link:../../docs/Fachdienst/MessengerService.adoc#i_timessengercontactmanagement[hier] zu finden.

=== VZD-FHIR-Directory Modul
Über dieses abstrakte Modul wird die Suche und die Pflege von Einträgen im *FHIR-Directory* ermöglicht. Der *TI-Messenger-Client* ruft die Schnittstellen der folgenden Teilkomponenten *Auth Services* und *FHIR-Proxy* am VZD-FHIR-Directory auf:

* *Auth-Service* +
- `/tim-authenticate` +
- `/owner-authenticate` +
* *FHIR-Proxy* +
- `/search` +
- `/owner`

Für den Aufruf der beiden Schnittstellen `/search` und `/owner` am *FHIR-Proxy* für die Suche und Pflege von Einträgen werden ACCESS_TOKEN benötigt, um die Berechtigung für den Zugriff nachzuweisen. Daher muss der *TI-Messenger-Client* zuvor am *Auth Service* des *VZD-FHIR-Directory* die notwendigen Token anfragen. Im folgenden werden die Aufrufe der Schnittstellen beschrieben. 

==== Auth-Service
Der Auth-Service bietet 2 Endpunkte an, die die beiden ACCESS_TOKEN  `search-accesstoken` und `owner-accesstoken` ausstellen. Die 2 Endpunkte werden in den folgenden Kapiteln weiter beschrieben.

===== /tim-authenticate
Für den Zugriff auf die Suche von FHIR-Ressourcen (`/search`) authentisiert sich der *TI-Messenger-Client* gegenüber dem *VZD-FHIR-Directory* mit einem 3rd Party `Matrix-OpenID Token`, den er von seinem *Matrix-Homeserver* anfordern kann. (siehe link:https://spec.matrix.org/v1.3/client-server-api/#post_matrixclientv3useruseridopenidrequest_token[Matrix OpenID Token]) Dieses 3rd Party Token benötigt der *TI-Messenger-Client*, um es beim `/tim-authenticate`-Endpunkt des *VZD-FHIR-Directory* gegen ein `search-accesstoken` einzutauschen. Bei Aufruf des Endpunktes `/tim-authenticate` ist es erforderlich dass 3rd Party Token `Matrix-OpenID-Token` im Header und die URL des *Matrix-Homeservers* im Parameter "MXID" zu übergeben. Der Aufruf des `/tim-authenticate`-Endpunktes ist (siehe link:https://github.com/gematik/api-vzd/blob/feature/gemILF_VZD_FHIR_Directory/docs/FHIR_VZD_HOWTO_Authenticate.adoc#21-authenticate-for-the-search-endpoint[hier]) beschrieben. 

===== /owner-authenticate
Für die Pflege von FHIR-Ressourcen (`/owner`) authentisiert sich der *TI-Messenger-Client* gegenüber dem *VZD-FHIR-Directory* unter Verwendung einer Smartcard (HBA), um ein `owner-accesstoken` vom *Auth-Service* zu erhalten. Für die Authentisierung mittels Smartcard ist der von der gematik bereitgestellte zentrale IDP-Dienst zu verwenden (Siehe bitte Kapitel Auth-Modul). Details sind dem Anwendungsfall link:docs/anwendungsfaelle/VZD-AF10058-practitioner-hinzufuegen.adoc[AF10058 - Akteur (User-HBA) im Verzeichnisdienst hinzufügen] zu entnehmen. Nach erfolgreicher Authensierung erhält der *TI-Messenger-Client* vom *Auth-Service* ein `owner-accesstoken`. Der Aufruf des `/owner-authenticate`-Endpunktes ist (siehe link:https://github.com/gematik/api-vzd/blob/feature/gemILF_VZD_FHIR_Directory/docs/FHIR_VZD_HOWTO_Authenticate.adoc#24-authenticate-for-the-owner-endpoint-as-an-user[hier]) beschrieben. 

TIP: Für die Interaktion mit den Smartcards und dem zentralen IDP-Dienst kann der link:https://fachportal.gematik.de/hersteller-anbieter/komponenten-dienste/authenticator[gematik authenticator] genutzt werden. 

Der durchzuführende Authorization Code Flow ist hier link:[TODO] beschrieben.

==== FHIR Proxy
Der *FHIR-Proxy* bietet Schnittstellen zur Suche und Pflege von FHIR-Ressourcen an, die nur unter Verwendung eines gültigen ACCESS_TOKEN aufgerufen werden können. 

===== /search
Der *FHIR-Proxy* bietet über die Schnittstelle `FHIRDirectorySearchAPI` den Endpunkt `/search` an, um FHIR-Ressourcen zu suchen. Um den Endpunkt `/search` aufrufen zu können, wird ein `search-accesstoken` im Authorization Header benötigt. Eine beispielhafte Verwendung der Schnittstelle für die Suche von FHIR-Ressourcen ist in der link:https://github.com/gematik/api-vzd/blob/feature/gemILF_VZD_FHIR_Directory/docs/FHIR_VZD_HOWTO_Search.adoc[search API examples] beschrieben.

===== /owner
Der *FHIR-Proxy* bietet über die Schnittstelle `FHIRDirectoryOwnerAPI` den Endpunkt `/owner` an, um FHIR-Ressourcen zu suchen und eigene Einträge zu pflegen. Um den Endpunkt `/owner` aufrufen zu können, wird ein `owner-accesstoken` im Authorization Header benötigt. Eine beispielhafte Verwendung der Schnittstelle zur Pflege der FHIR-Ressourcen ist in der link:https://github.com/gematik/api-vzd/blob/feature/gemILF_VZD_FHIR_Directory/docs/FHIR_VZD_HOWTO_Owner.adoc[owner API examples] beschrieben. 

=== Auth Modul
Über dieses abstrakte Modul wird die Kommunikation mit Smartcards (HBA) releasiert, um diese zur Authentisierung am  `/owner-authenticate`-Endpunkt zu ermöglichen. Dies wird als Grundlage für den Anwendungsfall link:docs/anwendungsfaelle/VZD-AF10058-practitioner-hinzufuegen.adoc[AF_10058 Akteur(User-HBA) im Verzeichnisdienst hinzufügen] benötigt. Im Folgenden wird der Prozess kurz skizziert, nachdem beim Aufruf der `/owner-authenticate`-Endpunktes der Redirect zum `Authorization Endpoint` des IDP-Dienstes zurückgegeben wurde. 

==== Authorization Endpoint IDP-Dienst
Der *TI-Messenger-Client* ruft den `{Authorization Endpoint}` am *zentralen IDP-Dienst* auf um das Challenge-Response-Verfahren durchzuführen und den `AuthorizationCode` sowie den Redirect zum Endpunkt `/signin-gematik-idp-dienst` zu erhalten. 

==== Signin-gematik-idp-dienst
An dem Endpunkt `/signin-gematik-idp-dienst` übergibt der *TI-Messenger-Client* den `AuthorizationCode` um sich ein `owner-accesstoken` ausstellen zu lassen. Der `AuthorizationCode` wird vom *Auth-Service* an den *zentralen-IDP-Dienst* weitergeleitet, um das für die passende Smartcard gehörende `ID_TOKEN` zu erhalten. Die darin enthaltenen `TelematikID` und `ProfessionOID` werden im Rahmen der Ausstllung des `owner-accesstoken` verwendet. 

=== Org-Admin Funktionalität
==== Auth owner-authenticate

==== Organisationsressourcen im VZD-FHIR-Directory bearbeiten


= Referenzierte Dokumente
Die nachfolgende Tabelle enthält die in der vorliegenden Online Dokumentation referenzierten Dokumente der gematik. Deren zu diesem Dokument jeweils gültige Versionsnummer entnehmen Sie bitte der aktuellen, auf der Internetseite der gematik veröffentlichten, Dokumentenlandkarte, in der die vorliegende Version aufgeführt wird.





|===
|[Quelle] |Herausgeber: Titel

|*[Client-Server API]* | https://spec.matrix.org/latest/client-server-api/
|*[API Playground]* | https://matrix.org/docs/api/#overview
|===
