@startuml
skinparam sequenceMessageAlign direction
skinparam minClassWidth 200
skinparam BoxPadding 1
skinparam sequenceReferenceHeaderBackgroundColor palegreen
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
'ParticipantFontName Impact
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20
'ActorFontName Aapex
}

autonumber
    
    actor v as "Versicherter"
    participant fdv as "Frontend des Versicherten"
    'box <size:18>Messenger-Service\n#WhiteSmoke
    participant pa as "Push-Anbieter"
    participant pg as "Push-Gateway"
    participant fd as "Fachdienst"
    'end box

|||
  activate fd
  v->fdv: installiert FdV auf dem Smartphone
  activate fdv
  fdv->pa: registriert sich beim Push-Anbieter
  activate pa
  pa-->fdv: :anbieterspezifisches AppToken
  deactivate pa
  fdv->fdv: speichere \nanbieterspezifisches AppToken
  fdv->fd: konfiguriere zu verwendendes Gateway(Gateway-Information, anbieterspezifisches AppToken)
  fd-->fdv: :Konfiguration übernommen
|||

  deactivate fd
  deactivate fdv
@enduml
