/' 
# TI-Messenger 1.1
# TI-Messenger-Dienst
# UC - XXX
# Sequence Diagram
# Name: Versichertenzugehörigkeit prüfen
'/

@startuml
skinparam sequenceMessageAlign direction
skinparam minClassWidth 200
skinparam BoxPadding 1
skinparam sequenceReferenceHeaderBackgroundColor palegreen
scale max 2048 width

skinparam sequence {
ArrowColor black
ArrowFontSize 17
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor Gainsboro

ParticipantBorderColor Motivation
ParticipantBackgroundColor Motivation
ParticipantFontSize 20
ParticipantFontColor black
ParticipantBorderColor Black
ParticipantBackgroundColor MOTIVATION

ActorBackgroundColor Gainsboro
ActorFontColor black
ActorFontSize 20

}

autonumber

    box <size:18>Messenger-Service\n#WhiteSmoke
    participant MP as "Messenger-Proxy"
    participant MH as "Matrix-Homeserver"
    end box


|||
Activate MP
MP->MP: prüfe den Sender und den Empfänger des Invite-Event\n auf Zugehörigkeit zu einer Versichertendomain 
|||
break #MistyRose <size:16>Sender und Empfänger sind beide Versicherte</size> 
MP->MP: <font color=red>HTTP 401 Unauthorized</font>
end

MP->MH: HTTP(S) Forward
Activate MH
MH-->MP: Status
Deactivate MH

@enduml
