ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images

image:gematik_logo.svg[width=70%]

=== AF_10104 Invitation of actors within an organisation
In this use case, an actor belonging to a common organisation is invited to a room to carry out actions. To search for actors within a common organisation, a TI-Messenger client searches its organisation's user directory on the Matrix home server. In this use case, the messenger proxy checks whether the Matrix domains contained in the Invite event are part of the TI federation (see Authorisation concept – Stage 1). If this is the case, it is forwarded to the corresponding Matrix home server. The latter checks whether the involved actors are registered with it. If this is not the case, the invited actor is not an actor within the organisation and the Invite event is forwarded to the Matrix home server of the invited actor. The use case "AF_10061 – Invitation of actors outside an organisation" shows the resulting course of events.

.use case description
[%collapsible%open]
====
[caption=]
Invitation of actors within an organisation
[%header, cols="1,1"]
|===
| |description
|Actor |Service provider, employee of an organisation in the "User/User-HBA" role
|Trigger |Actor A wants to invite actor B of their organisation to a shared space.
|Components a|
              * TI-Messenger-Client A + B,
              * Messenger proxy,
              * Messenger home server, 
              * Push gateway
|Preconditions a| 
                  * The actors are logged in to the same messenger service.
                  * Each actor has an approved TI-Messenger client.
                  *	A chat room has been set up by the inviter.
|Input data | Matrix Invite Event
|Result a| Actor A and actor B are both in a shared chat room.
           Optionally, a notification is sent to actor B about the invitation to the chat room.
|Output data |status
|===
====
.sequence diagram 
[%collapsible%open]
====
++++
<p align="center">
  <img width="55%" src=../../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10104_Seq.svg>
</p>
++++
====
