ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images
:toc: macro
:toclevels: 5
:toc-title: Inhaltsverzeichnis 
:numbered:

image:gematik_logo.svg[width=70%]



*AF_10103 - Authentication of an organisation on the TI-Messenger service* +

toc::[]

== Miscellaneous
In case the organization has never been authenticated at the registration service, this is the first step that has to be taken. First the user has to identify that he acts in place of a valid organization in the german healthcare system. For this, the possession of a valid SMC-B of the organization have to be proven. The following procedures may be used:

------
For organization verification

- 1. procedure) an unlocked SMC-B MUST be used when authenticating to the IDP service or +
- 2. procedure) a KIM message is sent to the address of the organization with the unlocked SMC-B.
------

In both cases, the Org-admin-client calls the `I_Registration` interface on the registration service. 

After a successful Authentication with the SMC-B an Admin Account can be created on the registration service and used to create a Messenger Service for the organization. 

CAUTION: 2-factor authentication must be used to authenticate the actor in the "Org Admin" role.

The use case is shown in the following sequence diagram.

== Sequence diagram
.sequence diagram
====
++++
<p align="center">
  <img width="75%" src=../../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10103_Seq.svg>
</p>
++++
====

== References

* https://fachportal.gematik.de/schnelleinstieg/smartcards-und-identitaeten-in-der-ti/smartcards/security-module-card-typ-b/security-module-card-fuer-organisationen[SMC-B ORG]

* https://fachportal.gematik.de/anwendungen/kommunikation-im-medizinwesen[KIM]
