ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images

image:gematik_logo.svg[width=70%]

=== AF_10103 Authentication of an organisation on the TI-Messenger service 
In case the organization has never been authenticated at the registration service, this is the first step that has to be taken. First the user has to identify that he acts in place of a valid organization in the german healthcare system. To do so the organization's SMC-B is needed to answer the authentication challenge of the central IDP-Service. 
Next to the SMC-B the user who is starting the process needs: 
[square]
* access to the frontend of the registration service
* the registration service frontend is registered at the central IDP-Service
* a connector that is connected to the gematik network
* a card terminal for the organization's SMC-B connected to the connector
* an authenticator is available for the data exchange with the connector 
* the SMC-B is plugged in the card terminal and unlocked
* a valid domain for the TI-Messenger-Dienst

After a successful Authentication with the SMC-B an Admin Account can be created and used to create a TI-Messenger Fachdienst for the organization. +

.use case description
[%collapsible%open]
====
[caption=]
.Authentication of an organisation on the TI-Messenger service
[%header, cols="1,1"]
|===
| |description
|Actor |Representative of an organisation in the "Org Admin" role
|Trigger |The administrator of the organisation (Org Admin) wants to make their organisation accessible by storing the MXIDs of the actors of the organisation in the VZD-FHIR directory.
|Components a|
              * TI-Messenger client (with advanced Org Admin functionality), 
              * Authenticator
              * IDP-Dienst
              * VZD Auth service
              * FHIR proxy
              * VZD-FHIR directory
|Preconditions a| 
                  * A messenger service was provided to the organisation and a FHIR resource was created in the VZD-FHIR directory.
                  * The organisation administrator has a TI-Messenger client (with advanced Org Admin functionality).
                  * The VZD-FHIR directory is registered with a responsible IDP service.
                  * The organisation administrator can authenticate themselves using a responsible IDP service.
|Input data |SMC-B, FHIR organisation resources
|Result |FHIR organisation resources updated, status
|Output data |Updated VZD-FHIR directory records 
|===
====

.sequence diagram
[%collapsible%open]
====
++++
<p align="center">
  <img width="75%" src=../../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10103_Seq.svg>
</p>
++++
====