ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images

image:gematik_logo.svg[width=70%]

===  Update federation list
The following figures describe how the messenger proxy updates its locally maintained federation list. To update the federation list, the messenger proxy MUST request it from the registration service of its TI-Messenger specialist service. The frequency of requesting a new list is determined by the provider, the goal should be to have a federation list as up-to-date as possible (but at least once a day). Here, the messenger proxy transfers the saved version of the federation list to the registration service. If the version matches, no new federation list will be provided by the registration service for the messenger proxy. If the version is larger than the one passed by the messenger proxy, an updated federation list is provided by the registration service. A download of the federation list is only necessary if a newer version exists on the FHIR proxy. The structure of the federation list is described by https://github.com/gematik/api-vzd/blob/develop/src/schema/FederationList.json[this JSON Schema definition]. After retrieving the federation list from the registration service, through the messenger proxy, the messenger proxy MUST check the signature of the federation list.

The registration service MUST regularly check the up-to-dateness of the federation list in the VZD-FHIR directory every hour. If the VZD-FHIR directory cannot be reached within a defined response time and further update attempts are also unsuccessful (`HealthState_VZD` and `HealthStateCheck_VZD`), the registration service MUST extend its own retention time of the federation list to a specified value of 48 hours (`TTL_Federationsliste`) and an incident event SHOULD be created, that can be catched by a third-party system (e.g. an ITSM system).

As soon as the messenger proxy initiates a request to update the federation list at the registration service, the registration service MUST fetch the current list from the FHIR proxy if the list held by the registration service is too old (`Alter_Föderationsliste`). If the list of the registration service is not too old, its federation list MUST be delivered to the messenger proxy. However, this only happens if the registration service's list is more up-to-date than that of the messenger proxy. If the messenger proxy receives an up-to-date federation list, a signature check MUST be carried out locally using the supplied signature certificate. The signing certificate is the first element from the x5c certificate list - transmitted together with the federation list.

In order to retrieve the federation list, the registration service needs to be authorized by a `provider-accesstoken`. Prior authentication involving the OAuth2 client credentials flow is required for the registration service to access the VZD-FHIR directory via the `/tim-provider-services` interface of the FHIR proxy. The TI messenger provider MUST apply for the necessary client credentials for his registration service from the VZD-FHIR directory provider. The request is made via a service request in the TI-ITSM system. After successful authentication, the registration service receives a `provider-accesstoken`, which MUST be included when the `/tim-provider-services` interface is called. The authentication process consists of the successive calls of the operations `/token` on the Auth-Service VZD on the one hand and `/ti-provider-authenticate` on the other hand. The client credentials are passed on the first operation call, and an IDP-TI-provider-accesstoken on the second call.

The interface `/tim-provider-services` (abstract unique name: https://raw.githubusercontent.com/gematik/api-vzd/develop/src/openapi/I_VZD_TIM_Provider_Services.yaml[`I_VZD_TIM_Provider_Services`]) MUST be used in version 1.2.0.

The runtime view of the federation list update process below defines the following types, which MUST be maintained at the registration service.

[caption=]
Types that MUST be maintained at the registration service
[%header, cols="1,1,2,1"]
|===
|name|type|description|value range
|`HealthState_VZD`|state|Type maintains the health state of components of the VZD-FHIR directory based on their response behavior|[gesund, ungesund]
|`HealthStateCheck_VZD`|upcounting iterator|Type holds the number of retries of the health status check of the VZD-FHIR directory|0\<= `HealthStateCheck_VZD`\<=3
|`Alter_Föderationsliste`|upcounting timer|Type keeps the current age of the federation list as of the time of the last update|min: 0s
|`TTL_Föderationsliste`|lifespan|Type describes the upper limit that a federation list can be old|fixed value: 48h
|===



.use case description
[%collapsible%open]
====
[caption=]
update of the federation list
[%header, cols="1,2"]
|===
| |description
|Actor |System
|Trigger a|
            * Scheduler
            * Interface call
|Components a|
              * Messenger proxy (standardized name: Messenger-Proxy),
              * Registration service (standardized name: Registrierungs-Dienst),
              * FHIR proxy (standardized name: FHIR-Proxy)
              * Auth-Service VZD (standardized name: OAuth-Service)
|Preconditions a| none
|Input data | version number
|Result a|The messenger proxy retrieves a status if the current list is not outdated or a new federation list in case the proxy owns an older one
|Output data |status values, federation list, x5c-certificate list
|===
====
.main sequence diagram "Föderationsliste aktualisieren"
[%collapsible%open]
====
++++
<p align="center">
  <img width="60%" src=../../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_Update_Federationlist_Seq.svg>
</p>
++++
====

.referenced sub-sequence diagram "Provider authentifizieren und Föderationsliste abrufen"
[%collapsible%open]
====
++++
<p align="center">
  <img width="60%" src=../../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_Update_Federationlist_auth_retrieve.svg>
</p>
++++
====

.referenced sub-sequence diagram "Signatur der Föderationsliste prüfen"
[%collapsible%open]
====
++++
<p align="center">
  <img width="40%" src=../../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_Update_Federationlist_SignCheck.svg>
</p>
++++
====
