ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images

image:gematik_logo.svg[width=70%]

=== AF_10059 Add organisation resources to directory service
With the aquisition of the SMC-B an entry for the organisation will be created in the VZD-FHIR directory by the [TODO]. 

.use case description
[%collapsible%open]
====
[caption=]
Add organisation resources to directory service
[%header, cols="1,1"]
|===
| |description
|Actor |Representative of an organisation in the "Org Admin" role
|Trigger |An organisation of the German healthcare system wants to participate in the TI-Messenger service and needs to provide one or more messenger services
|Components a|
              * Front end of the registration service, 
              * Registrierungs-Dienst, 
              * VZD-FHIR directory,
              * Messenger-Service 
|Preconditions a| 
                  * There is a contractual relationship with a TI-Messenger provider. 
                  * The operator has a front end of the registration service for communication with the registration service.
                  * The used front end of the registration service is registered with the responsible IDP service.
                  * The SMC-B inserted in the eHealth card terminal is enabled.
                  * The registration service can authenticate itself with the VZD-FHIR directory server for write access
                    with OAuth2.
|Input data |Admin account, identity of organisation (SMC-B)
|Result a|
            * The messenger service for the organisation has been created.
            * The Matrix domain of the new messenger service was entered as an endpoint in the VZD-FHIR directory and  
              included in the federation.
|Output data |New messenger service for the organisation, status
|===
====

.sequence diagram 
[%collapsible%open]
====
++++
<p align="center">
  <img width="60%" src=../../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10059_Seq.svg>
</p>
++++
====