ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../../images

image:gematik_logo.svg[width=70%]

=== AF_10059 Add organization resources to directory service
With this use case, an actor in the role of "Org-Admin" makes actors of his organization discoverable and reachable for other actors in the TI Messenger service. For this purpose, FHIR endpoint resources with the MXID are stored in the organization directory (HealthcareService) of the VZD FHIR directory. Organizations CAN administer several FHIR resources per organization and thus structure incoming communication processes organizationally and thematically (see [gemSpec_VZD_FHIR_Directory]).

.use case description
[%collapsible%open]
====
[caption=]
Add organization resources to directory service
[%header, cols="1,1"]
|===
| |description
|Actor |Representative of an organisation in the "Org Admin" role
|Trigger |The administrator of the organization (Org-Admin) wants to make his organization accessible by storing the MXIDs of the actors of the organization in the VZD-FHIR directory.
|Components a|
              * TI-Messenger-Client with Org-Admin-Funktionality
              * TI-Messenger Registration Service
              * Auth-Service 
              * FHIR-Proxy
              * FHIR-Directory
|Preconditions a| 
                  * A messenger service has been provided for the organization and an entry of the organization exists in the FHIR directory 
                  * The organization's administrator has a TI Messenger client (with enhanced Org Admin functionality). 
                  * A trust relationship exists between TI-Messenger registration service and the FHIR directory
                  * The organization's administrator can authenticate at its responsible IDP service registration service.
|Input data |FHIR organization ressources
|Result a|
            updated FHIR organization ressources, status
|Output data | updated FHIR organization ressources
|===
====

.sequence diagram 
[%collapsible%open]
====
++++
<p align="center">
  <img width="60%" src=../../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10059_Seq.svg>
</p>
++++
====