name: Lint PlantUML

runs:
  using: "composite"
  steps:
    - name: Verify absence of output file names
      run: |
        function err {
          >&2 echo -e "\033[0;31m$@\033[0m"
        }

        rc=0

        while read -r file; do
          echo "Checking $file"

          if grep -qE "^@startuml\s+." "$file"; then
            err "$file contains forbidden output name in @startuml"
            rc=1
          fi
        done < <(find . -name "*.puml")

        exit $rc
