name: Lint JSON Schema

runs:
  using: "composite"
  steps:
    - name: Set up check-jsonschema
      shell: bash
      run: |
        pip install check-jsonschema

    - name: Set up environment
      shell: bash
      run: |
        # Sadly, composite actions currently don't support environment variables so we freestyle a replacement
        echo 'SCHEMAS_ROOT=src/schema' >> .gha-env
        echo 'EXAMPLES_ROOT=src/schema/examples' >> .gha-env

    - name: Verify schemas
      shell: bash
      run: |
        source .gha-env

        # We handle the return code ourselves to prevent the action from exiting on the first error
        rc=0

        while read -r file; do
          echo "Validating $file"
          if ! check-jsonschema --check-metaschema "$file"; then
            rc=1
          fi
        done < <(find "$SCHEMAS_ROOT" -name "*.json" -maxdepth 1)

        exit $rc

    - name: Verify examples
      shell: bash
      run: |
        source .gha-env

        # We handle the return code ourselves to prevent the action from exiting on the first error
        rc=0

        while read -r file; do
          schema=$(basename "$file")
          schema=$SCHEMAS_ROOT/${schema%%.*}.json
          echo "Validating $file against $schema"
          if ! check-jsonschema --schemafile "$schema" "$file"; then
            rc=1
          fi
        done < <(find "$EXAMPLES_ROOT" -name "*.json")

        exit $rc
