ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../images
:toc: macro
:toclevels: 5
:toc-title: Table of Contents
:numbered:

image:gematik_logo.svg[width=70%]

toc::[]

= VZD-FHIR-Directory
Beim *VZD-FHIR-Directory* handelt es sich um einen zentralen Verzeichnisdient der TI. Im Rahmen des *TI-Messenger-Dienstes* wird das *VZD-FHIR-Directory* für die deutschlandweite Suche von Organisationen und Akteuren sowie der Bereitstellung einer sektorenübergreifende Kommunikation, verwendet. 

Dabei besteht das *VZD-FHIR-Directory* aus den Teilkomponenten:

* FHIR-Directory, 
* OAuth-Service,
* Auth-Service und
* FHIR-Proxy

die benötigt werden, um alle Funktionsmerkmale abbilden zu können.

In der folgenden Abbildung sind die Teilkomponenten sowie deren Schnittstellen und für deren Zugriff benötigten ACCESS_TOKEN dargestellt:

++++
<p align="left">
  <img width="100%" src=../images/I_VZD_FHIR_Directory.png>
</p>
++++

== FHIR-Directory / Verzeichnistypen
Das *FHIR-Directory* basiert auf link:https://hl7.org/fhir/R4/[FHIR R4] und stellt die zwei Verzeichnisse `HealthcareServiceDirectory`- und `PractitionerRoleDirectory` bereit. Die Profilierung der FHIR-Ressourcen ist im link:https://simplifier.net/vzd-fhir-directory[Simplifier] aufrufbar. 

Im folgenden sind die beiden Verzeichnisse mit deren Struktur beispielhaft dargestellt: 

* HealthcareService

++++
<p align="left">
  <img width="60%" src=https://raw.githubusercontent.com/gematik/api-vzd/main/images/diagrams/ObjectDiagram.HealthcareService.svg>
</p>
++++

* PractitionerRole

++++
<p align="left">
  <img width="60%" src=https://raw.githubusercontent.com/gematik/api-vzd/main/images/diagrams/ObjectDiagram.PractitionerRole.svg>
</p>
++++

Im Rahmen des TI-Messenger-Dienstes sollen die folgenden Attribute eines Endpoints eines `HealthcareService` oder `PractitionerRole` wie folgt gesetzt werden:

[options="header"]
|=================================================================================================================
| Attribut                | Wert          | Beschreibung                                      
| `endpoint.status`         | `active`        | Sichtbarkeit des Endpunktes im Verzeichnisidienst 
| `endpoint.connectionType` | `tim`           | Gibt an, um welche Anwendung es sich handelt      
| `endpoint.name`          | `<Bezeichnung>` | Identifier des Endpoints                          
| `endpoint.PayloadType`    | `tim-chat`      | Kennung der Übertragenen Inhalte                  
| `endpoint.address`        |`MXID`          | Matrix-UserID eines Akteurs                       
|=================================================================================================================

Beispiel: * `HealthcareService.endpoint.address = <MXID>`

Weitere Informationen zu den Verzeichnistypen können link:https://github.com/gematik/api-vzd/blob/main/docs/Fachkonzept_FHIR-Directory.adoc#datenstruktur-im-fhir-directory[hier] nachgelesen werden. 

== OAuth-Service
Der *OAuth-Service* stellt ein `ti-provider-accesstoken` aus, welches am `/ti-provider-authenticate`-Endpunkt übergeben werden muss. Hierfür muss sich ein Anbieter eines *TI-Messenger-Fachdienstes* mittels seiner Zugangsdaten am OAuth-Service authentisieren. 

== Auth-Service
Der *Auth-Service* stellt ACCESS_TOKEN aus, die für den Zugriff auf die Endpunkte am *FHIR-Proxy* benötigt werden. Der Aufruf der link:https://github.com/gematik/api-vzd/blob/feature/gemILF_VZD_FHIR_Directory/docs/FHIR_VZD_HOWTO_Authenticate.adoc#2-fhirdirectoryauthenticationapis[Endpunkte] am *Auth-Service* ist dort beschrieben. 

== FHIR-Proxy
Der *FHIR-Proxy* gibt Zugriff auf das *FHIR-Directory* unter Vorlage eines validen ACCESS_TOKEN und somit auf die FHIR-Ressourcen. Die vom *FHIR-Proxy* zur Verfügung gestellten Endpunkte werden für die Suche und Pflege von FHIR-Ressourcen verwendet sowie zur Pflege eigener TIM Provider Einträge. Der Aufruf der Endpunkte am *FHIR-Proxy* sind hier bechrieben:

* https://github.com/gematik/api-vzd/blob/feature/gemILF_VZD_FHIR_Directory/docs/FHIR_VZD_HOWTO_Search.adoc#21-fhirdirectorysearchapi-search-for-practitioners-and-organizations[/search]
* https://github.com/gematik/api-vzd/blob/feature/gemILF_VZD_FHIR_Directory/docs/FHIR_VZD_HOWTO_Owner.adoc#2-fhirdirectoryownerapi[/owner]
* https://github.com/gematik/api-vzd/blob/feature/gemILF_VZD_FHIR_Directory/docs/FHIR_VZD_HOWTO_Provider.adoc#2-fhirdirectoryproviderapi[/tim-provider-services]

IMPORTANT: Volltextsuche wird aktuell nicht vom *VZD-FHIR-Directory* unterstützt. Hierfür können die folgenden RegEx *_text* and *_content* verwendet werden. Für mehr Informationen kann die folgende  link:http://hl7.org/fhir/R4/search.html#content[Dokumentation] verwendet werden. 








