= FHIR-Directory Owner-API
:source-highlighter: highlight.js
ifdef::env-github[]
:toc: preamble
endif::[]
ifndef::env-github[]
:toc: left
endif::[]
:toclevels: 3
:toc-title: Table of content

The FHIR-Directory contains entries for healthcare services provided by organizations as well as practitioner entries. Both types of entries can be changed by using the FHIR-Directory /owner endpoint. The ways to authenticate differ depending on the entry type. The https://fachportal.gematik.de/fachportal-import/files/gemSpec_VZD_FHIR_Directory_V1.1.0.pdf[specification of the FHIR-Directory] contains information about the endpoint and authentication methods.

The FHIR profiles are defined in the https://simplifier.net/vzd-fhir-directory[FHIR-Directory Simplifier project].

== Organization entry

An organization entry has the following structure.

image:https://raw.githubusercontent.com/gematik/api-vzd/main/images/diagrams/ObjectDiagram.HealthcareService.svg[Organization entry]

=== Authentication

The /owner endpoint requires a valid jwt in the Authorization header. In order to get the jwt the following steps must be performed.

.*1. Login to the TI-Messenger Registrierungsdienst as Org-Admin*

This is a proprietary interface. Only healthcare organizations are permitted to take part in the TI-Messenger federation. Each TI-Messenger provider implements a way to authenticate a healthcare organization with OIDC and OAuth2. After the successful authentication the healthcare organization may create Org-Admin Accounts on the Registrierungsdienst.

.*2. Get the Registrierungsdienst token*

After login the Org-Admin requests a token from the Registrierungsdienst.

.*3. Get the jwt from the /owner-authenticate endpoint*
[%collapsible]
====
[source,]
----
REQUEST
GET https://fhir-directory-test.vzd.ti-dienste.de/owner-authenticate
HEADER
{"User-Agent"=>"Faraday v2.6.0", "Content-Type"=>"application/json", "X-RegService-Token"=>"registration-service-token", "X-Registration-Server-Name"=>"registration-service.dev.service-ti.de"}

RESPONSE
STATUS 200
HEADER
{"date"=>"Thu, 27 Oct 2022 09:22:38 GMT", "server"=>"Apache", "etag"=>"\"002d6050a8c142c91e88dc2d7ef4e3fbf\"", "content-type"=>"application/json", "content-length"=>"453"}
BODY
{
  "jwt": "owner-authenticate-token",
  "token_type": "bearer",
  "expires_in": 86400
}
----
====

== Practitioner entry

A practitioner entry has the following structure.

image:https://raw.githubusercontent.com/gematik/api-vzd/main/images/diagrams/ObjectDiagram.PractitionerRole.svg[Practitioner entry]

=== Authentication
