ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../images
:toc: macro
:toclevels: 5
:toc-title: Inhaltsverzeichnis
:numbered:

image:gematik_logo.svg[width=70%]

toc::[]

= VZD-FHIR-Directory
The FHIR-Directory contains entries for healthcare services provided by organizations as well as practitioner entries. This page describes how to use the FHIR-Directory endpoints. See more information in https://fachportal.gematik.de/fachportal-import/files/gemSpec_VZD_FHIR_Directory_V1.1.0.pdf[[gemSpec_VZD_FHIR_Directory]].  It contains information about the endpoints and authentication methods.

++++
<p align="left">
  <img width="75%" src=../images/I_VZD_FHIR_Directory.png>
</p>
++++

== FHIR Profiles
The FHIR Profiles are defined in the Simplifier project https://simplifier.net/vzd-fhir-directory[VZD-FHIR-Directory]. 

TIP: In generell FHIR allows various search capabilities. The https://www.hl7.org/fhir/search.html[FHIR search] page describes in detail the search framework.

== REST Service Endpoints
The VZD-FHIR-Directory provides three endpoints: +

* `/search`, 
* `/owner` and 
* `tim-provider-services`. 

=== Endpoint: /search
==== Authentication
The */search* endpoint requires a valid JSON Web Token (`tim-authenticate-token`) in the Authorization header. To get the token you need a valid `matrix-openid-token` from a permitted matrix-homeserver. With the `matrix-openid-token` you can get the `tim-authenticate-token` from the */tim-authenticate* endpoint from the VZD-FHIR-Directory Auth Service. The following example shows the call to the */tim-authenticate* endpoint to get the token.

*REQUEST*
[source, bash]
-----------------
GET https://fhir-directory-test.vzd.ti-dienste.de/tim-authenticate?mxId=matrix.dev.service-ti.de
-----------------

====
[source,yaml]
----
HEADER
{
  "User-Agent": "Faraday v2.6.0", 
  "Content-Type": "application/json", 
  "X-Matrix-OpenID-Token": "matrix-openid-token", 
  "X-Matrix-Server-Name": "matrix.dev.service-ti.de"
}
----
====

*RESPONSE*
[source, yaml]
-----------------
STATUS 200
HEADER
{
  "date": "Thu, 27 Oct 2022 09:22:38 GMT", 
  "server": "Apache", "etag"=>"\"002d6050a8c142c91e88dc2d7ef4e3fbf\"", 
  "content-type": "application/json", 
  "content-length": "453"
}
BODY
{
  "jwt": "tim-authenticate-token",
  "token_type": "bearer",
  "expires_in": 86400
}
-----------------
 
TIP: The Response Body from the */tim-authenticate* endpoint contains the necessary JSON Web Token `jwt": "tim-authenticate-token`

==== FHIR /search Request
It is important to understand how the entries in the FHIR-Directory are structured. The FHIR-Directory has two kinds of entries.
An organization entry has the following structure.

++++
<p align="left">
  <img width="50%" src=https://raw.githubusercontent.com/gematik/api-vzd/main/images/diagrams/ObjectDiagram.HealthcareService.svg>
</p>
++++

A practitioner entry has a similar structure.

++++
<p align="left">
  <img width="50%" src=https://raw.githubusercontent.com/gematik/api-vzd/main/images/diagrams/ObjectDiagram.PractitionerRole.svg>
</p>
++++

Please refer to the https://www.hl7.org/fhir/healthcareservice.html#search[HL7 FHIR documentation] to find the possible search parameters of each FHIR ressource.

If the goal of the search are organization entries then the search must start with */search/HealthcareService*. If practitioner entries are searched the search must start with */search/PractitionerRole*. In addition the FHIR-Directory /search endpoint verifies that only active organization entries or active practitioner entries are requested. Therefore the search must include a *organization.active=true* or a *practitioner.active=true* filter.

The search response should include the referenced ressources (search parameter *_include=**).

The matrix addresses of other users (mxid) are saved in HealthcareService.endpoint.address. The Endpoint ressource contains the mxid of a user or of a bot. Only active endpoints should be used (search parameter *endpoint.status=active*).

The FHIR Endpoint ressources are also used for other TI Applications e.g. https://github.com/gematik/api-kim[KIM]. For TI-Messenger Clients it is recommended to use a search parameter *endpoint.connection-type=tim*. This way only Endpoints with TI-Messenger addresses are found.

.*FHIR /search Request*
====
[source,]
----
REQUEST
GET https://fhir-directory-test.vzd.ti-dienste.de/search/HealthcareService?organization.active=true&endpoint.status=active&_include=*&_count=2&_pretty=true
HEADER
{"User-Agent"=>"Faraday v2.6.0", "Content-Type"=>"application/json", "Authorization"=>"Bearer tim-authenticate-token"}

RESPONSE
STATUS 200
HEADER
{"date"=>"Thu, 27 Oct 2022 09:22:39 GMT", "server"=>"Apache", "x-powered-by"=>"HAPI FHIR 5.6.0 REST Server (FHIR Server; FHIR 4.0.1/R4)", "x-request-id"=>"nkJjjcDy5kUgp3pS", "last-modified"=>"Thu, 27 Oct 2022 09:22:39 GMT", "content-type"=>"application/fhir+json;charset=UTF-8", "transfer-encoding"=>"chunked"}
BODY
{
  "resourceType": "Bundle",
  "id": "0bd92f43-f603-4aab-b821-75043768da2c",
  "meta": {
    "lastUpdated": "2022-10-27T11:22:39.178+02:00"
  },
  "type": "searchset",
  "total": 2,
  "entry": 
  [
    {
      ...
      ...
      ...
     }
  ]
     
----
====

==== Display search results

The results of the search are summarized in a json FHIR Bundle structure. Each entry of the Bundle contains a FHIR ressource. The https://simplifier.net/VZD-FHIR-Directory/~introduction[FHIR-Directory simplifier page] specifies the _must support_ elements of the FHIR ressources. It is recommended to display at least those elements of the search results.

TIP: The search results can also contain FHIR data which is not marked as _must support_.

==== Full text search

IMPORTANT: Full text search is not yet supported by the FHIR-Directory

The search parameters, *_text* and *_content*, are used for full text search.


=== Owner-API

=== Owner-API

