ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../images
:toc: macro
:toclevels: 5
:toc-title: Inhaltsverzeichnis
:numbered:

image:gematik_logo.svg[width=70%]

toc::[]

= VZD-FHIR-Directory
The FHIR-Directory contains entries for healthcare services provided by organizations as well as practitioner entries. This page describes how to use the FHIR-Directory endpoints. See more information in https://fachportal.gematik.de/fachportal-import/files/gemSpec_VZD_FHIR_Directory_V1.1.0.pdf[[gemSpec_VZD_FHIR_Directory]].  It contains information about the endpoints and authentication methods.

== FHIR Profiles
The FHIR Profiles are defined in the Simplifier project https://simplifier.net/vzd-fhir-directory[VZD-FHIR-Directory]. 

TIP: In generell FHIR allows various search capabilities. The https://www.hl7.org/fhir/search.html[FHIR search] page describes in detail the search framework.

== Interfaces
=== Search-API

==== Authentication
The `/search` endpoint requires a valid jwt in the Authorization header. In order to get the jwt the following steps must be performed.

.*1. Login to the matrix homeserver*
====
[source,]
----
REQUEST
POST https://matrix.dev.service-ti.de/_matrix/client/r0/login
HEADER
{"User-Agent"=>"Faraday v2.6.0", "Content-Type"=>"application/json"}
BODY
{"type":"m.login.password","user":"@user:matrix.dev.service-ti.de","password":"password"}

RESPONSE
STATUS 200
HEADER
{"date"=>"Thu, 27 Oct 2022 09:16:30 GMT", "server"=>"Synapse/1.53.0", "content-type"=>"application/json", "cache-control"=>"no-cache, no-store, must-revalidate", "access-control-allow-origin"=>"*", "access-control-allow-methods"=>"GET, HEAD, POST, PUT, DELETE, OPTIONS", "access-control-allow-headers"=>"X-Requested-With, Content-Type, Authorization, Date", "transfer-encoding"=>"chunked"}
BODY
{
  "user_id": "@user:matrix.dev.service-ti.de",
  "access_token": "matrix-accesstoken",
  "home_server": "matrix.dev.service-ti.de",
  "device_id": "SRCDQZFMLS"
}
----
====

.*2. Get the Matrix OpenID Token*
====
[source,]
----
REQUEST
POST https://matrix.dev.service-ti.de/_matrix/client/v3/user/@ettr02:matrix.dev.service-ti.de/openid/request_token?access_token=matrix-accesstoken
HEADER
{"User-Agent"=>"Faraday v2.6.0", "Content-Type"=>"application/json"}
BODY
{}

RESPONSE
STATUS 200
HEADER
{"date"=>"Thu, 27 Oct 2022 09:16:30 GMT", "server"=>"Synapse/1.53.0", "content-type"=>"application/json", "cache-control"=>"no-cache, no-store, must-revalidate", "access-control-allow-origin"=>"*", "access-control-allow-methods"=>"GET, HEAD, POST, PUT, DELETE, OPTIONS", "access-control-allow-headers"=>"X-Requested-With, Content-Type, Authorization, Date", "transfer-encoding"=>"chunked"}
BODY
{
  "access_token": "matrix-openid-token",
  "token_type": "Bearer",
  "matrix_server_name": "matrix.dev.service-ti.de",
  "expires_in": 3600
}
----
====

.*3. Get the jwt from the /tim-authenticate endpoint*
====
[source,]
----
REQUEST
GET https://fhir-directory-test.vzd.ti-dienste.de/tim-authenticate?mxId=matrix.dev.service-ti.de
HEADER
{"User-Agent"=>"Faraday v2.6.0", "Content-Type"=>"application/json", "X-Matrix-OpenID-Token"=>"matrix-openid-token", "X-Matrix-Server-Name"=>"matrix.dev.service-ti.de"}

RESPONSE
STATUS 200
HEADER
{"date"=>"Thu, 27 Oct 2022 09:22:38 GMT", "server"=>"Apache", "etag"=>"\"002d6050a8c142c91e88dc2d7ef4e3fbf\"", "content-type"=>"application/json", "content-length"=>"453"}
BODY
{
  "jwt": "tim-authenticate-token",
  "token_type": "bearer",
  "expires_in": 86400
}
----
====

==== FHIR /search Request
It is important to understand how the entries in the FHIR-Directory are structured. The FHIR-Directory has two kinds of entries.
An organization entry has the following structure.

++++
<p align="left">
  <img width="50%" src=https://raw.githubusercontent.com/gematik/api-vzd/main/images/diagrams/ObjectDiagram.HealthcareService.svg>
</p>
++++

A practitioner entry has a similar structure.

++++
<p align="left">
  <img width="50%" src=https://raw.githubusercontent.com/gematik/api-vzd/main/images/diagrams/ObjectDiagram.PractitionerRole.svg>
</p>
++++

Please refer to the https://www.hl7.org/fhir/healthcareservice.html#search[HL7 FHIR documentation] to find the possible search parameters of each FHIR ressource.

If the goal of the search are organization entries then the search must start with */search/HealthcareService*. If practitioner entries are searched the search must start with */search/PractitionerRole*. In addition the FHIR-Directory /search endpoint verifies that only active organization entries or active practitioner entries are requested. Therefore the search must include a *organization.active=true* or a *practitioner.active=true* filter.

The search response should include the referenced ressources (search parameter *_include=**).

The matrix addresses of other users (mxid) are saved in HealthcareService.endpoint.address. The Endpoint ressource contains the mxid of a user or of a bot. Only active endpoints should be used (search parameter *endpoint.status=active*).

The FHIR Endpoint ressources are also used for other TI Applications e.g. https://github.com/gematik/api-kim[KIM]. For TI-Messenger Clients it is recommended to use a search parameter *endpoint.connection-type=tim*. This way only Endpoints with TI-Messenger addresses are found.

.*FHIR /search Request*
====
[source,]
----
REQUEST
GET https://fhir-directory-test.vzd.ti-dienste.de/search/HealthcareService?organization.active=true&endpoint.status=active&_include=*&_count=2&_pretty=true
HEADER
{"User-Agent"=>"Faraday v2.6.0", "Content-Type"=>"application/json", "Authorization"=>"Bearer tim-authenticate-token"}

RESPONSE
STATUS 200
HEADER
{"date"=>"Thu, 27 Oct 2022 09:22:39 GMT", "server"=>"Apache", "x-powered-by"=>"HAPI FHIR 5.6.0 REST Server (FHIR Server; FHIR 4.0.1/R4)", "x-request-id"=>"nkJjjcDy5kUgp3pS", "last-modified"=>"Thu, 27 Oct 2022 09:22:39 GMT", "content-type"=>"application/fhir+json;charset=UTF-8", "transfer-encoding"=>"chunked"}
BODY
{
  "resourceType": "Bundle",
  "id": "0bd92f43-f603-4aab-b821-75043768da2c",
  "meta": {
    "lastUpdated": "2022-10-27T11:22:39.178+02:00"
  },
  "type": "searchset",
  "total": 2,
  "entry": [
    {
      "fullUrl": "https://fhir-directory-test.vzd.ti-dienste.de/search/HealthcareService/2667022",
      "resource": {
        "resourceType": "HealthcareService",
        "id": "2667022",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2022-08-31T17:46:52.145+02:00",
          "source": "#WEHMezg1dNw2bkoR",
          "profile": [
            "https://gematik.de/fhir/directory/StructureDefinition/HealthcareServiceDirectory",
            "http://hl7.org/fhir/StructureDefinition/HealthcareService"
          ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by Arvato QA at 2022-08-31T17:46:52+02:00\ndata model version:2\nprofile version   :0.8.0-beta6</div>"
        },
        "identifier": [
          {
            "system": "http://hl7.org/fhir/sid/us-npi",
            "value": "53a0664e-b434-46d7-92de-cbe7da253a50"
          }
        ],
        "providedBy": {
          "reference": "Organization/2667019"
        },
        "location": [
          {
            "reference": "Location/2667021"
          }
        ],
        "endpoint": [
          {
            "reference": "Endpoint/2667020"
          }
        ]
      },
      "search": {
        "mode": "match"
      }
    },
    {
      "fullUrl": "https://fhir-directory-test.vzd.ti-dienste.de/search/HealthcareService/2667036",
      "resource": {
        "resourceType": "HealthcareService",
        "id": "2667036",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2022-08-31T17:46:52.523+02:00",
          "source": "#0yLmT2BAs1qHE5Fw",
          "profile": [
            "https://gematik.de/fhir/directory/StructureDefinition/HealthcareServiceDirectory",
            "http://hl7.org/fhir/StructureDefinition/HealthcareService"
          ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by Arvato QA at 2022-08-31T17:46:52+02:00\ndata model version:2\nprofile version   :0.8.0-beta6</div>"
        },
        "identifier": [
          {
            "system": "http://hl7.org/fhir/sid/us-npi",
            "value": "8f7442e3-5c66-49bd-b99d-0c27f6ce4dcb"
          }
        ],
        "providedBy": {
          "reference": "Organization/2667033"
        },
        "specialty": [
          {
            "coding": [
              {
                "system": "urn:oid:1.3.6.1.4.1.19376.3.276.1.5.5",
                "code": "ERG",
                "display": "Ergotherapie"
              }
            ]
          },
          {
            "coding": [
              {
                "system": "urn:oid:1.3.6.1.4.1.19376.3.276.1.5.5",
                "code": "FOR",
                "display": "Forschung"
              }
            ]
          }
        ],
        "location": [
          {
            "reference": "Location/2667035"
          }
        ],
        "endpoint": [
          {
            "reference": "Endpoint/2667034"
          }
        ]
      },
      "search": {
        "mode": "match"
      }
    },
    {
      "fullUrl": "https://fhir-directory-test.vzd.ti-dienste.de/search/Organization/2667033",
      "resource": {
        "resourceType": "Organization",
        "id": "2667033",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2022-08-31T17:46:52.523+02:00",
          "source": "#0yLmT2BAs1qHE5Fw",
          "profile": [
            "https://gematik.de/fhir/directory/StructureDefinition/OrganizationDirectory",
            "http://hl7.org/fhir/StructureDefinition/Organization"
          ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by Arvato QA at 2022-08-31T17:46:52+02:00\ndata model version:2\nprofile version   :0.8.0-beta6</div>"
        },
        "identifier": [
          {
            "system": "http://hl7.org/fhir/sid/us-npi",
            "value": "7b3e6d7b-89be-47c9-b014-f9b4f2179a8e"
          },
          {
            "type": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "PRN"
                }
              ]
            },
            "system": "https://gematik.de/fhir/sid/telematik-id",
            "value": "1-2arvtst-ap000130"
          }
        ],
        "active": true,
        "type": [
          {
            "coding": [
              {
                "system": "https://gematik.de/fhir/directory/CodeSystem/OrganizationProfessionOID",
                "code": "1.2.276.0.76.4.244",
                "display": "Betriebsstätte der Kassenzahnärztlichen Bundesvereinigung"
              }
            ]
          }
        ],
        "name": "Organisation 1-2arvtst-ap000130",
        "alias": [
          "Organisation 1-2arvtst-ap000130"
        ]
      },
      "search": {
        "mode": "include"
      }
    },
    {
      "fullUrl": "https://fhir-directory-test.vzd.ti-dienste.de/search/Endpoint/2667034",
      "resource": {
        "resourceType": "Endpoint",
        "id": "2667034",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2022-08-31T17:46:52.523+02:00",
          "source": "#0yLmT2BAs1qHE5Fw",
          "profile": [
            "https://gematik.de/fhir/directory/StructureDefinition/EndpointDirectory",
            "http://hl7.org/fhir/StructureDefinition/Endpoint"
          ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by Arvato QA at 2022-08-31T17:46:52+02:00\ndata model version:2\nprofile version   :0.8.0-beta6</div>"
        },
        "identifier": [
          {
            "system": "http://hl7.org/fhir/sid/us-npi",
            "value": "546aa01e-1e90-4f94-8940-2e8e60c799ed"
          }
        ],
        "status": "active",
        "connectionType": {
          "system": "https://gematik.de/fhir/directory/CodeSystem/EndpointDirectoryConnectionType",
          "code": "tim"
        },
        "name": "MatrixId von Organisation 1-2arvtst-ap000130 (@1-2arvtst-ap000130:tim.test.gematik.de)",
        "payloadType": [
          {
            "coding": [
              {
                "system": "https://gematik.de/fhir/directory/CodeSystem/EndpointDirectoryPayloadType",
                "code": "tim-chat",
                "display": "TI-Messenger chat"
              }
            ]
          }
        ],
        "address": "@1-2arvtst-ap000130:tim.test.gematik.de"
      },
      "search": {
        "mode": "include"
      }
    },
    {
      "fullUrl": "https://fhir-directory-test.vzd.ti-dienste.de/search/Organization/2667019",
      "resource": {
        "resourceType": "Organization",
        "id": "2667019",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2022-08-31T17:46:52.145+02:00",
          "source": "#WEHMezg1dNw2bkoR",
          "profile": [
            "https://gematik.de/fhir/directory/StructureDefinition/OrganizationDirectory",
            "http://hl7.org/fhir/StructureDefinition/Organization"
          ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by Arvato QA at 2022-08-31T17:46:51+02:00\ndata model version:2\nprofile version   :0.8.0-beta6</div>"
        },
        "identifier": [
          {
            "system": "http://hl7.org/fhir/sid/us-npi",
            "value": "b52f6831-0a71-41f8-8110-5dcec2a5fa2f"
          },
          {
            "type": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "PRN"
                }
              ]
            },
            "system": "https://gematik.de/fhir/sid/telematik-id",
            "value": "1-2arvtst-ap000129"
          }
        ],
        "active": true,
        "type": [
          {
            "coding": [
              {
                "system": "https://gematik.de/fhir/directory/CodeSystem/OrganizationProfessionOID",
                "code": "1.2.276.0.76.4.52",
                "display": "Betriebsstätte Psychotherapeut"
              }
            ]
          }
        ],
        "name": "Organisation 1-2arvtst-ap000129",
        "alias": [
          "Organisation 1-2arvtst-ap000129"
        ]
      },
      "search": {
        "mode": "include"
      }
    },
    {
      "fullUrl": "https://fhir-directory-test.vzd.ti-dienste.de/search/Location/2667035",
      "resource": {
        "resourceType": "Location",
        "id": "2667035",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2022-08-31T17:46:52.523+02:00",
          "source": "#0yLmT2BAs1qHE5Fw",
          "profile": [
            "https://gematik.de/fhir/directory/StructureDefinition/LocationDirectory",
            "http://hl7.org/fhir/StructureDefinition/Location"
          ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by Arvato QA at 2022-08-31T17:46:52+02:00\ndata model version:2\nprofile version   :0.8.0-beta6</div>"
        },
        "identifier": [
          {
            "system": "http://hl7.org/fhir/sid/us-npi",
            "value": "583a39c5-a808-4448-a618-8a812e4037ce"
          }
        ],
        "name": "Location of Organisation 1-2arvtst-ap000130",
        "address": {
          "use": "work",
          "type": "postal",
          "text": "Peter-Hausmann-Platz 4&#13;&#10;53332&#13;&#10;Bornheim&#13;&#10;Nordrhein-Westfalen&#13;&#10;DE",
          "line": [
            "Peter-Hausmann-Platz 4"
          ],
          "city": "Bornheim",
          "state": "Nordrhein-Westfalen",
          "postalCode": "53332",
          "country": "DE"
        }
      },
      "search": {
        "mode": "include"
      }
    },
    {
      "fullUrl": "https://fhir-directory-test.vzd.ti-dienste.de/search/Endpoint/2667020",
      "resource": {
        "resourceType": "Endpoint",
        "id": "2667020",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2022-08-31T17:46:52.145+02:00",
          "source": "#WEHMezg1dNw2bkoR",
          "profile": [
            "https://gematik.de/fhir/directory/StructureDefinition/EndpointDirectory",
            "http://hl7.org/fhir/StructureDefinition/Endpoint"
          ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by Arvato QA at 2022-08-31T17:46:51+02:00\ndata model version:2\nprofile version   :0.8.0-beta6</div>"
        },
        "identifier": [
          {
            "system": "http://hl7.org/fhir/sid/us-npi",
            "value": "5f615219-d525-424b-a80f-fff0df8865e7"
          }
        ],
        "status": "active",
        "connectionType": {
          "system": "https://gematik.de/fhir/directory/CodeSystem/EndpointDirectoryConnectionType",
          "code": "tim"
        },
        "name": "MatrixId von Organisation 1-2arvtst-ap000129 (@1-2arvtst-ap000129:tim.test.gematik.de)",
        "payloadType": [
          {
            "coding": [
              {
                "system": "https://gematik.de/fhir/directory/CodeSystem/EndpointDirectoryPayloadType",
                "code": "tim-chat",
                "display": "TI-Messenger chat"
              }
            ]
          }
        ],
        "address": "@1-2arvtst-ap000129:tim.test.gematik.de"
      },
      "search": {
        "mode": "include"
      }
    },
    {
      "fullUrl": "https://fhir-directory-test.vzd.ti-dienste.de/search/Location/2667021",
      "resource": {
        "resourceType": "Location",
        "id": "2667021",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2022-08-31T17:46:52.145+02:00",
          "source": "#WEHMezg1dNw2bkoR",
          "profile": [
            "https://gematik.de/fhir/directory/StructureDefinition/LocationDirectory",
            "http://hl7.org/fhir/StructureDefinition/Location"
          ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by Arvato QA at 2022-08-31T17:46:52+02:00\ndata model version:2\nprofile version   :0.8.0-beta6</div>"
        },
        "identifier": [
          {
            "system": "http://hl7.org/fhir/sid/us-npi",
            "value": "81d9f44c-20b1-4724-84e2-bd0ad704ddbc"
          }
        ],
        "name": "Location of Organisation 1-2arvtst-ap000129",
        "address": {
          "use": "work",
          "type": "postal",
          "text": "Friesstr. 5&#13;&#10;60388&#13;&#10;Frankfurt am Main&#13;&#10;Hessen&#13;&#10;DE",
          "line": [
            "Friesstr. 5"
          ],
          "city": "Frankfurt am Main",
          "state": "Hessen",
          "postalCode": "60388",
          "country": "DE"
        }
      },
      "search": {
        "mode": "include"
      }
    }
  ]
}
----
====

==== Display search results

The results of the search are summarized in a json FHIR Bundle structure. Each entry of the Bundle contains a FHIR ressource. The https://simplifier.net/VZD-FHIR-Directory/~introduction[FHIR-Directory simplifier page] specifies the _must support_ elements of the FHIR ressources. It is recommended to display at least those elements of the search results.

TIP: The search results can also contain FHIR data which is not marked as _must support_.

==== Full text search

IMPORTANT: Full text search is not yet supported by the FHIR-Directory

The search parameters, *_text* and *_content*, are used for full text search.


=== Owner-API

