ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../images
:toc: macro
:toclevels: 5
:toc-title: Inhaltsverzeichnis
:numbered:

image:gematik_logo.svg[width=70%]

toc::[]

= TI-Messenger-Client
The TI-Messenger-Client is the client used to interact with the TI-Messenger Fachdienst and will be distributed on various platforms (i.e. Android, iOS, Windows, Linux, etc). The functionality of the TI Messenger Client can be divided into three abstract modules as illustrated in the following figure. 

++++
<p align="left">
  <img width="100%" src=../images/I_Client.png>
</p>
++++

== VZD-FHIR-Directory Modul
This module enables the search and maintenance of entries in the FHIR Directory. It interacts with the Auth Service provides by the VZD-FHIR-Directory to aquire a valid ACCESS_TOKEN that is needed for using the search and owner endpoints offered by the VZD-FHIR-Directory.

=== Auth Service
The Auth Service offers two endpoints to request ACCESS_TOKENS that are described in the following chapters. 

==== /tim-authenticate
The Auth Service of the VZD FHIR Directory provides the endpoint */tim-authenticate* to make out a `search-accesstoken`, which is needed to use the search API for FHIR resources */search*. For requesting a `search-accesstoken` the TI-Messenger client must first have requested a 3rd party token (`Matrix-OpenID-Token`) from the Matrix-Homeserver. This token needs to added in the http header while requesting the */tim-authenticate* endpoint. Next to the token the users `MXID` has to be added as a parameter. 

*Example Request*
[source, bash]
-----------------
curl -X GET \
'https://[FHIRbaseUrl]/tim-authenticate?mxId={MXID}' \
-H 'X-Matrix-OpenID-Token: {Matrix-OpenID-Token}'
-----------------

*Example Response*
[source, ruby]
-----------------
Code: 200
{
 "jwt": "search-accesstoken",
 "token_type": "bearer",
 "expires_in": 86400
}
-----------------

==== /owner-authenticate
Der Auth Service des VZD-FHIR-Directory bietet über den Endpunkt */owner-authenticate* die Möglichkeit an, sich ein `owner-accesstoken` ausstellen zu lassen, welches am FHIR-Proxy für das Eintragen von FHIR-Ressourcen eines Akteurs am Endpunkt */owner* notwendig ist. Bei Aufruf des Endpunktes */owner-authenticate* ist es erforderlich dass 3rd Party Token `registration-service-token` im Header mit zu übergeben, welches sich der TI-Messenger-Client zurvor vom zuständigen Registrierungs-Dienst austellen lassen muss. Ebenfalls ist es erforderlich im Header den Server Namen (`Registration-Server-Name`) des ausstelenden Registrierungs-Dienstes beim Aufruf mit zu übergeben. Am Endpunkt */owner-authenticate* ist es ebenfalls erforderlich die MXID des Akteurs als Parameter `mxId` im Aufruf mit zu übergeben. 

The Auth Service of the VZD FHIR Directory offers the possibility via the endpoint */owner-authenticate* to have an `owner-accesstoken` issued, which is necessary at the FHIR proxy for registering FHIR resources of an actor at the endpoint */owner*. When calling the endpoint */owner-authenticate*, it is necessary to pass the 3rd party token `registration-service-token` in the header, which the TI messenger client must first have issued by the responsible registration service. It is also necessary to pass the server name (`registration-server-name`) of the issuing registration service in the header. At the endpoint */owner-authenticate* it is also necessary to pass the MXID of the actor as parameter `mxId` in the call. 

*Example Request*
[source, bash]
-----------------
curl -X GET \
'https://[FHIRbaseUrl]/owner-authenticate?mxId={MXID}' \
-H 'X-RegService-Token: {registration-service-token}', \
-H 'X-Registration-Server-Name: {Service-Name}'
-----------------

*Example response*
[source, ruby]
-----------------
Code: 200
{
  "jwt": "owner-accesstoken",
  "token_type": "bearer",
  "expires_in": 86400
}
-----------------

=== FHIR Proxy

==== /search
Der FHIR Proxy des VZD-FHIR-Directory bietet über die Schnittstelle *FHIRDirectorySearchAPI* den Endpunkt */search* an, um FHIR-Ressourcen im FHIR-Directory zu suchen. Um den Endpunkt */search* aufrufen zu können, wird ein `search-accesstoken` im Authorization Header benötigt. 

The VZD-FHIR-Directory proxy offers the endpoint */search* to search for HealthcareService and Practitioner resources. For authorisation the search access token, described in the chapter above is needed.

*Example Request*
[source, bash]
-----------------
GET https://[baseUrl]/search/[resourceType]?organization.active=true&[optional parameters] \
-H "Authorization: Bearer {search-accesstoken}
-----------------

*Ressourcen Types*
|===
|resourceType | description

|HealthcareService | To search for organizations, use "HealthcareService" + 
as the resource type
|PractitionerRole | To search for people, use "PractitionerRole" + 
as the resource type
|===

TIP: Only resources with the status "active" shall be displayed. For this reason, the [resource].active=true parameter must be specified for all search operations.

Ein Überblick über die unterstützten FHIR Parameter können hier https://github.com/gematik/api-vzd/blob/feature/ILF-FHIR_VZD/docs/gemILF_FHIR_VZD.adoc#fhir-search-organizations[[FHIR VZD implementation guide]] nachgelesen werden.

An overview of all supported FHIR parameters is documented at https://github.com/gematik/api-vzd/blob/feature/ILF-FHIR_VZD/docs/gemILF_FHIR_VZD.adoc#fhir-search-organizations[[FHIR VZD implementation guide]]. 

*Beispielabfrage:*
[source, bash]
-----------------
curl -X GET "https://fhir-directory-test.vzd.ti-dienste.de/search/HealthcareService?organization.active=true&_count=1" \
    -H "Authorization: Bearer {search-accesstoken}
-----------------

==== /owner
Der FHIR Proxy des VZD-FHIR-Directory bietet über die Schnittstelle *FHIRDirectoryOwnerAPI* den Endpunkt */owner* an, um FHIR-Ressourcen im FHIR-Directory für einen Akteur einzutragen. Um den Endpunkt */owner* aufrufen zu können, wird ein `owner-accesstoken` im Authorization Header benötigt. 

The FHIR Proxy exposes the endpoint */owner* to offer CRUD operations on FHIR-resources for the resource owner. For interaction with the */owner* endpoint an `owner-accesstoken` is mandatory.

*Example Request*
[source, bash]
-----------------
POST https://[baseUrl]/owner/[resourceType]&[optional parameters] \
-H "Authorization: Bearer {owner-accesstoken}
-----------------

Erst GET (Datensatz suchen) -> PUT (Datensatz ändern)

!!!TODO!!!

== TI-Messenger Modul
Über dieses abstrakte Modul wird die eigentliche Ad-Hoc Kommunikation durchgeführt. Der TI-Messenger-Client kommuniziert mit dem Messenger Service des TI-Messenger-Fachdienstes über die Matrix - Client-Server Schnittstelle, um Events auszutauschen. Für die Administration einer Freigabeliste stellt der Messenger Service die Schnittstelle `I_Ti_MessengerContactManagement` bereit. Der Aufruf der Schnittstellen erfolgt immer über den Messenger Proxy. Im folgenden werden die Schnittstellen beschrieben. 

This modul contains the client interface to interact with the messenger-service provided by the TI-Messenger-Fachdienst. Therefore the client has to implement the Matrix Client-Server API. For the administration of the personal contact management list, the client has to implement the  interface 'I_Ti_MessengerContactManagement' offered by the Messenger Proxy.

=== Matrix - Client-Server API
Der Matrix Homeserver muss die Schnittstelle gemäß der Matrix https://spec.matrix.org/latest/[[Client-Server API]] anbieten, welche der TI-Messenger Client aufruft. Der Aufruf der einzelnen Endpunkte kann dort nachgelesen werden. Ein Überblick über die einzelnen Endpunkte der Schnittstelle ist hier https://matrix.org/docs/api/#overview[[API Playground]] einsehbar. 

The Matrix Homeserver must offer the interface according to the Matrix [Client-Server API], which the TI-Messenger Client calls. The call of the individual endpoints can be read there. An overview of the individual endpoints of the interface can be viewed here [API Playground].

Für die Fallbezogene Kommunikation ist es erforderlich etwas am Event xyz anzupassen!!!!
Es ist erforderlich, dass der TI-Messenger-Client FHIR-Ressourcen in den Room-State eines existierenden Chatraumes hinzufügt. 

For patient-case-related communication, additional informations have to be added to the room state. 
The TI Messenger client will use FHIR based resources as additional information for the matrix chat room. 

Art des Events: state event
Event state_key: <vom Sender festgelegt> +
Event type: "de.gematik.tim.casereference" +
Die FHIR-Ressourcen werden im Element content als json-Daten eingetragen und als FHIR-Bundle (type message) zusammengefasst.

The FHIR-Ressources will be added in the content part of a room state event. 

*Example des Request*
[source, bash]
-----------------
POST 'https://{domain}/_matrix/client/v3/createRoom' \
-----------------

=== I_Ti_MessengerContactManagement
Es ist erforderlich das der TI-Messenger-Client die Operationen der Schnittstelle `I_TiMessengerContactManagement` aufruft. 

For administration of the personal contact list the messenger proxy exposes the API `I_TiMessengerContactManagement`.

/tim-contact-mgmt/

== Auth Modul
Über dieses abstrakte Modul wird die Kommunikation mit dem IDP durchgeführt. Der TI-Messenger-Client authentisiert  sich mittels OpenID-Connect um ein ID_TOKEN ausgestellt zu bekommen. Für die Authentisierung am IDP wird endweder eine SMC-B oder ein HBA verwendet.

The auth module contains the functionality to authenticate a user with an SMC-B or HBA card. To interact with one of the mentioned cards the module needs a connection to a card terminal that is connected to a connector. The module reads the cards certificate information and sends the data to the gematik IDP. After successful authentication an ID_TOKEN will be issued by the gematik IDP which can be used to get an ACCESS_TOKEN for the FHIR-VZD. 

=== OIDC / OAuth
Der TI-Messenger-Client löst einen OAUTH2 Authorization Request unter Angabe des zu verwendenden sektoralen Identity Providers an den Authorization Endpoint des Authorization-Servers aus.

= Referenzierte Dokumente
Die nachfolgende Tabelle enthält die in der vorliegenden Online Dokumentation referenzierten Dokumente der gematik. Deren zu diesem Dokument jeweils gültige Versionsnummer entnehmen Sie bitte der aktuellen, auf der Internetseite der gematik veröffentlichten, Dokumentenlandkarte, in der die vorliegende Version aufgeführt wird.

The following table contains the gematik documents referenced in this online documentation. For the version number valid for this document, please refer to the current document map published on the gematik website, in which the present version is listed.

|===
|[Quelle] |Herausgeber: Titel

|*[Client-Server API]* | https://spec.matrix.org/latest/client-server-api/
|*[API Playground]* | https://matrix.org/docs/api/#overview
|===
