:imagesdir: ../images
:toc: macro
:toclevels: 5
:toc-title: Inhaltsverzeichnis
:numbered:

image:gematik_logo.svg[width=70%]

toc::[]

= TI-Messenger-Fachdienst
Der TI-Messenger-Fachdienst ist in *[gemSpec_TI-Messenger-FD]* spezifiziert. Dieser besteht aus den Teilkomponenten Registrierungs-Dienst, Messenger-Service und einem Push-Gateway. Dieser stellt den TI-Messenger-Clients verschiedene Schnittstellen bereit, um die Kommunikations mit der jeweiligen Teilkomponente zu ermöglichen. In der folgenden Abbildung (links) sind alle Schnittstellen, die der Fachdienst anbietet, mit der jeweiligen Teilkomponente, dargestellt.

++++
<p align="left">
  <img width="100%" src=../images/I_Fachdienst.png>
</p>
++++

== Registrierungs-Dienst
Über den Registrierungs-Dienst bekommt der TI-Messenger-Anbieter die Möglichkeit Messenger-Services automatisiert Organisationen zur Verfügung zu stellen und die Matrix-Domain der von ihm bereitgestellten Messenger-Services in deren Organisationsressource in das zentrale VZD-FHIR-Directory einzutragen. Der Registrierungs-Dienst eines TI-Messenger-Fachdienstes bietet als weitere Funktion die Bereitstellung einer Föderationsliste für die Messenger Proxies seiner Messenger-Services an

=== I_Registration
Diese nicht durch die gematik normierte Operation `I_Registration` am Registrierungs-Dienst ermöglicht es Akteuren ihre Organisation über deren Identität (SMC-B) bei einem Anbieter zu registrieren um Messenge-Services bereitzustellen. Es ist zu empfehlen, diese Schnittstelle als eine REST-Schnittstelle zu implementieren. Der Akteur sollte diese über ein Webbrowser (z. B. über ein Portal des Anbieters) aufrufen können. 

Für die Authentifizierung einer Organisation am Registrierungs-Dienst wird der zentrale IDP-Dienst der gematik benötigt. Hierfür wird das durch die gematik bereitgestellte Authenticator-Modul (siehe *[gematik Authenticator]* ) verwendet, um  das Authentifizierungszertifikats der SMC-B in ein ID_TOKEN umzuwandeln. Der Authenticator wird in einer Windows-Systemumgebungen zusammen mit dem Primärsystem betrieben. 

Nach der erfolgreichen Authentifizierung der Organisation am Registrierungs-Dienst muss es über die Schnittstelle möglich sein, dass ein Admin Account für die Organisation angelegt werden kann. Die für den Nutzer notwendigen Credentials werden bei der Einrichtung des Admin Accounts auf dem Registrierungs-Dienst übergeben. Es muss berücksichtigt werden, dass mindestens eine 2-Faktor Verfahren unterstützt wird. 

=== I_internVerification
Bei der Schnittstelle `I_internVerification` handelt es sich um eine abstrakte interne Schnittstelle am Registrierungs-Dienst mit der den Messenger-Proxies die folgenden  Funktionalitäten bereitgestellt werden:

- Bereitstellung der Föderationsliste, die alle verifizierte Matrix-Domains als Hashes enthält und
- die Überprüfung von MXID-Einträgen im VZD-FHIR-Directory, um die Berechtigungsprüfung der Stufe 3 durchführen zu können.

Für die Prüfung der Organisationszugehörigkeit ist es erforderlich, dass der Registrierungs-Dienst über die abstrakte Schnittstelle `I_internVerification` den Messenger-Proxies eine aktuelle Föderationsliste bereitstellt. Hierfür ist es erforderlich, dass der Registrierungs-Dienst die Operation `/tim-provider-services/getFederationList` am FHIR-Proxys des VZD-FHIR-Directory aufruft, um eine aktuelle Föderationsliste zu erhalten. 
Im fogenden ist der Aufbau der Föderationsliste die vom FHIR-Proxy des VZD-FHIR-Directory bereitgestellt wird dargestellt

.Föderationsliste
[%collapsible%open]
====
[source, yaml]
----
FederationList {
  version	    integer
                    readOnly: true
                    The version of the federation list
 
  hashAlgorithm	    string
                    readOnly: true
                    The hash algorithm that was used to create the hashes. Currently only SHA-256 is supported.
 
  domainList        [ 
                      The list of hashed TI-Messenger domain names

                    DomainList {
                        description:	  the list of hashed TI-Messenger domain names
                        
                        domain	          string
                                          hashed TI-Messenger domain name
                                        
                        isInsurance	  boolean
                                          example: false
                                          Indicates if it is a domain of an health insurance for insured persons
                                        
                  }]
}
----
====

*Beispiel einer HTTP Nachricht*

[cols="h,a",] 
|===
|URI        |\https://vzd-fhir-directory.vzd.ti-dienste.de/tim-provider-services
|Method     |GET
|Header |
[source, bash]
----
HTTP-Version: "HTTP/1.1"
Authorization: "provider-accesstoken"
----
|Body    |
[source, bash]
----
-
|===


*Beispielabfrage:*
[source, bash]
-----------------
curl -X 'GET' \
  'https://vzd-fhir-directory.vzd.ti-dienste.de/tim-provider-services/FederationList?version=1' \
  -H 'accept: application/json'
-----------------


== Messenger-Service
Beschreibungstext


Die Messenger-Services KÖNNEN den Akteuren unterschiedliche Authentifizierungsverfahren anbieten, bei denen der Besitz einer SMC-B oder eines HBAs nicht vorausgesetzt wird


Über eine Anpassung in der Synapse-Konfigurationsdatei /etc/matrix-synapse/homeserver.yaml ist es möglich existierende Authentifizierungsverfahren anzubinden.

[source, yaml]
-----------------
Passwortanbieter:
    - Modul: "ldap_auth_provider.LdapAuthProvider"
      Config:
        aktiviert: wahr
        uri: "ldap://DIRECTION_IP_DC:389"
        start_tls: falsch
        Base: "oder = OR_2, oder = OR_1, dc = DOMAIN,dc=LOCAL"
        Attribute:
           uid: "sAMAccountName"
           Post: "Post"
           Name: "Vorname"
        bind_dn: "cn=USUARIO_LDAP_SYNAPSE,oder = OR_2, oder = OR_1, dc = DOMAIN,dc=LOCAL"
        bind_password: "PASSWORT"
        #Filter: "(objectClass=posixAccount)"
-----------------

Quelle: https://github.com/matrix-org/matrix-synapse-ldap3

Bei der Verwendung eines existierenden Authentifizierungsverfahrens muss dieses als 2-Faktor Authentifizierung ergänzt werden.

2 Faktor gemäß BSI Empfehlung: https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Accountschutz/Zwei-Faktor-Authentisierung/Bewertung-2FA-Verfahren/bewertung-2fa-verfahren_node.html

Beispiel

- E-Mail?
- SMS Code?

=== Messenger Proxy
Der Messenger-Proxy als Prüfinstanz aller eingehenden Anfragen zum Messenger-Service ist für die Regelung der gemäß Matrix Client-Server-API und Matrix-Server-Server-API geltenden Aufrufe zuständig.

Freigabeliste

=== Matrix-Homeserver

= Referenzierte Dokumente

Die nachfolgende Tabelle enthält die in der vorliegenden Online Dokumentation referenzierten Dokumente der gematik. Deren zu diesem Dokument jeweils gültige Versionsnummer entnehmen Sie bitte der aktuellen, auf der Internetseite der gematik veröffentlichten, Dokumentenlandkarte, in der die vorliegende Version aufgeführt wird.

|===
|[Quelle] |Herausgeber: Titel

|*[gemSpec_TI-Messenger-FD]* |gematik: Spezifikation TI-Messenger-Fachdienst
|*[gematik Authenticator]* | gematik Authenticator +
https://cloud.gematik.de/index.php/s/23ebxa75z3s7zGt?path=%2Fv2.1.0 
|===
