ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../images
:toc: macro
:toclevels: 5
:toc-title: Inhaltsverzeichnis
:numbered:

image:gematik_logo.svg[width=70%]

toc::[]

= TI-Messenger-Client
Der TI-Messenger-Client basiert auf den offenen Kommunikationsprotokoll Matrix und wird auf dem Endgerät eines Akteurs verwendet. Die Funktionalität des TI-Messenger-Clients kann in drei abstrakten Modulen unterteilt werden. In der folgende Abbildung wird dies verdeutlicht. 


++++
<p align="left">
  <img width="100%" src=../images/I_Client.png>
</p>
++++

== VZD-FHIR-Directory Modul
Der TI-Messenger-Client nutzt die Schnittstellen der Teilkomponenten Auth Services und FHIR-Proxy am VZD-FHIR-Directory. Für den Aufruf der beiden Schnittstellen am FHIR-Proxy werden Token benötigt, um die Berechtigung für den Zugriff nachzuweisen. Daher muss der TI-Messenger-Client zuvor am Auth Service die notwendigen Token anfragen. Im folgenden werden die Aufrufe beschrieben. 

=== Auth Service
Der Auth Service des VZD-FHIR-Directory bietet zwei Schnittstellen an, um sich valide ACCESS TOKENS ausstellen zu lassen.

==== /tim-authenticate
Der Auth Service des VZD-FHIR-Directory bietet über den Endpunkt */tim-authenticate* an, um sich ein `search-accesstoken` ausstellen zu lassen, welches am FHIR-Proxy für die Suche nach FHIR-Ressourcen am Endpunkt */search* notwendig ist. Bei Aufruf des Endpunktes */tim-authenticate* ist es erforderlich im Header, dass 3rd Party Token `Matrix-OpenID-Token` mit zu übergeben, welches zurvor sich der TI-Messenger-Client vom zuständigen Matrix-Homeserver als 3rd Party Token austellen lassen muss.  

*Beispielabfrage:*
[source, bash]
-----------------
curl -X GET \
'https://[FHIRbaseUrl]/tim-authenticate?mxId=matrix.dev.service-ti.de' \
-H 'X-Matrix-OpenID-Token: {Matrix-OpenID-Token}'
-----------------

*Beispielantwort*
[source, ruby]
-----------------
Code: 200
{
 "jwt": "search-accesstoken",
 "token_type": "bearer",
 "expires_in": 86400
}
-----------------


==== /owner-authenticate
Der Auth Service des VZD-FHIR-Directory bietet über den Endpunkt */owner-authenticate* an, um sich ein `owner-accesstoken` ausstellen zu lassen, welches am FHIR-Proxy für das Eintragen von FHIR-Ressourcen eines Akteurs am Endpunkt */owner* notwendig ist. Bei Aufruf des Endpunktes */owner-authenticate* ist es erforderlich im Header, dass 3rd Party Token `registration-service-token` mit zu übergeben, welches zurvor sich der TI-Messenger-Client vom zuständigen Registrierungs-Dienst als 3rd Party Token austellen lassen muss. 

*Beispielabfrage:*
[source, bash]
-----------------
curl -X GET \
'https://[FHIRbaseUrl]/owner-authenticate?mxId=matrix.dev.service-ti.de' \
-H 'X-RegService-Token": "registration-service-token', 
-H 'X-Registration-Server-Name": "registration-service.dev.service-ti.de'
-----------------

*Beispielantwort*
[source, ruby]
-----------------
Code: 200
{
  "jwt": "owner-accesstoken",
  "token_type": "bearer",
  "expires_in": 86400
}
-----------------

=== FHIR Proxy

==== /search
Der FHIR Proxy des VZD-FHIR-Directory bietet über die Schnittstelle *FHIRDirectorySearchAPI* den Endpunkt */search* an, um FHIR-Ressourcen im FHIR-Directory zu suchen. Um den Endpunkt */search* aufrufen zu können, wird ein `search-accesstoken` im Authorization Header benötigt. 

Es gilt der folgende Aufbau:

[source, bash]
-----------------
GET https://[baseUrl]/[resourceType]?organization.active=true&[optional parameters]
-----------------

*Ressourcen Types*
|===
|resourceType | description

|HealthcareService | To search for organizations, use "HealthcareService" + 
as the resource type
|PractitionerRole | To search for people, use "PractitionerRole" + 
as the resource type
|===

TIP: Only resources with the status "active" may be displayed. For this reason, the [resource].active=true parameter must be specified for all search operations.

Ein Überblick über die unterstützten FHIR Parameter können https://github.com/gematik/api-vzd/blob/feature/ILF-FHIR_VZD/docs/gemILF_FHIR_VZD.adoc#fhir-search-organizations[[FHIR VZD implementation guide]] nachgelesen werden 

*Beispielabfrage:*
[source, bash]
-----------------
curl -X GET "https://fhir-directory-test.vzd.ti-dienste.de/search/HealthcareService?organization.active=true&_count=1" \
    -H "Authorization: Bearer {owner-accesstoken}
-----------------

==== /owner


siehe: 

== TI-Messenger Modul

== Auth Modul
