:imagesdir: ../images
:toc: macro
:toclevels: 5
:toc-title: Inhaltsverzeichnis
:numbered:

image:gematik_logo.svg[width=70%]

toc::[]

= TI-Messenger-Fachdienst
Der TI-Messenger-Fachdienst ist in *[gemSpec_TI-Messenger-FD]* spezifiziert. Dieser besteht aus den Teilkomponenten Registrierungs-Dienst, Messenger-Service und einem Push-Gateway. Dieser stellt den TI-Messenger-Clients verschiedene Schnittstellen bereit, um die Kommunikations mit der jeweiligen Teilkomponente zu ermöglichen. In der folgenden Abbildung (links) sind alle Schnittstellen, die der Fachdienst anbietet, mit der jeweiligen Teilkomponente, dargestellt.

++++
<p align="left">
  <img width="100%" src=../images/I_Fachdienst.png>
</p>
++++

== Registrierungs-Dienst
Über den Registrierungs-Dienst bekommt der TI-Messenger-Anbieter die Möglichkeit Messenger-Services automatisiert Organisationen zur Verfügung zu stellen und die Matrix-Domain der von ihm bereitgestellten Messenger-Services in deren Organisationsressource in das zentrale VZD-FHIR-Directory einzutragen. Der Registrierungs-Dienst eines TI-Messenger-Fachdienstes bietet als weitere Funktion die Bereitstellung einer Föderationsliste für die Messenger Proxies seiner Messenger-Services an

=== I_Registration
Diese nicht durch die gematik normierte Operation `I_Registration` am Registrierungs-Dienst ermöglicht es Akteuren ihre Organisation über deren Identität (SMC-B) bei einem Anbieter zu registrieren um Messenge-Services bereitzustellen. Es ist zu empfehlen, diese Schnittstelle als eine REST-Schnittstelle zu implementieren. Der Akteur sollte diese über ein Webbrowser (z. B. über ein Portal des Anbieters) aufrufen können. 

Für die Authentifizierung einer Organisation am Registrierungs-Dienst wird der zentrale IDP-Dienst der gematik benötigt. Hierfür wird das durch die gematik bereitgestellte Authenticator-Modul (siehe *[gematik Authenticator]* ) verwendet, um  das Authentifizierungszertifikats der SMC-B in ein ID_TOKEN umzuwandeln. Der Authenticator wird in einer Windows-Systemumgebungen zusammen mit dem Primärsystem betrieben. 

Nach der erfolgreichen Authentifizierung der Organisation am Registrierungs-Dienst muss es über die Schnittstelle möglich sein, dass ein Admin Account für die Organisation angelegt werden kann. Die für den Nutzer notwendigen Credentials werden bei der Einrichtung des Admin Accounts auf dem Registrierungs-Dienst übergeben. Es muss berücksichtigt werden, dass mindestens eine 2-Faktor Verfahren unterstützt wird. 

=== I_internVerification
Bei der Schnittstelle `I_internVerification` handelt es sich um eine abstrakte interne Schnittstelle am Registrierungs-Dienst mit der den Messenger-Proxies die folgenden  Funktionalitäten bereitgestellt werden:

- Bereitstellung der Föderationsliste, die alle verifizierte Matrix-Domains als Hashes enthält und
- die Überprüfung von MXID-Einträgen im VZD-FHIR-Directory, um die Berechtigungsprüfung der Stufe 3 durchführen zu können.

Für die Prüfung der Organisationszugehörigkeit ist es erforderlich, dass der Registrierungs-Dienst über die abstrakte Schnittstelle `I_internVerification` den Messenger-Proxies eine aktuelle Föderationsliste bereitstellt. Hierfür ist es erforderlich, dass der Registrierungs-Dienst die Operation `/tim-provider-services/getFederationList` am FHIR-Proxys des VZD-FHIR-Directory aufruft, um eine aktuelle Föderationsliste zu erhalten. 
Im fogenden ist der Aufbau der Föderationsliste die vom FHIR-Proxy des VZD-FHIR-Directory bereitgestellt wird dargestellt

.Föderationsliste
[%collapsible%open]
====
[source, yaml]
----
FederationList {
  version	    integer
                    readOnly: true
                    The version of the federation list
 
  hashAlgorithm	    string
                    readOnly: true
                    The hash algorithm that was used to create the hashes. Currently only SHA-256 is supported.
 
  domainList        [ 
                      The list of hashed TI-Messenger domain names

                    DomainList {
                        description:	  the list of hashed TI-Messenger domain names
                        
                        domain	          string
                                          hashed TI-Messenger domain name
                                        
                        isInsurance	  boolean
                                          example: false
                                          Indicates if it is a domain of an health insurance for insured persons
                                        
                  }]
}
----
====

*Beispiel einer HTTP Nachricht*

[cols="h,a",] 
|===
|URI        |\https://vzd-fhir-directory.vzd.ti-dienste.de/tim-provider-services
|Method     |GET
|Header |
[source, bash]
----
HTTP-Version: "HTTP/1.1"
Authorization: "provider-accesstoken"
----
|Body    |
[source, bash]
----
-
|===


*Beispielabfrage:*
[source, bash]
-----------------
curl -X 'GET' \
  'https://vzd-fhir-directory.vzd.ti-dienste.de/tim-provider-services/FederationList?version=1' \
  -H 'accept: application/json'
-----------------


== Messenger-Service
Der Messenger-Service besteht aus den Teilkomponenten Messenger-Proxy und dem Matrix-Homeserver. Über den Messenger-Proxy werden immer alle Anfragen  an den Matrix-Homeserver weitergeleitet. Eine direkte Kommunikation zum Matrix-Homeserver ist nicht erlaubt. 

=== Messenger-Proxy
Der Messenger-Proxy als Prüfinstanz aller eingehenden Anfragen zum Messenger-Service ist für die Regelung der gemäß Matrix Client-Server-API und Matrix-Server-Server-API geltenden Aufrufe zuständig.

==== TLS-Kommunikation
Am Messenger-Proxy wird die TLS-Kommunikation zwischen den TI-Messenger-Clients und den Matrix-Homeserver terminiert. Für die Serverauthentisierung ist es erfordlich ein durch den Fachdienst-Anbieter bereitgestelltes X.509-Zertifikat zu verwenden. Hierbei darf es sich nicht um ein self-sign Zertifikat handeln. 

Der Messenger-Proxy prüft bei jeder Verbindung, anhand der `client_id`, ob es sich um ein zugelassenen TI-Messenger-Client handelt. Damit der TI-Messenger-Client mit dem Messenger-Proxy erfolgreich kommunizieren kann, ist es erforderlich, dass die `client_id` beim Messenger-Proxy bekannt ist. Hierfür muss der TI-Messenger-Client Hersteller die `client_id` beim TI-Messenger-Anbieter bekannt machen. Sollten unterschiedliche TI-Messenger-Clients vom Messenger-Proxy eines Anbieters unterstützt werden, so müssen alle `client_id` an den TI-Messenger-Anbieter des Messener-Proxies übermittelt werden. 

==== Authentifizierungsverfahren

Neben der Authentifizierung mittels einer SMC-B oder eines HBA's können auch weitere Authentifizierungsverfahren vom Messenger-Service unterstützt werden. Dies ermöglicht es Nutzern bereits existierende Authentifizierungsverfahren in ihrer Organisation nachzunutzen. Dies kann zum Beispiel ein Active Directory oder ein LDAP-Verzeichnis sein.

Um dies innerhalb einer Organisation für die Nutzer bereitstellen zu können muss das bestehende Authentifizierungsverfahren dies am Matrix-Homeserver  konfiguriert werden. 

Beim Einsatz eines Synapse-Servers als Matrix-Homeserver kann zum Beispiel für eine LDAP-Authentifizierung das modul `LDAP Auth Provider` gemäß https://github.com/matrix-org/matrix-synapse-ldap3[[LDAP Auth Provider]] verwendet werden. Hierfür muss die Synapse-Konfigurationsdatei `/etc/matrix-synapse/homeserver.yaml` wie folgt angepasst werden:

[source, yaml]
-----------------
modules:
- module: "ldap_auth_provider.LdapAuthProvider"
  config:
    enable: true
    uri: "ldap://DIRECTION_IP_DC:389"
    start_tls: false
    base: "ou=users,dc=example,dc=com"
    attributes:
       uid: "cn"
       mail: "mail"
       name: "givenName"
-----------------

Bei der Verwendung eines existierenden Authentifizierungsverfahrens muss zusätzich ein 2. Faktor hinzugezogen werden. Hier sind die Empfehlungen des BSIs gemäß https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Accountschutz/Zwei-Faktor-Authentisierung/Bewertung-2FA-Verfahren/bewertung-2fa-verfahren_node.html[&#91;Technische Betrachtung&#93;] zu berücksichtigen. 

Mögliche Beispiele wären:

* Verifizierung über E-Mail

* Überprüfung per SMS Code

==== Proxy für das Matrix-Protokoll
Der Messenger-Proxy ist technisch ein Reverse-proxy und leitet alle Anfragen, die einer Matrix API entsprechen, nach einer Berechtigungsprüfung, an den Matrix Homeserver weiter. 

==== Bereistellen und Administration der Freigabeliste
Bei der Freigabeliste handelt es sich um eine Whitelist, die alle Akteure enthält, die vom jeweiligen Akteur berechtigt werden mit ihm kontakt aufzunehmen. Die Liste kann in Form einer Lookup-Table implementiert werden. Für die Adminstration der Freigabeliste eines Akteurs ist es erforderlich, dass der Messenger Proxy Schnittstelle `I_TiMessengerContactManagement` gemäß https://github.com/gematik/api-ti-messenger/blob/feature/fachdienst/src/openapi/TiMessengerContactManagement.yaml[&#91;TIMessengerContactManagement&#93;] bereitgestellt.

==== Prüfregeln
Der Messenger-Proxy muss bei jedem `Invite-Event` die Anfrage an den Matrix-Homeserver auf Berechtigung prüfen. Die Berechtigungsstufen sind in *[gemSpec_TI_Messenger-Dienst#Berechtigungskonzept]* beschrieben. 

Bei einer Clint-Server Kommunikation wird nur die Föderationszugehörigkeit (Stufe 1) geprüft. Bei einer Server-Server Kommunikation werden alle Berechtigungsstufen durchlaufen. 

Zur Überpürfung gemäß der Berechtigungsstufe 1, ist es erforderlich, dass der Messenger-Proxy die Föderationsliste vom zuständigen Registrierungs-Dienst abruft. Dies ist in *[gemSpec_TI-Messenger-FD#Messenger-Proxy]* beschrieben. 

=== Matrix-Homeserver
Die Teilkomponente Matrix-Homeserver basiert auf dem offenen Kommunikationsprotokoll Matrix. 

=== Push-Gateway
Das Push-Gateway muss gemäß der Matrix-Spezifikation implementiert werden. 


= Betriebliche Aspekte
Der Betrieb des Fachdienstes wird durch den TI-Messenger-Anbieter verantwortet. Zentrale Komponenten, wie der Registrierungs-Dienst und das Push-Gateway werden zentral durch den TI-Messenger-Anbieter bereitgestellt und betrieben. Ein Messenger Service kann sowohl in einem Rechenzentrum des TI-Messenger-Anbieters als auch on Premise in den Räumlichkeiten einer Organisation durch den TI-Messenger-Anbieter betrieben werden.


= Referenzierte Dokumente

Die nachfolgende Tabelle enthält die in der vorliegenden Online Dokumentation referenzierten Dokumente der gematik. Deren zu diesem Dokument jeweils gültige Versionsnummer entnehmen Sie bitte der aktuellen, auf der Internetseite der gematik veröffentlichten, Dokumentenlandkarte, in der die vorliegende Version aufgeführt wird.

|===
|[Quelle] |Herausgeber: Titel

|*[gemSpec_TI-Messenger-FD]* |gematik: Spezifikation TI-Messenger-Fachdienst
|*[gematik Authenticator]* | gematik Authenticator +
https://cloud.gematik.de/index.php/s/23ebxa75z3s7zGt?path=%2Fv2.1.0 
|===
