ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../images
:toc: macro
:toclevels: 5
:toc-title: Table of Contents
:numbered:

image:gematik_logo.svg[width=70%]

toc::[]

= TI-Messenger-Fachdienst
The following guide is intended to assist in the implementation of the TI-Messenger-Fachdienst.

TIP: This guide can be seen as a supplement to the *[gemSpec_TI-Messenger-FD]* specification.

The TI-Messenger-Fachdienst consists of the subcomponents:  

* Registrierungs-Dienst, 

* Messenger-Service and

* Push-Gateway. 

The TI-Messenger-Fachdienst provides various interfaces to enable communication with the subcomponents. The following figure shows all interfaces offered by the TI-Messenger-Fachdienst with the respective subcomponents.

++++
<p align="left">
  <img width="100%" src=../images/I_Fachdienst.png>
</p>
++++

== Registrierungs-Dienst
The Registrierungs-Dienst gives the TI-Messenger-Fachdienst provider the opportunity to automatically make Messenger-Services available to authenticated organizations and to enter the matrix domain of the Messenger-Services they provide in their organizational resource in the central VZD-FHIR-directory. As a further function, the Registrierungs-Dienst of a TI-Messenger-Fachdienst offers the provision of a federation list for the Messenger-Proxies of its Messenger-Services.

TIP:  To authenticate an organization to the Registrierungs-Dienst, it is necessary to use the central IDP-Service according to *[gemSpec_IDP_FD]*

For the implementation of the functions described, the two interfaces `I_Registration` and `I_internVerification` are implemented by the Registrierungs-Dienst. These are described below.

=== Interface: I_Registration
This interface, which is not standardized by gematik, is accessed via a Frontend of the Registrierungs-Dienst. This enables the authentication of an organization as well as the administration and provision of Messenger-Services. An organization is authenticated via its identity (SMC-B).
It is recommended to implement this interface as a REST interface.

The central IDP-Service of gematik is required for the authentication of an organization at the Registrierungs-Dienst. The Authenticator-Module provided by gematik (see https://cloud.gematik.de/index.php/s/23ebxa75z3s7zGt?path=%2Fv2.1.0[[gematik Authenticator]]) is used for this to authenticate the SMC-B to an ID_TOKEN. The authenticator runs in a Windows system environment together with the primary system. The Registrierungs-Dienst must check the ID_TOKEN when verifying the organization. In order to be able to carry out the verification, the Registrierungs-Dienst and the frontend of the Registrierungs-Dienst must be registered with the central IDP-Service.

After the organization has been successfully authenticated at the Registrierungs-Dienst, it must be possible to create an admin account for the organization via the frontend of the Registrierungs-Dienst. Messenger-Services can then be generated and provided with this admin account.

=== Interface: I_internVerification
The interface `I_internVerification` is an abstract internal interface at the Registrierungs-Dienst, with which the following functionalities are provided to the Messenger-Proxies:

- Provision of the federation list containing all verified matrix domains as hashes and
- the verification of MXID entries in the VZD-FHIR-Directory in order to be able to carry out the Level 3 authorization check according to *[gemSpec_TI-Messenger-FD#Messenger-Proxy]*.

TIP: The implementation of the functionalities to be provided, Provision of the federation list and Authorization check - Level 3, on the Registrierungs-Dienst can also be carried out via separate interfaces on the Registrierungs-Dienst.

==== Feature: Provision of the federation list
To verify organizational affiliation, the Registrierungs-Dienst must provide the Messenger-Proxies with an up-to-date federation list via the abstract interface `I_internVerification`. This requires the Registrierungs-Dienst to call the `/tim-provider-services/getFederationList` operation on the FHIR-Proxy of the VZD-FHIR-Directory in order to obtain a current federation list.

The structure of the federation list provided by the FHIR-Proxy of the VZD-FHIR-Directory is shown below.

*Structure of the federation list*
|====
a|
[source, yaml]
----
FederationList {
  version	    integer
                    readOnly: true
                    The version of the federation list
 
  hashAlgorithm	    string
                    readOnly: true
                    The hash algorithm that was used to create the hashes. Currently only SHA-256 is supported.
 
  domainList        [ 
                      The list of hashed TI-Messenger domain names

                    DomainList {
                        description:	  the list of hashed TI-Messenger domain names
                        
                        domain	          string
                                          hashed TI-Messenger domain name
                                        
                        isInsurance	  boolean
                                          example: false
                                          Indicates if it is a domain of an health insurance for insured persons
                                        
                  }]
}
----
|====

*Example of an HTTP message*

[cols="h,a",] 
|===
|URI        |\https://vzd-fhir-directory.vzd.ti-dienste.de/tim-provider-services
|Method     |GET
|Header |
[source, bash]
----
HTTP-Version: "HTTP/1.1"
Authorization: "provider-accesstoken"
----
|Body    |
[source, bash]
----
-
|===


*Sample query:*
[source, bash]
-----------------
curl -X 'GET' \
  'https://vzd-fhir-directory.vzd.ti-dienste.de/tim-provider-services/FederationList?version=1' \
  -H 'accept: application/json'
-----------------

==== Feature: Authorization check - Level 3
The Registrierungs-Dienst must offer the Messenger-Proxies of the TI-Messenger-Fachdienst a function via the `I_internVerification` interface, with which it is possible to check for MXID entries in the VZD-FHIR-Directory.

TIP: According to the TI-Messenger-Dienst architecture, only the respective Registrierungs-Dienst of a TI-Messenger-Fachdienst may access the VZD-FHIR directory. 

For this it is necessary to call the operation `/tim-provider-services/whereIs` with the MXIDs of the actors listed in the `Invite-Event` on the FHIR-Proxy. As a result, the FHIR-Proxy returns the following:

*Return value of the operation `whereIs`*
|====
a|
[source, yaml]
----
responses:
  200:
    description: OK
    content:
      application/json:
        schema:
            type: string
            enum: [org, pract, orgPract, none]
            example: org |
            *description:* +
              Returns in which part of the directory the MXID (the request contains the hash of the MXID) is located: 
              
               - `org`:      Located in the Organization part +               
               - `pract`:    Located in the Practitioner part +         
               - `orgPract`: Located in the Organization and Practitioner part +               
               - `none`:     Not found in any part
                    
|====

The result from the FHIR-Proxy must be returned to the requesting Messenger-Proxy.

=== Interface: I_requestToken
The Interface I_requestToken shall be provided by the Registrierungs-Dienst to request an RegService-OpenID-Token that can be exchanged for an owner-accesstoken for organization ressources. The interface is only accessable for Org-Admin users.  

== Messenger-Service
The Messenger-Service consists of the subcomponent Messenger-Proxy and the Matrix-Homeserver. All requests are always forwarded to the Matrix-Homeserver via the Messenger-Proxy. A Messenger-Service is provided by an authorized actor via the frontend of the Registrierungs-Dienst.

TIP: Direct communication with the Matrix-Homeserver is not permitted. 

=== Messenger-Proxy
The Messenger-Proxy, as the checking instance for all incoming `Invite Events`, is responsible for regulating the calls that apply in accordance with the Matrix Client-Server-API and Matrix-Server-Server-API. After a successful check, the `Invite Event` is forwarded to the responsible Matrix-Homeserver. An overview can be found in *[gemSpec_TI-Messenger-Dienst#Stufen der Berechtigungsprüfung]*. The functional features that the Messenger-Proxy must implement are described below.

==== TLS-Communication
The TLS communication between the TI-Messenger-Clients and the Matrix-Homeserver is terminated at the Messenger-Proxy. For server authentication, it is necessary to use an X.509 certificate provided by the TI Messenger-Fachdienst provider.

TIP: The X.509 certificate must be a public certificate issued by a trustworthy publisher.

With each connection, the Messenger-Proxy uses the `client_id` to check whether it is an approved TI-Messenger-Client. In order for the TI-Messenger-Client to successfully communicate with the Messenger-Proxy, it is necessary for the Messenger-Proxy to know the `client_id`. To do this, the TI-Messenger-Client manufacturer must make the `client_id` known to the TI-Messenger-Fachdienst provider. If different TI-Messenger-Clients are supported by a provider's Messenger-Proxy, all `client_ids` must be transmitted to the TI-Messenger-Fachdienst provider of the Messenger-Proxies.

==== Authentication procedure
In addition to authentication using an SMC-B or an HBA, other authentication methods can be supported by the Messenger-Service. This enables actors to reuse existing authentication methods in their organization. For example, an existing Active Directory in an organization.

In order to be able to provide this for the actors within an organization, the existing authentication procedure must be set up in the Matrix-Homeserver configuration. When using a Synapse server as a Matrix-Homeserver, for example, the `LDAP Auth Provider` module can be used for LDAP authentication according to https://github.com/matrix-org/matrix-synapse-ldap3[&#91;LDAP Auth Provider&#93;] be used. For this, the Synapse configuration file `/etc/matrix-synapse/homeserver.yaml` has to be adjusted as follows:

[source, yaml]
-----------------
modules:
- module: "ldap_auth_provider.LdapAuthProvider"
  config:
    enable: true
    uri: "ldap://DIRECTION_IP_DC:389"
    start_tls: false
    base: "ou=users,dc=example,dc=com"
    attributes:
       uid: "cn"
       mail: "mail"
       name: "givenName"
-----------------

When using an existing authentication method, a second factor must also be included. Here are the recommendations of the BSI, according to https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Accountschutz/Zwei-Faktor-Authentisierung/Bewertung-2FA-Verfahren/bewertung-2fa-verfahren_node.html[&#91;Technische Betrachtung&#93;] to be taken into account.

Possible 2nd factors would be:

* Verification via email

* SMS-TAN procedure

==== Proxy for the Matrix-Protocol
The Messenger-Proxy acts as a Reverse-Proxy and, after an authorization check, forwards all requests that correspond to a Matrix API to the Matrix-Homeserver.

==== Provision and administration of Freigabeliste
The approval list is a whitelist that contains all actors who are authorized by the respective actor to contact him. The list can be implemented in the form of a lookup table. The administration of an actor's approval list requires that the Messenger-Proxy provides the interface `I_TiMessengerContactManagement` according to https://github.com/gematik/api-ti-messenger/blob/feature/fachdienst/src/openapi/TiMessengerContactManagement.yaml[&#91;TIMessengerContactManagement&#93;]

To add an actor's MXID to the approval list, use the `createContactSetting` operation.

*Example of an HTTP message*

[cols="h,a",] 
|===
|URI        |\https::{domain}/tim-contact-mgmt/contacts
|Method     |POST
|Header |
[source, bash]
----
HTTP-Version: "HTTP/1.1"
----
|Body    |
[source, bash]
----
{
  "displayName": "Musterfrau, Erika",
  "mxid": "string",
  "inviteSettings": {
    "start": 1654159585,
    "end": 1654169585
  }
}
|===


*Sample query:*
[source, bash]
-----------------
curl -X 'POST' \
  'https://localhost/tim-contact-mgmt/v1.0/contacts' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "displayName": "Musterfrau, Erika",
  "mxid": "string",
  "inviteSettings": {
    "start": 1654159585,
    "end": 1654169585
  }
}'
----------------- 
 
The attributes `start` and `end` specify the period of authorization. 
 
==== Validation rules
TIP: The Messenger-Proxy must check the request to the Matrix-Homeserver for authorization for each `invite event`.

The authorization levels are described in *[gemSpec_TI-Messenger-Dienst#Berechtigungskonzept]*. In the case of a Client-Server communication, only the federation membership (Level 1) is checked. In the case of Server-Server communication, all authorization levels are passed through.

For verification according to authorization Level 1, it is necessary for the Messenger-Proxy to call up the federation list from the responsible Registrierungs-Dienst. This is described in *[gemSpec_TI-Messenger-FD#Messenger-Proxy]*.

=== Matrix-Homeserver
The subcomponent Matrix-Homeserver is a component that must have implemented the Matrix-Specification (Client-Server- / Server-Server-API). A well-known Matrix-Homeserver is https://matrix.org/docs/projects/server/synapse[[synapse]]. In general, this component does not have to be developed in-house. It is sufficient to configure them according to the requirements.

=== Push-Gateway
The Push Gateway subcomponent must be implemented according to the Matrix specification. https://spec.matrix.org/latest/push-gateway-api/[&#91;Push Gateway API&#93;]

= Operational aspects
The TI-Messenger provider is responsible for operating the TI-Messenger-Fachdienst. Central components such as the Registrierungs-Dienst and the Push-Gateway are provided and operated centrally by the TI-Messenger provider. A Messenger-Service can be operated both in a data center of the TI-Messenger provider and on premise on the premises of an organization by the TI-Messenger provider.

???Deplyoment???

= Referenced documents
The table below contains the gematik documents referenced in this online documentation. The version number valid for this document can be found in the current document map published on the gematik website, in which the present version is listed.

|===
|[Source] |Editor: Title

|*[gemSpec_TI-Messenger-FD]* |gematik: Spezifikation TI-Messenger-Fachdienst
|*[gemSpec_IDP_FD]* | gematik: Spezifikation Identity Provider – Nutzungsspezifikation für Fachdienste 
|===
