ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../images
:toc: macro
:toclevels: 3
:toc-title: table of content
:numbered:

image:gematik_logo.svg[width=70%]

toc::[]

= Use-Cases
This page shall give the reader an overview of the most common use-cases for TI-Messenger users. Besides the introduction every chapter contains a brief overview of the use-case itself and a sequence diagram showing the interaction between the involved components.

TIP: The service calls might not include all parameters need for the call. A detailed description is located: TODO

IMPORTANT:  The following sequence diagrams might not include all failure cases. They focus on the most common failure cases for each individual use-case. 

== Messenger service
To start exchanging messages with other users the organisation needs a messenger service offered by the selected provider. 

++++
<p align="center">
  TODO some Picture
</p>
++++

=== AF_10103 Authentication of an organisation on the TI-Messenger service
In case the organization has never been authenticated at the registration service, this is the first step that has to be taken. First the user has to identify that he acts in place of a valid organization in the german healthcare system. To do so organization's SMC-B is needed to answer the authentication challenge of the central IDP-Service. 
Next to the SMC-B the user who is starting the process needs: 
[square]
* access to the frontend of the registration service
* the registration service frontend is registered at the central IDP-Service
* a connector that is connected to the gematik network
* a card terminal for the organization's SMC-B connected to the connector
* an authenticator is available for the data exchange with the connector 
* the SMC-B is plugged in the card terminal and unlocked
* a valid domain for the TI-Messenger-Dienst

After a successful Authentication with the SMC-B an Admin Account can be created and used to create a TI-Messenger Fachdienst for the organization.

.AF_10103 use case description
[%collapsible]
====
[caption=]
.Authentication of an organisation on the TI-Messenger service
[%header, cols="1,1"]
|===
| |description
|Actor |Representative of an organisation in the "Org Admin" role
|Trigger |The administrator of the organisation (Org Admin) wants to make their organisation accessible by storing the MXIDs of the actors of the organisation in the VZD-FHIR directory.
|Components a|
              * TI-Messenger client (with advanced Org Admin functionality), 
              * Authenticator
              * IDP-Dienst
              * VZD Auth service
              * FHIR proxy
              * FHIR directory
|Preconditions a| 
                  * A messenger service was provided to the organisation and a FHIR resource was created in the VZD-FHIR directory.
                  * The organisation administrator has a TI-Messenger client (with advanced Org Admin functionality).
                  * The VZD-FHIR directory is registered with a responsible IDP service.
                  * The organisation administrator can authenticate themselves using a responsible IDP service.
|Input data |SMC-B, FHIR organisation resources
|Result |FHIR organisation resources updated, status
|Output data |Updated VZD-FHIR directory records 
|===
====

.AF_10103 sequence diagram
[%collapsible]
====
++++
<p align="center">
  <img width="75%" src=../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10103_Seq.svg>
</p>
++++
====

=== AF_10060 Provision of messenger service to an organisation
After a successful authentication the user can use the admin credentials to log into the registration service. After a successful login the user is able to create new messenger services(TODO ref API) by providing a domain name. This domain name will be checked. (TODO list check examples). Afterwards a messenger service will be created and configured. To take part in the TI-messenger federation the new service domain has to be added to the federation list hosted at the VZD-FHIR directory. (TODO Ref auf provider access token and addtimessengerDomain Endpoint)

.AF_10060 use case description
[%collapsible]
====
[caption=]
Provision of messenger service to an organisation
[%header, cols="1,1"]
|===
| |description
|Actor |Representative of an organisation in the "Org Admin" role
|Trigger |An organisation of the German healthcare system wants to participate in the TI-Messenger service and needs to provide one or more messenger services
|Components a|
              * Front end of the registration service, 
              * Registrierungs-Dienst, 
              * VZD-FHIR directory,
              * Messenger-Service 
|Preconditions a| 
                  * There is a contractual relationship with a TI-Messenger provider. 
                  * The operator has a front end of the registration service for communication with the registration service.
                  * The used front end of the registration service is registered with the responsible IDP service.
                  * The SMC-B inserted in the eHealth card terminal is enabled.
                  * The registration service can authenticate itself with the VZD-FHIR directory server for write access
                    with OAuth2.
|Input data |Admin account, identity of organisation (SMC-B)
|Result a|
            * The messenger service for the organisation has been created.
            * The Matrix domain of the new messenger service was entered as an endpoint in the VZD-FHIR directory and  
              included in the federation.
|Output data |New messenger service for the organisation, status
|===
====
.AF_10060 sequence diagram 
[%collapsible]
====
++++
<p align="center">
  <img width="60%" src=../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10060_Seq.svg>
</p>
++++
====

=== AF_10064 Check federation affiliation of a messenger service
This use case checks whether a messenger service is part of the TI-Messenger federation and applies to all use cases that have to check the Matrix domain of another messenger service. For checking the affiliation of the Matrix domain with the TI-Messenger federation, the messenger proxy uses a federation list that is provided by the registration service of its TI-Messenger specialist service. The storage time of the messenger proxy federation list is limited. 

.AF_10064 use case description
[%collapsible]
====
[caption=]
Check federation affiliation of a messenger service
[%header, cols="1,1"]
|===
| |description
|Actor |-
|Trigger |The messenger proxy receives an Invite event and MUST check the MXIDs included in the request for domain belonging to the TI-Messenger federation.
|Components a|
              * Messenger proxy,
              * Matrix home server 
|Preconditions a| none
|Input data |Invite Event
|Result a|The messenger proxy uses the federation list to determine whether the Matrix domain of the other messenger service is part of the TI-Messenger federation.
|Output data |Status of the Matrix home server and forwarding
|===
====
.AF_10064 sequence diagram 
[%collapsible]
====
++++
<p align="center">
  <img width="60%" src=../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10064_Seq.svg>
</p>
++++
====

===  update of the federation list
The following figure describes how the messenger proxy updates its locally maintained federation list. To update the federation list, the messenger proxy MUST request it from the registration service of its TI-Messenger specialist service. The frequency of requesting a new list is determined by the provider, the goal should be to have a federation list as up-to-date as possible (but at least once a day). Here, the messenger proxy transfers the saved version of the federation list to the registration service. If the version matches, no new federation list will be provided by the registration service for the messenger proxy. If the version is larger than the one passed by the messenger proxy, an updated federation list is provided by the registration service. Each time a messenger proxy is requested from the registration service for a current federation list, the registration service MUST also check the up-to-dateness of the FHIR proxy by handing over the version of the federation list it has saved when calling the FHIR proxy. A download of the federation list is only necessary if a newer version exists on the FHIR proxy. The structure of the federation list is described in [gemSpec_VZD_FHIR_Directory]. After retrieving the federation list from the registration service, through the messenger proxy, the latter MUST check the signature of the federation list. 

.use case description
[%collapsible]
====
[caption=]
update of the federation list
[%header, cols="1,1"]
|===
| |description
|Actor |messenger proxy
|Trigger |-
|Components a|
              * Messenger proxy,
              * registration service,
              * FHIR-proxy
              * Auth-Service VZD 
|Preconditions a| none
|Input data |actual version number
|Result a|The messenger proxy retrieves a status if the current list is not outdated or a new federation list in case the proxy owns an older one
|Output data |status, federation list
|===
====
.sequence diagram 
[%collapsible]
====
++++
<p align="center">
  <img width="60%" src=../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_Update_Federationlist_Seq.svg>
</p>
++++
====

=== Authorisation check
The following figure describes how to check the entitlement of incoming Matrix requests on the messenger proxy. The authorisation concept is based on a three-stage check, which is described in the "Authorisation concept" section. The mention of necessary authentications is omitted here.

.use case description
[%collapsible]
====
[caption=]
Authorisation Check
[%header, cols="1,1"]
|===
| |description
|Actor |messenger proxy
|Trigger |-
|Components a|
              * Messenger proxy A+B,
              * Matrix home server A+B,
              * registration service,
              * FHIR-proxy
              * VZD-FHIR directory 
|Preconditions a| none
|Input data |actual version number
|Result a|The messenger proxy retrieves a status if the current list is not outdated or a new federation list in case the proxy owns an older one
|Output data |status, federation list
|===
====
.sequence diagram 
[%collapsible]
====
++++
<p align="center">
  <img width="60%" src=../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_Approvel_List_Seq.svg>
</p>
++++
====

== VZD Resource management
The VZD-FHIR directory is the main address book for organizations and people in the german healtcare system. The following chapters explain in details what is needed to change the organization or practitioner information in the VZD-FHIR directory. (TODO ref to the FHIR resources)

=== AF_10059 Add organisation resources to directory service
With the aquisition of the SMC-B an entry for the organisation will be created in the VZD-FHIR directory by the [TODO]. 

.AF_10059 use case description
[%collapsible]
====
[caption=]
Add organisation resources to directory service
[%header, cols="1,1"]
|===
| |description
|Actor |Representative of an organisation in the "Org Admin" role
|Trigger |An organisation of the German healthcare system wants to participate in the TI-Messenger service and needs to provide one or more messenger services
|Components a|
              * Front end of the registration service, 
              * Registrierungs-Dienst, 
              * VZD-FHIR directory,
              * Messenger-Service 
|Preconditions a| 
                  * There is a contractual relationship with a TI-Messenger provider. 
                  * The operator has a front end of the registration service for communication with the registration service.
                  * The used front end of the registration service is registered with the responsible IDP service.
                  * The SMC-B inserted in the eHealth card terminal is enabled.
                  * The registration service can authenticate itself with the VZD-FHIR directory server for write access
                    with OAuth2.
|Input data |Admin account, identity of organisation (SMC-B)
|Result a|
            * The messenger service for the organisation has been created.
            * The Matrix domain of the new messenger service was entered as an endpoint in the VZD-FHIR directory and  
              included in the federation.
|Output data |New messenger service for the organisation, status
|===
====

.AF_10059 sequence diagram 
[%collapsible]
====
++++
<p align="center">
  <img width="60%" src=../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10059_Seq.svg>
</p>
++++
====

=== AF_10058 Akteur (User-HBA) im Verzeichnisdienst hinzufügen
With this use case, an actor in the "User-HBA" role can be found and reached for other actors of other messenger services. For this purpose, FHIR resources with their respective MXID are stored in the person directory (PractitionerRole) of the VZD-FHIR directory. In addition, it is possible to limit visibility for other actors. This use case MAY be directly combined with the initial login process of an actor to the messenger service (see use case: "AF_10057 – Login of an actor to the messenger service"). For this purpose, the actor in the "User-HBA" role is asked by the TI-Messenger client during the login process whether they have an HBA.

.AF_10058 use case description
[%collapsible]
====
[caption=]
Bereitstellung eines Messenger-Service für eine Organisation
[%header, cols="1,1"]
|===
| |description
|Actor |Service provider, a healthcare organisation employee in the "User-HBA" role
|Trigger |An actor in the "User-HBA" role wants to be accessible in the person directory by storing their MXID in their Practitioner record in the VZD-FHIR directory.
|Components a|
              * TI-Messenger-Client,
              * Authenticator,
              * IDP service, 
              * FHIR Proxy, 
              * Auth service,
              * VZD-FHIR directory,
|Preconditions a| 
                  * The actor is logged in to a valid messenger service (see AF_10057). 
                  *	The actor has an approved TI-Messenger client.
                  * The VZD-FHIR directory is registered with a responsible IDP service.
                  * The actor can authenticate themselves using the IDP service.
                  * The registration service can authenticate itself with the VZD-FHIR directory server for write access
                    with OAuth2.
|Input data |Admin account, identity of organisation (SMC-B)
|Result a|
            * The messenger service for the organisation has been created.
            * The Matrix domain of the new messenger service was entered as an endpoint in the VZD-FHIR directory and  
              included in the federation.
|Output data |New messenger service for the organisation, status
|===
====
.AF_10058 sequence diagram 
[%collapsible]
====
++++
<p align="center">
  <img width="55%" src=../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10058_Seq.svg>
</p>
++++
====

=== Search Entries in the VZD-FHIR directory
The following figure describes how an actor searches for HealthcareService and PractitionerRole resources in the VZD-FHIR directory. This requires a successful login of the actor to a messenger service. The shown procedure displays all communication relationships that are necessary in principle. Further information on the procedure can be found in [gemSpec_VZD_FHIR_Directory].

.use case description
[%collapsible]
====
[caption=]
Search Entries in the VZD-FHIR directory
[%header, cols="1,1"]
|===
| |description
|Actor |a user in the role "User/User-HBA"
|Trigger |An actor in the "User"/"User-HBA" role want to search in the FHIR-VZD
|Components a|
              * TI-Messenger-Client,
              * messenger proxy,
              * Matrix-Homeserver
              * FHIR Proxy, 
              * Auth service,
              * VZD-FHIR directory,
|Preconditions a| 
                  * The actor is logged in to a valid messenger service (see AF_10057). 
                  *	The actor has an approved TI-Messenger client.
                  * The Matrix Home Server is a trusted IDP
                  * The actor can authenticate themselves using the matrix OpenID Token
|Input data |Search, Matrix OpenID Token
|Result a|The searched FHIR-Resources
|Output data |FHIR Records
|===

====
.sequence diagram
[%collapsible]
====
++++
<p align="center">
  <img width="55%" src=../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_Directory_search_Seq.svg>
</p>
++++
====

== User communication

=== AF_10057 Signing in to messenger service
With this use case, an actor logs in to a messenger service responsible for the TI federation and registers their TI-Messenger client as the end device. The actor MUST be able to enter the Matrix domain of the desired messenger service directly into the TI-Messenger client. The input MAY be automated or supported by other tools such as a QR code scan. The authentication is performed according to the specifications of the respective organisation. After the successful login of an actor to the messenger service, the services offered by it MAY be used.

.AF_10057 use case description
[%collapsible]
====
[caption=]
Signing in to messenger service
[%header, cols="1,1"]
|===
| |description
|Actor |Service provider, employee of an organisation in the "User/User-HBA" role
|Trigger |An actor wants to register with a messenger service with their TI-Messenger client.
|Components a|
              * TI-Messenger-Client,
              * Messenger proxy,
              * Messenger home server, 
              * Auth service (FHIR directory)
|Preconditions a| 
                  * The actor has a TI-Messenger client supported by the provider. 
                  *	The actor knows the messenger service URL or the URL is already configured in their TI-Messenger client.
                  *	The actor can identify themselves through an authentication process supported by the Matrix home server. If a separate authentication procedure is used by the organisation, a connection to the Matrix home server MUST have been made.
                  *	The Matrix home server used is integrated into the federation (valid messenger service).
|Input data |URL of the matrix home server
|Result a|
            A TI-Messenger account was created for an actor in the "User/User-HBA" role
|Output data |Matrix-ACCESS_TOKEN, MXID, device_id, status
|===
====
.AF_10057 sequence diagram 
[%collapsible]
====
++++
<p align="center">
  <img width="55%" src=../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10057_Seq.svg>
</p>
++++
====

=== AF_10104 Invitation of actors within an organisation
In this use case, an actor belonging to a common organisation is invited to a room to carry out actions. To search for actors within a common organisation, a TI-Messenger client searches its organisation's user directory on the Matrix home server. In this use case, the messenger proxy checks whether the Matrix domains contained in the Invite event are part of the TI federation (see Authorisation concept – Stage 1). If this is the case, it is forwarded to the corresponding Matrix home server. The latter checks whether the involved actors are registered with it. If this is not the case, the invited actor is not an actor within the organisation and the Invite event is forwarded to the Matrix home server of the invited actor. The use case "AF_10061 – Invitation of actors outside an organisation" shows the resulting course of events.

.AF_10104 use case description
[%collapsible]
====
[caption=]
Invitation of actors within an organisation
[%header, cols="1,1"]
|===
| |description
|Actor |Service provider, employee of an organisation in the "User/User-HBA" role
|Trigger |Actor A wants to invite actor B of their organisation to a shared space.
|Components a|
              * TI-Messenger-Client A + B,
              * Messenger proxy,
              * Messenger home server, 
              * Push gateway
|Preconditions a| 
                  * The actors are logged in to the same messenger service.
                  * Each actor has an approved TI-Messenger client.
                  *	A chat room has been set up by the inviter.
|Input data | Matrix Invite Event
|Result a|
            Actor A and actor B are both in a shared chat room.
Optionally, a notification is sent to actor B about the invitation to the chat room.
|Output data |status
|===
====
.AF_10104 sequence diagram 
[%collapsible]
====
++++
<p align="center">
  <img width="55%" src=../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10104_Seq.svg>
</p>
++++
====

=== AF_10063 Exchange of events between actors within an organisation
This use case allows actors who are in a common space within a messenger service to exchange messages and execute other actions (events) defined by the Matrix specification.

.AF_10063 use case description
[%collapsible]
====
[caption=]
Exchange of events between actors within an organisation
[%header, cols="1,1"]
|===
| |description
|Actor |Service provider, employee of an organisation in the "User/User-HBA" role
|Trigger |All Matrix events performed within an organisation's messenger service
|Components a|
              * TI-Messenger-Client A + B,
              * Messenger proxy,
              * Messenger home server, 
              * Push gateway
|Preconditions a| 
                  * The actors are logged in to the same messenger service.
                  * Each actor has an approved TI-Messenger client.
                  *	The participants have joined a common space.
|Input data | Matrix Event
|Result a|Matrix event was successfully processed
|Output data |Dependent on the matrix event
|===
====
.AF_10063 sequence diagram 
[%collapsible]
====
++++
<p align="center">
  <img width="55%" src=../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10063_Seq.svg>
</p>
++++
====

=== AF_10061 Invitation of actors outside an organisation
In this use case, an actor outside an organisation is invited. The VZD-FHIR directory can be used to search for actors outside the organisation. If the MXID of the sought actor does not exist there, contact must also be made via a QR code scan. In contrast to an invitation of actors within an organisation (see "AF_10063 – Exchange of events within an organisation"), in this use case the messenger proxy of the invitee additionally checks the criteria defined in the"Authorisation concept" section (Stages 1-3).

.AF_10061 use case description
[%collapsible]
====
[caption=]
Invitation of actors outside an organisation
[%header, cols="1,1"]
|===
| |description
|Actor |Service provider, employee of an organisation in the "User/User-HBA" role
|Trigger |Actor A wants to set up a shared chat room with actor B outside an organisation.
|Components a|
              * TI-Messenger-Client A + B,
              * Messenger proxy A + B,
              * Messenger home server A + B, 
              * VZD-FHIR directory,
              * Push gateway B
|Preconditions a| 
                  * The actors have an approved TI-Messenger client.
                  * The actors are logged into the messenger services (see AF_10057)
                  * Both messenger services are part of the federation.
|Input data | Matrix Invite Event
|Result a|Actor A and actor B are both in a shared chat room.
Optionally, a notification is sent to actor B about the invitation to the chat room.
|Output data |status
|===
====
.AF_10061 sequence diagram 
[%collapsible]
====
++++
<p align="center">
  <img width="55%" src=../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10061_Seq.svg>
</p>
++++
====

=== AF_10062 Exchange of events between actors outside an organisation
In this use case, actors in a common space can exchange messages and execute other actions specified by the Matrix specification. This use case requires a successful Invite event for one or more involved actors. In this use case, the involved actors are distributed in a shared chat room and across different messenger services.

.AF_10062 use case description
[%collapsible]
====
[caption=]
Exchange of events between actors outside an organisation
[%header, cols="1,1"]
|===
| |description
|Actor |Service provider, employee of an organisation in the "User/User-HBA" role
|Trigger |All Matrix events run between messenger services of different organisations.
|Components a|
              * TI-Messenger-Client A + B,
              * Messenger proxy A + B,
              * Messenger home server A + B, 
              * Push gateway B
|Preconditions a| 
                  * The actors are logged in to the same messenger service.
                  * Each actor has an approved TI-Messenger client.
                  *	The participants have joined a common space.
                  *	The messenger proxies have a current federation list.
|Input data | Matrix Event
|Result a|Matrix event was successfully processed
|Output data |Dependent on the matrix event
|===
====
.AF_10062 sequence diagram 
[%collapsible]
====
++++
<p align="center">
  <img width="55%" src=../images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10062_Seq.svg>
</p>
++++
====