/'
# TI-Messenger
# Include Datei zur Festlegung eines einheitlichen Aussehens der PlantUML Diagramme
# Name: gem-tim.iuml
'/

@startuml
skinparam dpi 100
skinparam sequenceMessageAlign direction
skinparam minClassWidth 200
skinparam BoxPadding 1
skinparam sequenceReferenceHeaderBackgroundColor palegreen
scale max 2048 width

skinparam sequence {
    ArrowColor black
    ArrowFontSize 17
    ActorBorderColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor Gainsboro

    'ParticipantFontName Impact
    ParticipantFontSize 20
    ParticipantFontColor black
    ParticipantBorderColor Black
    ParticipantBackgroundColor MOTIVATION

    ActorBackgroundColor Gainsboro
    ActorFontColor black
    ActorFontSize 20
    'ActorFontName Aapex
}
@enduml